import { InventoryItem, InspectionRecord, ProductionOrder, AuditLog, ReceiveRecord, IssueRecord } from '../types/erp';

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-101',
    sku: 'FAB-CTN-180-WHT',
    styleNumber: 'STY-TS-2026',
    buyerOrderId: 'ord-1',
    buyerName: 'H&M Hennes & Mauritz',
    poNumber: 'PO-HM-99201',
    bomItemId: 'bom-1',
    fabricType: '100% Combed Cotton Single Jersey (180 GSM)',
    color: 'Optic White',
    batchLot: 'LOT-TX-9041A',
    rollCount: 42,
    quantityMeters: 4250.5,
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-R01-B04',
    status: 'IN_STOCK',
    unitCost: 3.45,
    supplierName: 'Square Textiles Ltd',
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'inv-102',
    sku: 'FAB-DNM-12OZ-IND',
    styleNumber: 'STY-DN-502',
    buyerOrderId: 'ord-2',
    buyerName: 'Inditex / Zara',
    poNumber: 'PO-ZARA-4482',
    bomItemId: 'bom-201',
    fabricType: 'Rigid Indigo Slub Denim (12.5 Oz)',
    color: 'Deep Indigo Stone',
    batchLot: 'LOT-TX-9042D',
    rollCount: 28,
    quantityMeters: 2840.0,
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-R02-B08',
    status: 'ALLOCATED',
    unitCost: 5.8,
    supplierName: 'Envoy Textiles Ltd',
    updatedBy: 'Tania Ahmed',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: 'inv-103',
    sku: 'FAB-PLY-TC-240-NVY',
    styleNumber: 'STY-TH-1190-02',
    fabricType: '65/35 Poly-Cotton Twill Chino (240 GSM)',
    color: 'Classic Navy',
    batchLot: 'LOT-TX-9043B',
    rollCount: 16,
    quantityMeters: 1450.2,
    qualityGrade: 'GRADE_B',
    warehouseLocation: 'WH-R01-B12',
    status: 'INSPECTING',
    unitCost: 4.15,
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: 'inv-104',
    sku: 'FAB-FTER-320-BLK',
    styleNumber: 'STY-NK-7741-05',
    fabricType: 'Heavy French Terry Organic (320 GSM)',
    color: 'Carbon Black',
    batchLot: 'LOT-TX-9044C',
    rollCount: 35,
    quantityMeters: 3120.0,
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-R03-B02',
    status: 'IN_STOCK',
    unitCost: 6.2,
    updatedBy: 'Kazi Farhan',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'inv-105',
    sku: 'FAB-VIS-EL-190-MAR',
    styleNumber: 'STY-UQ-3310-04',
    fabricType: '95/5 Viscose Elastane Rib 2x2 (190 GSM)',
    color: 'Burgundy Heather',
    batchLot: 'LOT-TX-9045E',
    rollCount: 12,
    quantityMeters: 890.0,
    qualityGrade: 'ON_HOLD',
    warehouseLocation: 'WH-QUARANTINE-01',
    status: 'INSPECTING',
    unitCost: 4.9,
    updatedBy: 'Tania Ahmed',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: 'inv-106',
    sku: 'FAB-LIN-BL-160-NAT',
    styleNumber: 'STY-ZR-5501-11',
    fabricType: '55/45 Linen Cotton Slub Plain Weave',
    color: 'Natural Ecru',
    batchLot: 'LOT-TX-9046A',
    rollCount: 22,
    quantityMeters: 2180.5,
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-R02-B04',
    status: 'IN_STOCK',
    unitCost: 7.1,
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
  {
    id: 'inv-107',
    sku: 'FAB-TC-POPL-120-LBL',
    styleNumber: 'STY-GAP-9902-01',
    fabricType: 'Fine Yarn-Dyed Poplin Stripe (120 GSM)',
    color: 'Sky Blue Pin Stripe',
    batchLot: 'LOT-TX-9047D',
    rollCount: 8,
    quantityMeters: 620.0,
    qualityGrade: 'REJECTED',
    warehouseLocation: 'WH-REJECT-BAY',
    status: 'INSPECTING',
    unitCost: 3.9,
    updatedBy: 'Tania Ahmed',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
  {
    id: 'inv-108',
    sku: 'FAB-MICRO-PLY-90-RED',
    styleNumber: 'STY-NK-8822-08',
    fabricType: '100% Poly Micro Ripstop Water-Repellent',
    color: 'Crimson Red',
    batchLot: 'LOT-TX-9048F',
    rollCount: 30,
    quantityMeters: 3600.0,
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-R04-B01',
    status: 'IN_STOCK',
    unitCost: 4.8,
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: 'inv-109',
    sku: 'FAB-CTN-SP-220-KHK',
    styleNumber: 'STY-TH-3391-03',
    fabricType: '98/2 Cotton Spandex Stretch Sateen',
    color: 'British Khaki',
    batchLot: 'LOT-TX-9049A',
    rollCount: 26,
    quantityMeters: 2480.0,
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-R02-B11',
    status: 'ALLOCATED',
    unitCost: 5.3,
    updatedBy: 'Kazi Farhan',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: 'inv-110',
    sku: 'FAB-BMB-JER-170-SGE',
    styleNumber: 'STY-UQ-7712-07',
    fabricType: 'Bamboo Organic Cotton Breathable Jersey',
    color: 'Sage Moss Green',
    batchLot: 'LOT-TX-9050C',
    rollCount: 18,
    quantityMeters: 1750.0,
    unit: 'Meters',
    category: 'FABRIC',
    supplierName: 'Pacific Textiles Mills Ltd',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-R03-B07',
    status: 'IN_STOCK',
    unitCost: 6.4,
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  // --- RAW MATERIALS: SEWING THREAD ---
  {
    id: 'inv-201',
    sku: 'TRD-COATS-120-WHT',
    category: 'SEWING_THREAD',
    styleNumber: 'STY-TS-2026',
    buyerOrderId: 'ord-1',
    buyerName: 'H&M Hennes & Mauritz',
    poNumber: 'PO-HM-99201',
    bomItemId: 'bom-2',
    fabricType: 'Coats Epic 120 High-Tenacity Polyester Core Spun Thread (5000m)',
    color: 'Optic White #01',
    batchLot: 'LOT-CT-4819',
    rollCount: 0,
    quantityMeters: 450, // Cones
    unit: 'Cones',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-TRIM-A01',
    status: 'IN_STOCK',
    unitCost: 2.15,
    supplierName: 'Coats Bangladesh Ltd',
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: 'inv-202',
    sku: 'TRD-ASTRA-080-BLK',
    category: 'SEWING_THREAD',
    styleNumber: 'STY-NK-7741-05',
    fabricType: 'Coats Astra 80 Spun Polyester Heavy Seaming Thread',
    color: 'Jet Black #99',
    batchLot: 'LOT-CT-4822',
    rollCount: 0,
    quantityMeters: 320,
    unit: 'Cones',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-TRIM-A02',
    status: 'IN_STOCK',
    unitCost: 2.45,
    supplierName: 'Coats Bangladesh Ltd',
    updatedBy: 'Tania Ahmed',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  // --- RAW MATERIALS: TRIMS & BUTTONS ---
  {
    id: 'inv-301',
    sku: 'BTN-HRN-24L-BRN',
    category: 'TRIMS_BUTTONS',
    styleNumber: 'STY-ZR-5501-11',
    fabricType: 'Eco Resin Imitation Horn Button 24L (4-Hole Rimmed)',
    color: 'Mottled Tortoise Brown',
    batchLot: 'LOT-BTN-8812',
    rollCount: 0,
    quantityMeters: 180, // Gross
    unit: 'Gross',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-ACC-B03',
    status: 'IN_STOCK',
    unitCost: 1.85,
    supplierName: 'Avery Dennison RBIS',
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
  {
    id: 'inv-302',
    sku: 'RVT-BRS-9MM-ANT',
    category: 'TRIMS_BUTTONS',
    styleNumber: 'STY-ZR-4882-09',
    fabricType: 'Antique Brass Denim Reinforcement Rivets 9mm',
    color: 'Antique Brass',
    batchLot: 'LOT-RVT-1140',
    rollCount: 0,
    quantityMeters: 25000,
    unit: 'Pcs',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-ACC-B05',
    status: 'ALLOCATED',
    unitCost: 0.04,
    supplierName: 'YKK Fastening Auto Products',
    updatedBy: 'Kazi Farhan',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  // --- RAW MATERIALS: ZIPPERS ---
  {
    id: 'inv-401',
    sku: 'ZIP-YKK-M5-IND',
    category: 'ZIPPERS',
    styleNumber: 'STY-ZR-4882-09',
    fabricType: 'YKK #5 Closed-End Metal Zipper with Locking Slider (7 inch)',
    color: 'Deep Indigo Stone / Brass',
    batchLot: 'LOT-YKK-9921',
    rollCount: 0,
    quantityMeters: 8500,
    unit: 'Pcs',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-ACC-C01',
    status: 'IN_STOCK',
    unitCost: 0.48,
    supplierName: 'YKK Fastening Auto Products',
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  // --- RAW MATERIALS: INTERLINING & ELASTIC ---
  {
    id: 'inv-501',
    sku: 'INT-KUF-W75-GRY',
    category: 'INTERLINING_ELASTIC',
    styleNumber: 'STY-TH-1190-02',
    fabricType: 'Kufner 75 GSM Woven Polyester Fusible Microdot Interlining',
    color: 'Charcoal Grey',
    batchLot: 'LOT-KF-3310',
    rollCount: 15,
    quantityMeters: 3200,
    unit: 'Meters',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-R05-B02',
    status: 'IN_STOCK',
    unitCost: 1.25,
    supplierName: 'Kufner Interlining Asia',
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: 'inv-502',
    sku: 'ELA-JCQ-40-NVY',
    category: 'INTERLINING_ELASTIC',
    styleNumber: 'STY-UQ-3310-04',
    fabricType: '40mm High-Recovery Knitted Jacquard Waistband Elastic',
    color: 'Navy / Silver Stripe',
    batchLot: 'LOT-EL-6621',
    rollCount: 25,
    quantityMeters: 4500,
    unit: 'Yards',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-R05-B06',
    status: 'IN_STOCK',
    unitCost: 0.65,
    supplierName: 'Apex Elastic Industries',
    updatedBy: 'Tania Ahmed',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  // --- RAW MATERIALS: LABELS & PACKAGING ---
  {
    id: 'inv-601',
    sku: 'LBL-WVN-DMK-HM',
    category: 'LABELS_PACKAGING',
    styleNumber: 'STY-HM-2026-01',
    fabricType: 'H&M Organic Damask High-Definition Woven Neck Label (Heat-cut)',
    color: 'Soft White / Black Text',
    batchLot: 'LOT-AD-5510',
    rollCount: 0,
    quantityMeters: 35000,
    unit: 'Pcs',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-PKG-A01',
    status: 'IN_STOCK',
    unitCost: 0.035,
    supplierName: 'Avery Dennison RBIS',
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'inv-602',
    sku: 'PKG-PLY-SLF-M',
    category: 'LABELS_PACKAGING',
    styleNumber: 'STY-HM-2026-01',
    fabricType: 'Self-Adhesive Recycled LDPE Polybag with 14-Language Warning (M)',
    color: 'Clear Transparent',
    batchLot: 'LOT-BP-9912',
    rollCount: 0,
    quantityMeters: 28000,
    unit: 'Pcs',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-PKG-B02',
    status: 'IN_STOCK',
    unitCost: 0.022,
    supplierName: 'Bengal Poly & Carton Ltd',
    updatedBy: 'Kazi Farhan',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: 'inv-603',
    sku: 'PKG-CTN-5PLY-EXP',
    category: 'LABELS_PACKAGING',
    styleNumber: 'STY-ZR-4882-09',
    fabricType: '5-Ply Heavy-Duty Corrugated Master Export Carton (60 x 40 x 35 cm)',
    color: 'Kraft Natural Brown',
    batchLot: 'LOT-BP-9918',
    rollCount: 0,
    quantityMeters: 1200,
    unit: 'Pcs',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-PKG-C01',
    status: 'IN_STOCK',
    unitCost: 1.45,
    supplierName: 'Bengal Poly & Carton Ltd',
    updatedBy: 'Rafiqul Islam',
    lastUpdatedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
];

// --- GOODS RECEIVED NOTE (GRN) INWARD REGISTRY ---
export const INITIAL_RECEIVE_REGISTRY: ReceiveRecord[] = [
  {
    id: 'grn-01',
    grnNumber: 'GRN-2026-0891',
    date: '2026-09-20',
    itemId: 'inv-101',
    sku: 'FAB-CTN-180-WHT',
    category: 'FABRIC',
    itemName: '100% Combed Cotton Single Jersey (180 GSM)',
    supplierName: 'Pacific Textiles Mills Ltd',
    poNumber: 'PO-HM-99201',
    buyerOrderId: 'ord-1',
    buyerName: 'H&M Hennes & Mauritz',
    styleNumber: 'STY-TS-2026',
    bomItemId: 'bom-1',
    bomItemCode: 'FAB-CTN-180',
    challanNumber: 'CH-PT-88301',
    receivedQty: 4250.5,
    unit: 'Meters',
    rollsReceived: 42,
    batchLot: 'LOT-TX-9041A',
    qcStatus: 'PASSED',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-R01-B04',
    receivedBy: 'Rafiqul Islam (Store Officer)',
    inspectedBy: 'Kazi Farhan (Senior QC)',
    notes: 'ASTM 4-point inspected: 14 pts/100 sq.yd. Approved for spreading.',
  },
  {
    id: 'grn-02',
    grnNumber: 'GRN-2026-0890',
    date: '2026-09-19',
    itemId: 'inv-201',
    sku: 'TRD-COATS-120-WHT',
    category: 'SEWING_THREAD',
    itemName: 'Coats Epic 120 Polyester Thread',
    supplierName: 'Coats Bangladesh Ltd',
    poNumber: 'PO-HM-99201',
    buyerOrderId: 'ord-1',
    buyerName: 'H&M Hennes & Mauritz',
    styleNumber: 'STY-TS-2026',
    bomItemId: 'bom-2',
    bomItemCode: 'THR-ASTRA-40',
    challanNumber: 'CH-CB-44912',
    receivedQty: 450,
    unit: 'Cones',
    batchLot: 'LOT-CT-4819',
    qcStatus: 'PASSED',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-TRIM-A01',
    receivedBy: 'Rafiqul Islam',
    inspectedBy: 'Tania Ahmed',
    notes: 'Color shade tolerance deltaE < 0.3. Passed sewability test.',
  },
  {
    id: 'grn-03',
    grnNumber: 'GRN-2026-0889',
    date: '2026-09-18',
    itemId: 'inv-401',
    sku: 'ZIP-YKK-M5-IND',
    category: 'ZIPPERS',
    itemName: 'YKK #5 Closed-End Metal Zipper 7"',
    supplierName: 'YKK Fastening Auto Products',
    poNumber: 'PO-ZARA-4482',
    buyerOrderId: 'ord-2',
    buyerName: 'Inditex / Zara',
    styleNumber: 'STY-DN-502',
    bomItemId: 'bom-202',
    bomItemCode: 'ZIP-YKK-M4',
    challanNumber: 'CH-YKK-00192',
    receivedQty: 8500,
    unit: 'Pcs',
    batchLot: 'LOT-YKK-9921',
    qcStatus: 'PASSED',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-ACC-C01',
    receivedBy: 'Rafiqul Islam',
    inspectedBy: 'Kazi Farhan',
    notes: 'Puller strength tested at 350N. Passed nickel-free test.',
  },
  {
    id: 'grn-04',
    grnNumber: 'GRN-2026-0888',
    date: '2026-09-17',
    itemId: 'inv-105',
    sku: 'FAB-VIS-EL-190-MAR',
    category: 'FABRIC',
    itemName: '95/5 Viscose Elastane Rib 2x2',
    supplierName: 'Pacific Textiles Mills Ltd',
    poNumber: 'PO-UQ-3310',
    challanNumber: 'CH-PT-88240',
    receivedQty: 890,
    unit: 'Meters',
    rollsReceived: 12,
    batchLot: 'LOT-TX-9045E',
    qcStatus: 'QUARANTINE',
    qualityGrade: 'ON_HOLD',
    warehouseLocation: 'WH-QUARANTINE-01',
    receivedBy: 'Tania Ahmed',
    inspectedBy: 'Rafiqul Islam',
    notes: 'Color bowing observed on rolls 3 and 7. Lab wash fastness pending.',
  },
  {
    id: 'grn-05',
    grnNumber: 'GRN-2026-0887',
    date: '2026-09-16',
    itemId: 'inv-601',
    sku: 'LBL-WVN-DMK-HM',
    category: 'LABELS_PACKAGING',
    itemName: 'H&M Damask Woven Neck Label',
    supplierName: 'Avery Dennison RBIS',
    poNumber: 'PO-HM-99201',
    challanNumber: 'CH-AD-77319',
    receivedQty: 35000,
    unit: 'Pcs',
    batchLot: 'LOT-AD-5510',
    qcStatus: 'PASSED',
    qualityGrade: 'GRADE_A',
    warehouseLocation: 'WH-PKG-A01',
    receivedBy: 'Rafiqul Islam',
    inspectedBy: 'Tania Ahmed',
    notes: 'Barcode verification 100% scannable. Heat-cut edges verified.',
  },
];

// --- STORE ISSUE VOUCHER (SIV) ISSUE REGISTRY ---
export const INITIAL_ISSUE_REGISTRY: IssueRecord[] = [
  {
    id: 'siv-01',
    sivNumber: 'SIV-2026-0422',
    date: '2026-09-20',
    itemId: 'inv-101',
    sku: 'FAB-CTN-180-WHT',
    category: 'FABRIC',
    itemName: '100% Combed Cotton Single Jersey (180 GSM)',
    issuedTo: 'CUTTING_FLOOR',
    departmentDetail: 'Cutting Spreading Table 03',
    poNumber: 'PO-HM-99201',
    styleNumber: 'STY-HM-2026-01',
    requisitionNumber: 'REQ-CUT-2026-088',
    issuedQty: 1200,
    unit: 'Meters',
    issuedBy: 'Rafiqul Islam (Store Head)',
    receivedByFloor: 'Kamal Hossain (Cutting Master)',
    purpose: 'Spreading lay #04 - Tee Front & Back panels',
    notes: 'Delivered with shade lot segregation tag #04A.',
  },
  {
    id: 'siv-02',
    sivNumber: 'SIV-2026-0421',
    date: '2026-09-20',
    itemId: 'inv-201',
    sku: 'TRD-COATS-120-WHT',
    category: 'SEWING_THREAD',
    itemName: 'Coats Epic 120 Polyester Thread',
    issuedTo: 'SEWING_LINE',
    departmentDetail: 'Sewing Line 03 & Line 04',
    poNumber: 'PO-HM-99201',
    styleNumber: 'STY-HM-2026-01',
    requisitionNumber: 'REQ-SEW-1042',
    issuedQty: 80,
    unit: 'Cones',
    issuedBy: 'Rafiqul Islam',
    receivedByFloor: 'Nasreen Begum (Line 03 Supervisor)',
    purpose: 'Overlock 4-thread and twin-needle neck rib attachment',
  },
  {
    id: 'siv-03',
    sivNumber: 'SIV-2026-0420',
    date: '2026-09-19',
    itemId: 'inv-401',
    sku: 'ZIP-YKK-M5-IND',
    category: 'ZIPPERS',
    itemName: 'YKK #5 Closed-End Metal Zipper 7"',
    issuedTo: 'SEWING_LINE',
    departmentDetail: 'Sewing Line 07',
    poNumber: 'PO-ZR-4882',
    styleNumber: 'STY-ZR-4882-09',
    requisitionNumber: 'REQ-SEW-1039',
    issuedQty: 2500,
    unit: 'Pcs',
    issuedBy: 'Tania Ahmed',
    receivedByFloor: 'Abdul Latif (Line 07 Supervisor)',
    purpose: 'Fly zipper insertion for Denim 5-pocket pants',
  },
  {
    id: 'siv-04',
    sivNumber: 'SIV-2026-0419',
    date: '2026-09-18',
    itemId: 'inv-501',
    sku: 'INT-KUF-W75-GRY',
    category: 'INTERLINING_ELASTIC',
    itemName: 'Kufner 75 GSM Woven Fusible Interlining',
    issuedTo: 'CUTTING_FLOOR',
    departmentDetail: 'Fusing Machine Section 02',
    poNumber: 'PO-TH-1190',
    styleNumber: 'STY-TH-1190-02',
    requisitionNumber: 'REQ-FUS-0512',
    issuedQty: 650,
    unit: 'Meters',
    issuedBy: 'Rafiqul Islam',
    receivedByFloor: 'Rezaul Karim (Fusing Operator)',
    purpose: 'Collar and cuff fusing for Twill Chino shirts',
  },
  {
    id: 'siv-05',
    sivNumber: 'SIV-2026-0418',
    date: '2026-09-17',
    itemId: 'inv-602',
    sku: 'PKG-PLY-SLF-M',
    category: 'LABELS_PACKAGING',
    itemName: 'Self-Adhesive LDPE Polybag (M)',
    issuedTo: 'FINISHING_DEPT',
    departmentDetail: 'Finishing Packing Table 01',
    poNumber: 'PO-HM-99201',
    styleNumber: 'STY-HM-2026-01',
    requisitionNumber: 'REQ-PKG-089',
    issuedQty: 5000,
    unit: 'Pcs',
    issuedBy: 'Rafiqul Islam',
    receivedByFloor: 'Shahidul Islam (Packing In-Charge)',
    purpose: 'Individual garment folding and polybag packing',
  },
];

export const INITIAL_INSPECTIONS: InspectionRecord[] = [
  {
    id: 'insp-001',
    inspectionCode: 'QMS-2026-0891',
    inspectionType: 'FINAL',
    orderNumber: 'PO-ZARA-4482',
    styleNumber: 'STY-ZR-4882-09',
    styleDescription: 'Slim Fit Denim Jeans 5-Pocket',
    lotNumber: 'LOT-TX-9042D',
    stage: 'FINISHING_PACKING',
    orderQuantity: 12000,
    lotQuantity: 12000,
    cartonCount: 480,
    packedPercent: 100,
    aqlLevel: 'AQL 2.5 General Inspection Level II',
    sampleSize: 315,
    passCount: 309,
    defectCount: 6,
    majorDefects: 1,
    minorDefects: 5,
    criticalDefects: 0,
    status: 'PASSED',
    inspectorId: 'usr_qa',
    inspectorName: 'Tania Ahmed',
    buyer: 'Inditex (Zara)',
    factoryUnit: 'Unit 01 (Dhaka Complex)',
    shift: 'General Shift',
    remarks: 'Pre-shipment FRI audit completed. Carton drop test (10 drops) passed without internal packaging breach. 100% metal detection passed (Fe 1.0mm, Non-Fe 1.2mm, SS 1.5mm).',
    correctiveAction: 'Slight slub irregularity noted on 4 garments, within acceptable buyer tolerance.',
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    defects: [
      { id: 'd-1', defectType: 'Minor Slub Weft Irregularity', severity: 'MINOR', count: 4, location: 'Front Left Thigh' },
      { id: 'd-2', defectType: 'Slight Uneven Hem Fold', severity: 'MAJOR', count: 1, location: 'Bottom Hem Cuff' },
      { id: 'd-2b', defectType: 'Loose Thread Ends', severity: 'MINOR', count: 1, location: 'Back Pocket Stitch' }
    ],
    measurements: [
      { id: 'm-1', point: 'Waist Circumference', spec: 32.0, actual: 32.1, tol: '±0.5"', result: 'PASS' },
      { id: 'm-2', point: 'Inseam Length', spec: 30.0, actual: 30.0, tol: '±0.5"', result: 'PASS' },
      { id: 'm-3', point: 'Front Rise', spec: 10.5, actual: 10.6, tol: '±0.25"', result: 'PASS' },
      { id: 'm-4', point: 'Thigh Width (1" below crotch)', spec: 23.0, actual: 23.2, tol: '±0.5"', result: 'PASS' },
      { id: 'm-5', point: 'Leg Opening', spec: 14.0, actual: 13.9, tol: '±0.25"', result: 'PASS' },
    ],
    checkpoints: [
      { id: 'c-1', category: 'Workmanship', checkpoint: 'Seam alignment & stitch tension', status: 'PASS' },
      { id: 'c-2', category: 'Packaging', checkpoint: 'Master carton shipping marks & barcodes', status: 'PASS' },
      { id: 'c-3', category: 'Safety', checkpoint: '100% Needle / Metal Detection signoff', status: 'PASS' },
      { id: 'c-4', category: 'Carton Test', checkpoint: 'ISTA 1A Carton Drop Test (10 drops)', status: 'PASS' },
    ]
  },
  {
    id: 'insp-002',
    inspectionCode: 'QMS-2026-0892',
    inspectionType: 'INLINE',
    orderNumber: 'PO-HM-99201',
    styleNumber: 'STY-HM-2026-01',
    styleDescription: 'Organic Combed Cotton Crew T-Shirt',
    lotNumber: 'LOT-TX-9041A',
    stage: 'CUTTING_INSPECTION',
    orderQuantity: 25000,
    lotQuantity: 8000,
    sewingLine: 'Cutting Section Table 03',
    factoryUnit: 'Unit 02 (Gazipur Facility)',
    shift: 'Morning Shift A',
    sampleSize: 200,
    passCount: 198,
    defectCount: 2,
    majorDefects: 0,
    minorDefects: 2,
    criticalDefects: 0,
    status: 'PASSED',
    inspectorId: 'usr_inspector',
    inspectorName: 'Rafiqul Islam',
    buyer: 'H&M Global',
    remarks: 'Fabric spreading lay tension and notch depths audited across front, back, and sleeve panels. SPI calibration verified at 12 stitches/inch.',
    createdAt: new Date(Date.now() - 1000 * 60 * 115).toISOString(),
    defects: [
      { id: 'd-3', defectType: 'Notch Depth Variation (+1mm)', severity: 'MINOR', count: 2, location: 'Pattern Front Chest' }
    ],
    measurements: [
      { id: 'm-6', point: 'Chest Width (1" below armhole)', spec: 21.0, actual: 21.0, tol: '±0.5"', result: 'PASS' },
      { id: 'm-7', point: 'Body Length (HPS to hem)', spec: 28.5, actual: 28.6, tol: '±0.5"', result: 'PASS' },
      { id: 'm-8', point: 'Sleeve Length', spec: 8.5, actual: 8.4, tol: '±0.25"', result: 'PASS' },
    ],
    checkpoints: [
      { id: 'c-5', category: 'Cutting', checkpoint: 'CAD marker alignment and ply height', status: 'PASS' },
      { id: 'c-6', category: 'Shade', checkpoint: 'Shade lot segregation across bundles', status: 'PASS' },
    ]
  },
  {
    id: 'insp-003',
    inspectionCode: 'QMS-2026-0893',
    inspectionType: 'INLINE',
    orderNumber: 'PO-NK-7741',
    styleNumber: 'STY-NK-7741-05',
    styleDescription: 'Dri-FIT Athletic Training Hoodie',
    lotNumber: 'LOT-TX-9044C',
    stage: 'SEWING_IN_LINE',
    orderQuantity: 18000,
    lotQuantity: 4500,
    sewingLine: 'Sewing Line 04 (Performance)',
    factoryUnit: 'Unit 01 (Dhaka Complex)',
    shift: 'Morning Shift A',
    sampleSize: 125,
    passCount: 119,
    defectCount: 6,
    majorDefects: 2,
    minorDefects: 4,
    criticalDefects: 0,
    status: 'CONDITIONAL_PASS',
    inspectorId: 'usr_qa',
    inspectorName: 'Tania Ahmed',
    buyer: 'Nike Apparel',
    remarks: 'Line 04 sewing audit. Skip stitches identified on 4-thread overlock machine #14. Operator advised to replace needle #11 and re-tune looper tension.',
    correctiveAction: 'Mechanic reset needle gauge. Supervisor to re-check next 50 pcs in-line.',
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    defects: [
      { id: 'd-4', defectType: 'Skip Stitch Overlock', severity: 'MAJOR', count: 2, location: 'Side Seam Line 02' },
      { id: 'd-5', defectType: 'Loose Thread Ends', severity: 'MINOR', count: 4, location: 'Cuff Hemming' }
    ],
    measurements: [
      { id: 'm-9', point: 'Chest Width', spec: 22.5, actual: 22.4, tol: '±0.5"', result: 'PASS' },
      { id: 'm-10', point: 'Hood Height', spec: 14.0, actual: 13.9, tol: '±0.25"', result: 'PASS' },
    ],
    checkpoints: [
      { id: 'c-7', category: 'Sewing', checkpoint: 'Seam strength and SPI consistency (10-12 SPI)', status: 'FAIL', notes: 'Machine #14 skipped stitches' },
      { id: 'c-8', category: 'Needle Control', checkpoint: 'Broken needle log and replacement slip', status: 'PASS' },
    ]
  },
  {
    id: 'insp-004',
    inspectionCode: 'QMS-2026-0894',
    inspectionType: 'PRE_FINAL',
    orderNumber: 'PO-GAP-9902',
    styleNumber: 'STY-GAP-9902-01',
    styleDescription: 'Oxford Button-Down Long Sleeve Shirt',
    lotNumber: 'LOT-TX-9047D',
    stage: 'FINISHING_PACKING',
    orderQuantity: 15000,
    lotQuantity: 10500,
    cartonCount: 350,
    packedPercent: 70,
    aqlLevel: 'AQL 2.5 Normal Inspection Level II',
    sampleSize: 315,
    passCount: 284,
    defectCount: 31,
    majorDefects: 18,
    minorDefects: 12,
    criticalDefects: 1,
    status: 'REJECTED',
    inspectorId: 'usr_qa',
    inspectorName: 'Tania Ahmed',
    buyer: 'Gap Inc.',
    factoryUnit: 'Unit 02 (Gazipur Facility)',
    shift: 'General Shift',
    remarks: 'Pre-final inspection conducted at 70% packed. Lot REJECTED due to severe weft shade variations across 3 rolls and 1 critical oil smear near placket button #2.',
    correctiveAction: '100% finishing line screening mandatory. Re-inspection required once rejected cartons are replaced and re-packed.',
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    defects: [
      { id: 'd-6', defectType: 'Critical Oil Smear Near Placket', severity: 'CRITICAL', count: 1, location: 'Front Center Placket' },
      { id: 'd-7', defectType: 'Severe Color Banding Shade Delta 1.9', severity: 'MAJOR', count: 18, location: 'Front Body Panels' },
      { id: 'd-7b', defectType: 'Loose Thread Trimming', severity: 'MINOR', count: 12, location: 'Cuff & Collar Points' }
    ],
    measurements: [
      { id: 'm-11', point: 'Collar Band Length', spec: 16.5, actual: 16.4, tol: '±0.25"', result: 'PASS' },
      { id: 'm-12', point: 'Sleeve Length from Center Back', spec: 34.5, actual: 34.0, tol: '±0.5"', result: 'FAIL' },
      { id: 'm-13', point: 'Chest Width', spec: 22.0, actual: 22.1, tol: '±0.5"', result: 'PASS' },
    ],
    checkpoints: [
      { id: 'c-9', category: 'Pre-Final Packing', checkpoint: 'Carton assortment by size & color ratio', status: 'PASS' },
      { id: 'c-10', category: 'Cleanliness', checkpoint: 'Oil spot and stain free check', status: 'FAIL', notes: 'Oil smear found on placket' },
    ]
  },
  {
    id: 'insp-005',
    inspectionCode: 'QMS-2026-0895',
    inspectionType: 'PRE_FINAL',
    orderNumber: 'PO-UQ-3310',
    styleNumber: 'STY-UQ-3310-04',
    styleDescription: 'Supima Cotton Crew Neck Tee',
    lotNumber: 'LOT-TX-9045E',
    stage: 'FINISHING_PACKING',
    orderQuantity: 20000,
    lotQuantity: 14000,
    cartonCount: 420,
    packedPercent: 70,
    aqlLevel: 'AQL 1.5 Strict Level II',
    sampleSize: 80,
    passCount: 78,
    defectCount: 2,
    majorDefects: 0,
    minorDefects: 2,
    criticalDefects: 0,
    status: 'PASSED',
    inspectorId: 'usr_inspector',
    inspectorName: 'Rafiqul Islam',
    buyer: 'Fast Retailing (Uniqlo)',
    factoryUnit: 'Unit 01 (Dhaka Complex)',
    shift: 'Morning Shift A',
    remarks: 'Pre-final inspection passed with minor label alignment notes. Assortment ratio confirmed: S:2, M:4, L:4, XL:2 per carton. Polybag ventilation holes verified.',
    createdAt: new Date(Date.now() - 1000 * 60 * 310).toISOString(),
    defects: [
      { id: 'd-8', defectType: 'Slightly Off-Center Heat Seal Label', severity: 'MINOR', count: 2, location: 'Inner Back Neck' }
    ],
    measurements: [
      { id: 'm-14', point: 'Chest Width', spec: 20.5, actual: 20.5, tol: '±0.375"', result: 'PASS' },
      { id: 'm-15', point: 'Body Length', spec: 27.5, actual: 27.6, tol: '±0.5"', result: 'PASS' },
    ],
    checkpoints: [
      { id: 'c-11', category: 'Folding & Packaging', checkpoint: 'Folding board dimensions consistency', status: 'PASS' },
      { id: 'c-12', category: 'Barcode', checkpoint: 'UPC sticker readability on polybags', status: 'PASS' },
    ]
  },
  {
    id: 'insp-006',
    inspectionCode: 'QMS-2026-0896',
    inspectionType: 'FINAL',
    orderNumber: 'PO-TH-1190',
    styleNumber: 'STY-TH-1190-02',
    styleDescription: 'Classic Twill Casual Chino Pant',
    lotNumber: 'LOT-TX-9043B',
    stage: 'FINISHING_PACKING',
    orderQuantity: 10000,
    lotQuantity: 10000,
    cartonCount: 380,
    packedPercent: 100,
    aqlLevel: 'AQL 2.5 General Level II',
    sampleSize: 125,
    passCount: 124,
    defectCount: 1,
    majorDefects: 0,
    minorDefects: 1,
    criticalDefects: 0,
    status: 'PASSED',
    inspectorId: 'usr_admin',
    inspectorName: 'Kazi Farhan',
    buyer: 'PVH (Tommy Hilfiger)',
    factoryUnit: 'Unit 01 (Dhaka Complex)',
    shift: 'General Shift',
    remarks: 'Final Random Inspection PASSED. Ready for factory gate pass & container stuffing. Full carton seal integrity and pallet wrapping checked.',
    createdAt: new Date(Date.now() - 1000 * 60 * 390).toISOString(),
    defects: [
      { id: 'd-9', defectType: 'Polybag Barcode Misaligned', severity: 'MINOR', count: 1, location: 'Carton #14 Inner Polybag' }
    ],
    measurements: [
      { id: 'm-16', point: 'Waist Extended', spec: 34.0, actual: 34.0, tol: '±0.5"', result: 'PASS' },
      { id: 'm-17', point: 'Inseam', spec: 32.0, actual: 32.2, tol: '±0.5"', result: 'PASS' },
    ],
    checkpoints: [
      { id: 'c-13', category: 'Final Audit', checkpoint: 'AQL 2.5 random sampling criteria met', status: 'PASS' },
      { id: 'c-14', category: 'Shipping Marks', checkpoint: 'Destination port, PO number, Carton # on box', status: 'PASS' },
    ]
  }
];

export const INITIAL_PRODUCTION_ORDERS: ProductionOrder[] = [
  {
    id: 'po-201',
    orderNumber: 'PO-IND-2026-88',
    recordDate: '2026-09-21',
    shift: 'Shift A (Morning 08:00 - 16:30)',
    buyer: 'Inditex (Zara)',
    styleName: 'Slim Tapered Slub Denim Trouser',
    styleNumber: 'STY-DN-502',
    unit: 'Unit 01 (Dhaka Complex)',
    section: 'Sewing Line 04 (Heavy Bottoms)',
    targetQuantity: 15000,
    completedQuantity: 11450,
    totalDefects: 132,
    defectRate: 1.15,
    dhuRate: 1.15,
    rftRate: 98.2,
    efficiencyPercent: 84.5,
    rejectQuantity: 28,
    sewingLine: 'Line 04 (Heavy Bottoms)',
    lineId: 'Line 04',
    status: 'RUNNING',
    dueDate: '2026-10-15',
    operatorCount: 48,
    supervisorName: 'Kabir Hossain (Senior Line Sup)',
    qualityInspector: 'Md. Rafiqul Islam (Senior QC Auditor)',
    remarks: 'Pre-washed denim fabric. Inline needle breakage check verified.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    hourlyReports: [
      { id: 'hr-1', hourSlot: '08:00 - 09:00', targetQty: 140, checkedQty: 135, passedQty: 133, defectQty: 2, defectRate: 1.48, topDefect: 'Skip Stitch', operatorId: 'Station 04', remarks: 'Machine tension tuned' },
      { id: 'hr-2', hourSlot: '09:00 - 10:00', targetQty: 150, checkedQty: 148, passedQty: 146, defectQty: 2, defectRate: 1.35, topDefect: 'Open Seam', operatorId: 'Station 11', remarks: 'Normal pacing' },
      { id: 'hr-3', hourSlot: '10:00 - 11:00', targetQty: 150, checkedQty: 152, passedQty: 151, defectQty: 1, defectRate: 0.66, topDefect: 'Broken Stitch', operatorId: 'Station 08', remarks: 'High speed maintained' },
      { id: 'hr-4', hourSlot: '11:00 - 12:00', targetQty: 150, checkedQty: 149, passedQty: 147, defectQty: 2, defectRate: 1.34, topDefect: 'Puckering', operatorId: 'Station 16', remarks: 'Differential feed checked' },
      { id: 'hr-5', hourSlot: '12:00 - 13:00', targetQty: 150, checkedQty: 146, passedQty: 144, defectQty: 2, defectRate: 1.37, topDefect: 'Needle Mark', operatorId: 'Station 05', remarks: 'Needle replaced' },
      { id: 'hr-6', hourSlot: '14:00 - 15:00', targetQty: 150, checkedQty: 150, passedQty: 149, defectQty: 1, defectRate: 0.67, topDefect: 'Oil Stain', operatorId: 'Station 22', remarks: 'Spot cleaner applied' },
      { id: 'hr-7', hourSlot: '15:00 - 16:00', targetQty: 150, checkedQty: 145, passedQty: 143, defectQty: 2, defectRate: 1.38, topDefect: 'Uneven Hem', operatorId: 'Station 19', remarks: 'Guide gauge aligned' },
      { id: 'hr-8', hourSlot: '16:00 - 17:00', targetQty: 140, checkedQty: 138, passedQty: 136, defectQty: 2, defectRate: 1.45, topDefect: 'Skip Stitch', operatorId: 'Station 07', remarks: 'End of standard shift' },
    ],
  },
  {
    id: 'po-202',
    orderNumber: 'PO-HM-2026-14',
    recordDate: '2026-09-21',
    shift: 'Shift A (Morning 08:00 - 16:30)',
    buyer: 'H&M Global',
    styleName: 'Essential Organic Tee Crew Neck',
    styleNumber: 'STY-HM-2026-01',
    unit: 'Unit 01 (Dhaka Complex)',
    section: 'Sewing Line 01 (Knit Tops)',
    targetQuantity: 45000,
    completedQuantity: 38900,
    totalDefects: 330,
    defectRate: 0.85,
    dhuRate: 0.85,
    rftRate: 98.9,
    efficiencyPercent: 87.2,
    rejectQuantity: 65,
    sewingLine: 'Line 01 & 02 (Knit Tops)',
    lineId: 'Line 01',
    status: 'RUNNING',
    dueDate: '2026-10-02',
    operatorCount: 52,
    supervisorName: 'Nazmul Huda (Knit In-Charge)',
    qualityInspector: 'Farhana Yasmin (Floor QC Specialist)',
    remarks: 'High-speed flatlock rib collar attachment running at 105% target pace.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    hourlyReports: [
      { id: 'hr-201', hourSlot: '08:00 - 09:00', targetQty: 480, checkedQty: 475, passedQty: 472, defectQty: 3, defectRate: 0.63, topDefect: 'Raw Edge', operatorId: 'Line 01-A', remarks: 'Smooth start' },
      { id: 'hr-202', hourSlot: '09:00 - 10:00', targetQty: 500, checkedQty: 510, passedQty: 506, defectQty: 4, defectRate: 0.78, topDefect: 'Skip Stitch', operatorId: 'Line 01-B', remarks: 'Target exceeded' },
      { id: 'hr-203', hourSlot: '10:00 - 11:00', targetQty: 500, checkedQty: 495, passedQty: 491, defectQty: 4, defectRate: 0.81, topDefect: 'Puckering', operatorId: 'Line 01-C', remarks: 'Tension adjusted' },
      { id: 'hr-204', hourSlot: '11:00 - 12:00', targetQty: 500, checkedQty: 505, passedQty: 501, defectQty: 4, defectRate: 0.79, topDefect: 'Oil Stain', operatorId: 'Line 01-D', remarks: 'Cleaners inspected' },
      { id: 'hr-205', hourSlot: '12:00 - 13:00', targetQty: 500, checkedQty: 490, passedQty: 487, defectQty: 3, defectRate: 0.61, topDefect: 'Open Seam', operatorId: 'Line 01-E', remarks: 'Good quality' },
      { id: 'hr-206', hourSlot: '14:00 - 15:00', targetQty: 500, checkedQty: 502, passedQty: 498, defectQty: 4, defectRate: 0.80, topDefect: 'Skip Stitch', operatorId: 'Line 01-F', remarks: 'Inline QC active' },
      { id: 'hr-207', hourSlot: '15:00 - 16:00', targetQty: 500, checkedQty: 498, passedQty: 494, defectQty: 4, defectRate: 0.80, topDefect: 'Broken Stitch', operatorId: 'Line 01-G', remarks: 'Stable run' },
      { id: 'hr-208', hourSlot: '16:00 - 17:00', targetQty: 480, checkedQty: 482, passedQty: 479, defectQty: 3, defectRate: 0.62, topDefect: 'Uneven Hem', operatorId: 'Line 01-H', remarks: 'Shift target achieved' },
    ],
  },
  {
    id: 'po-203',
    orderNumber: 'PO-NK-2026-55',
    recordDate: '2026-09-20',
    shift: 'Shift A (Morning 08:00 - 16:30)',
    buyer: 'Nike Apparel',
    styleName: 'French Terry Club Pullover Hoodie',
    styleNumber: 'STY-NK-7741-05',
    unit: 'Unit 02 (Chittagong SEZ)',
    section: 'Sewing Line 06 (Fleece Assembly)',
    targetQuantity: 20000,
    completedQuantity: 14200,
    totalDefects: 202,
    defectRate: 1.42,
    dhuRate: 1.42,
    rftRate: 97.5,
    efficiencyPercent: 81.0,
    rejectQuantity: 42,
    sewingLine: 'Line 06 (Fleece Assembly)',
    lineId: 'Line 06',
    status: 'RUNNING',
    dueDate: '2026-10-25',
    operatorCount: 46,
    supervisorName: 'Shahidul Islam (Assembly Sup)',
    qualityInspector: 'Nasrin Akter (Inline Quality Inspector)',
    remarks: 'Kangaroo pocket alignment jig in use. Critical metal detection 100% passed.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: 'po-204',
    orderNumber: 'PO-TH-2026-09',
    recordDate: '2026-09-19',
    shift: 'Shift A (Morning 08:00 - 16:30)',
    buyer: 'Tommy Hilfiger',
    styleName: 'Classic Fit Stretch Chino Pant',
    styleNumber: 'STY-TH-1190-02',
    unit: 'Unit 01 (Dhaka Complex)',
    section: 'Sewing Line 03 (Woven Bottoms)',
    targetQuantity: 12000,
    completedQuantity: 12000,
    totalDefects: 110,
    defectRate: 0.92,
    dhuRate: 0.92,
    rftRate: 98.8,
    efficiencyPercent: 88.5,
    rejectQuantity: 18,
    sewingLine: 'Line 03 (Woven Bottoms)',
    lineId: 'Line 03',
    status: 'COMPLETED',
    dueDate: '2026-09-20',
    operatorCount: 40,
    supervisorName: 'Farid Ahmed (Master Tailor)',
    qualityInspector: 'Tariqul Anam (QA In-Charge)',
    remarks: 'All 12,000 pcs inspected and transferred to final finishing carton warehouse.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
  },
  {
    id: 'po-205',
    orderNumber: 'PO-UQ-2026-31',
    buyer: 'Uniqlo (Fast Retailing)',
    styleName: 'Ultra Stretch Rib Long Sleeve Tee',
    styleNumber: 'STY-UQ-3310-04',
    unit: 'Unit 03 (Ashulia Modern Plant)',
    section: 'Sewing Line 05 (Precision Knit)',
    targetQuantity: 28000,
    completedQuantity: 19400,
    totalDefects: 144,
    defectRate: 0.74,
    dhuRate: 0.74,
    rftRate: 99.1,
    efficiencyPercent: 85.0,
    rejectQuantity: 32,
    sewingLine: 'Line 05 (Precision Knit)',
    lineId: 'Line 05',
    status: 'RUNNING',
    dueDate: '2026-10-18',
    operatorCount: 50,
    supervisorName: 'Mahmudur Rahman (QA Supervisor)',
    remarks: 'Micro-stitch tolerance within +/- 0.5mm. Zero shade deviation observed.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: 'po-206',
    orderNumber: 'PO-GAP-2026-19',
    buyer: 'Gap Inc.',
    styleName: 'Vintage Wash Denim Cargo Jogger',
    styleNumber: 'STY-GAP-9902-01',
    unit: 'Unit 02 (Chittagong SEZ)',
    section: 'Finishing & Packing Section 01',
    targetQuantity: 18000,
    completedQuantity: 9200,
    totalDefects: 115,
    defectRate: 1.25,
    dhuRate: 1.25,
    rftRate: 97.8,
    efficiencyPercent: 82.5,
    rejectQuantity: 24,
    sewingLine: 'Line 07 (Cargo & Utility)',
    lineId: 'Line 07',
    status: 'RUNNING',
    dueDate: '2026-10-29',
    operatorCount: 44,
    supervisorName: 'Jashim Uddin (Finishing Head)',
    remarks: 'Enzyme wash recipe approved by Gap country quality office.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-01',
    action: 'GRADE_CHANGE',
    entity: 'InventoryItem',
    entityId: 'inv-107',
    performedBy: 'Tania Ahmed',
    userRole: 'QA_MANAGER',
    timestamp: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    details: 'Changed status to REJECTED due to Delta-E shade variation over tolerance threshold 1.5.'
  },
  {
    id: 'log-02',
    action: 'INSPECTION_SIGN_OFF',
    entity: 'InspectionRecord',
    entityId: 'insp-001',
    performedBy: 'Tania Ahmed',
    userRole: 'QA_MANAGER',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    details: 'Signed off Fabric Inward AQL 2.5 sample acceptance for Zara batch.'
  },
  {
    id: 'log-03',
    action: 'STOCK_ADJUSTMENT',
    entity: 'InventoryItem',
    entityId: 'inv-104',
    performedBy: 'Rafiqul Islam',
    userRole: 'WAREHOUSE_INSPECTOR',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    details: 'Verified meter count on digital roll unwinder (+120m adjustment).'
  }
];
