import {
  StyleOperationBulletin,
  ProductionPlanSchedule,
  TimeMotionStudy,
} from '@/lib/types/planning-ie';

export const INITIAL_OPERATION_BULLETINS: StyleOperationBulletin[] = [
  {
    id: 'ob-1',
    styleNumber: 'STY-TS-2026',
    styleDescription: 'Men Heavyweight Cotton Crewneck Tee',
    buyerName: 'H&M Hennes & Mauritz',
    garmentType: 'T-Shirt',
    totalSmv: 11.2,
    targetLineOperators: 28,
    linePitchTimeSec: 24.0,
    targetEfficiency: 82,
    plannedDailyOutput: 1800,
    balancingEfficiency: 89.2,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
    operations: [
      {
        id: 'op-1',
        seqNumber: 1,
        operationName: 'Shoulder Join (with Mobilon Tape)',
        section: 'PREPARATION',
        machineType: '4-Thread Overlock',
        machineCode: '4T-OVL-01',
        smv: 0.65,
        theoreticalOperators: 1.6,
        allocatedOperators: 2,
        cycleTimeSec: 22.0,
        pitchTimeSec: 24.0,
        isBottleneck: false,
        remarks: 'Ensure clear mobilon elastic tension',
      },
      {
        id: 'op-2',
        seqNumber: 2,
        operationName: 'Rib Collar Prepare & Loop Join',
        section: 'PREPARATION',
        machineType: 'Single Needle Lockstitch (SNLS)',
        machineCode: 'SNLS-02',
        smv: 0.55,
        theoreticalOperators: 1.4,
        allocatedOperators: 1,
        cycleTimeSec: 26.5,
        pitchTimeSec: 24.0,
        isBottleneck: true,
        remarks: 'Operator needs helper for trimming notches',
      },
      {
        id: 'op-3',
        seqNumber: 3,
        operationName: 'Attach Rib Neck to Body',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock (Differential)',
        machineCode: '4T-OVL-02',
        smv: 1.15,
        theoreticalOperators: 2.9,
        allocatedOperators: 3,
        cycleTimeSec: 23.5,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
      {
        id: 'op-4',
        seqNumber: 4,
        operationName: 'Neck Topstitch / Binding',
        section: 'ASSEMBLY',
        machineType: 'Flatlock 2-Needle 4-Thread',
        machineCode: 'FL-01',
        smv: 0.90,
        theoreticalOperators: 2.2,
        allocatedOperators: 2,
        cycleTimeSec: 25.0,
        pitchTimeSec: 24.0,
        isBottleneck: true,
      },
      {
        id: 'op-5',
        seqNumber: 5,
        operationName: 'Back Neck Tape Attach & Folder',
        section: 'ASSEMBLY',
        machineType: 'Single Needle Chainstitch',
        machineCode: 'SNCS-01',
        smv: 0.80,
        theoreticalOperators: 2.0,
        allocatedOperators: 2,
        cycleTimeSec: 23.0,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
      {
        id: 'op-6',
        seqNumber: 6,
        operationName: 'Sleeve Open Hem Fold & Stitch',
        section: 'PREPARATION',
        machineType: 'Flatlock Bottom Hem',
        machineCode: 'FL-02',
        smv: 1.10,
        theoreticalOperators: 2.7,
        allocatedOperators: 3,
        cycleTimeSec: 22.5,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
      {
        id: 'op-7',
        seqNumber: 7,
        operationName: 'Sleeve Attach to Armhole (Both sides)',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock',
        machineCode: '4T-OVL-03',
        smv: 1.45,
        theoreticalOperators: 3.6,
        allocatedOperators: 4,
        cycleTimeSec: 22.0,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
      {
        id: 'op-8',
        seqNumber: 8,
        operationName: 'Side Seam Close with Care Label Insert',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock',
        machineCode: '4T-OVL-04',
        smv: 1.55,
        theoreticalOperators: 3.8,
        allocatedOperators: 4,
        cycleTimeSec: 23.8,
        pitchTimeSec: 24.0,
        isBottleneck: false,
        remarks: 'Care label inserted at 10cm from bottom hem',
      },
      {
        id: 'op-9',
        seqNumber: 9,
        operationName: 'Bottom Hem Fold & Flatlock Stitch',
        section: 'ASSEMBLY',
        machineType: 'Flatlock 3-Needle Cylinder Bed',
        machineCode: 'FL-03',
        smv: 1.30,
        theoreticalOperators: 3.2,
        allocatedOperators: 3,
        cycleTimeSec: 25.2,
        pitchTimeSec: 24.0,
        isBottleneck: true,
      },
      {
        id: 'op-10',
        seqNumber: 10,
        operationName: 'Bartack at Neck Joint & Side Seam Ends',
        section: 'FINISHING',
        machineType: 'Electronic Bartack',
        machineCode: 'BT-01',
        smv: 0.60,
        theoreticalOperators: 1.5,
        allocatedOperators: 2,
        cycleTimeSec: 18.0,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
      {
        id: 'op-11',
        seqNumber: 11,
        operationName: 'Thread Trimming & In-Line Inspection',
        section: 'FINISHING',
        machineType: 'Manual Trimming & QC Table',
        machineCode: 'MANUAL',
        smv: 1.15,
        theoreticalOperators: 2.9,
        allocatedOperators: 3,
        cycleTimeSec: 23.0,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
    ],
  },
  {
    id: 'ob-2',
    styleNumber: 'STY-DN-502',
    styleDescription: 'Slim Fit Washed Indigo Denim Jeans 12oz',
    buyerName: 'Inditex / Zara',
    garmentType: 'Denim Jeans',
    totalSmv: 22.4,
    targetLineOperators: 48,
    linePitchTimeSec: 28.0,
    targetEfficiency: 80,
    plannedDailyOutput: 950,
    balancingEfficiency: 86.8,
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-22T14:30:00Z',
    operations: [
      {
        id: 'op-201',
        seqNumber: 1,
        operationName: 'Front Pocket Bag Prepare & Serging',
        section: 'PREPARATION',
        machineType: '3-Thread Overlock',
        machineCode: '3T-OVL',
        smv: 1.2,
        theoreticalOperators: 2.1,
        allocatedOperators: 2,
        cycleTimeSec: 27.0,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-202',
        seqNumber: 2,
        operationName: 'Coin Pocket Attach & Rivet Marking',
        section: 'PREPARATION',
        machineType: 'Double Needle Lockstitch (DNLS)',
        machineCode: 'DNLS-01',
        smv: 0.85,
        theoreticalOperators: 1.5,
        allocatedOperators: 2,
        cycleTimeSec: 24.0,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-203',
        seqNumber: 3,
        operationName: 'Back Pocket Hem & Decorative Embroidery',
        section: 'PREPARATION',
        machineType: 'Pattern Sewing Automated CNC',
        machineCode: 'CNC-01',
        smv: 1.4,
        theoreticalOperators: 2.4,
        allocatedOperators: 2,
        cycleTimeSec: 30.5,
        pitchTimeSec: 28.0,
        isBottleneck: true,
      },
      {
        id: 'op-204',
        seqNumber: 4,
        operationName: 'Back Pocket Attach to Back Panel',
        section: 'ASSEMBLY',
        machineType: 'Twin Needle Post Bed with Guide',
        machineCode: 'DNLS-02',
        smv: 2.1,
        theoreticalOperators: 3.6,
        allocatedOperators: 4,
        cycleTimeSec: 27.5,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-205',
        seqNumber: 5,
        operationName: 'Back Yoke Join & Double Topstitch',
        section: 'ASSEMBLY',
        machineType: 'Feed-off-the-Arm Lap Seam',
        machineCode: 'FOA-01',
        smv: 1.6,
        theoreticalOperators: 2.8,
        allocatedOperators: 3,
        cycleTimeSec: 26.0,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-206',
        seqNumber: 6,
        operationName: 'Back Rise Join (Fell Seam)',
        section: 'ASSEMBLY',
        machineType: 'Feed-off-the-Arm 3-Needle',
        machineCode: 'FOA-02',
        smv: 1.5,
        theoreticalOperators: 2.6,
        allocatedOperators: 3,
        cycleTimeSec: 27.0,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-207',
        seqNumber: 7,
        operationName: 'Front Fly Zipper Attach & J-Stitch',
        section: 'ASSEMBLY',
        machineType: 'SNLS with J-Stitch Template',
        machineCode: 'SNLS-04',
        smv: 2.3,
        theoreticalOperators: 4.0,
        allocatedOperators: 4,
        cycleTimeSec: 29.5,
        pitchTimeSec: 28.0,
        isBottleneck: true,
      },
      {
        id: 'op-208',
        seqNumber: 8,
        operationName: 'Inseam Join with Double Lap Seam',
        section: 'ASSEMBLY',
        machineType: 'Feed-off-the-Arm Chainstitch',
        machineCode: 'FOA-03',
        smv: 2.2,
        theoreticalOperators: 3.8,
        allocatedOperators: 4,
        cycleTimeSec: 27.5,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-209',
        seqNumber: 9,
        operationName: 'Outseam Join (Safety 5-Thread Overlock)',
        section: 'ASSEMBLY',
        machineType: '5-Thread Heavy Overlock',
        machineCode: '5T-OVL',
        smv: 1.9,
        theoreticalOperators: 3.3,
        allocatedOperators: 3,
        cycleTimeSec: 31.0,
        pitchTimeSec: 28.0,
        isBottleneck: true,
      },
      {
        id: 'op-210',
        seqNumber: 10,
        operationName: 'Waistband Attach (Kansai Special Multi-Needle)',
        section: 'ASSEMBLY',
        machineType: 'Kansai Special Waistband Machine',
        machineCode: 'KANSAI-01',
        smv: 2.8,
        theoreticalOperators: 4.8,
        allocatedOperators: 5,
        cycleTimeSec: 27.8,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-211',
        seqNumber: 11,
        operationName: 'Belt Loop Attach (5 positions)',
        section: 'ASSEMBLY',
        machineType: 'Automated Belt Loop Setter',
        machineCode: 'BLS-01',
        smv: 1.5,
        theoreticalOperators: 2.6,
        allocatedOperators: 3,
        cycleTimeSec: 25.0,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-212',
        seqNumber: 12,
        operationName: 'Bottom Hemming (Union Special Chainstitch)',
        section: 'ASSEMBLY',
        machineType: 'Union Special Lockstitch / Chainstitch',
        machineCode: 'US-01',
        smv: 1.4,
        theoreticalOperators: 2.4,
        allocatedOperators: 3,
        cycleTimeSec: 24.5,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-213',
        seqNumber: 13,
        operationName: 'Button Hole, Shank Button & Riveting',
        section: 'FINISHING',
        machineType: 'Eyelet Buttonhole & Pneumatic Riveter',
        machineCode: 'EBH-01',
        smv: 1.6,
        theoreticalOperators: 2.8,
        allocatedOperators: 3,
        cycleTimeSec: 26.5,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
    ],
  },
  {
    id: 'ob-3',
    styleNumber: 'STY-PL-889',
    styleDescription: 'Pique Cotton Polo with Flat-Knit Collar',
    buyerName: 'PVH Tommy Hilfiger',
    garmentType: 'Polo Shirt',
    totalSmv: 15.0,
    targetLineOperators: 34,
    linePitchTimeSec: 26.5,
    targetEfficiency: 82,
    plannedDailyOutput: 1400,
    balancingEfficiency: 87.5,
    createdAt: '2026-09-08T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z',
    operations: [
      {
        id: 'op-301',
        seqNumber: 1,
        operationName: 'Placket Fusing & Creasing',
        section: 'PREPARATION',
        machineType: 'Mini Fusing Press',
        machineCode: 'FUSE-01',
        smv: 0.8,
        theoreticalOperators: 1.8,
        allocatedOperators: 2,
        cycleTimeSec: 25.0,
        pitchTimeSec: 26.5,
        isBottleneck: false,
      },
      {
        id: 'op-302',
        seqNumber: 2,
        operationName: 'Box Placket Cut & Make on Front Body',
        section: 'PREPARATION',
        machineType: 'Automated Placket Setting Machine',
        machineCode: 'APS-01',
        smv: 2.4,
        theoreticalOperators: 5.4,
        allocatedOperators: 6,
        cycleTimeSec: 25.5,
        pitchTimeSec: 26.5,
        isBottleneck: false,
      },
      {
        id: 'op-303',
        seqNumber: 3,
        operationName: 'Collar Rib Attach & Overlock',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock',
        machineCode: '4T-OVL',
        smv: 1.6,
        theoreticalOperators: 3.6,
        allocatedOperators: 4,
        cycleTimeSec: 26.0,
        pitchTimeSec: 26.5,
        isBottleneck: false,
      },
      {
        id: 'op-304',
        seqNumber: 4,
        operationName: 'Collar Band Topstitch with Twill Tape',
        section: 'ASSEMBLY',
        machineType: 'SNLS with Tape Guide',
        machineCode: 'SNLS',
        smv: 1.5,
        theoreticalOperators: 3.4,
        allocatedOperators: 4,
        cycleTimeSec: 25.0,
        pitchTimeSec: 26.5,
        isBottleneck: false,
      },
      {
        id: 'op-305',
        seqNumber: 5,
        operationName: 'Side Vent Make & Herringbone Reinforcement',
        section: 'ASSEMBLY',
        machineType: 'SNLS',
        machineCode: 'SNLS',
        smv: 1.8,
        theoreticalOperators: 4.1,
        allocatedOperators: 4,
        cycleTimeSec: 29.0,
        pitchTimeSec: 26.5,
        isBottleneck: true,
      },
    ],
  },
];

export const INITIAL_PRODUCTION_SCHEDULES: ProductionPlanSchedule[] = [
  {
    id: 'mps-1',
    lineId: 'Line 03',
    lineName: 'Sewing Line 03 (T-Shirt & Knit)',
    orderNumber: 'PO-HM-99201',
    buyerName: 'H&M Hennes & Mauritz',
    styleNumber: 'STY-TS-2026',
    styleDescription: 'Men Heavyweight Cotton Crewneck Tee',
    orderQuantity: 45000,
    smv: 11.2,
    allocatedOperators: 28,
    plannedDailyTarget: 1800,
    startDate: '2026-09-19',
    endDate: '2026-10-14',
    daysRequired: 25,
    status: 'RUNNING',
    learningCurveRampUp: {
      day1Percent: 45,
      day2Percent: 68,
      day3Percent: 85,
      day4PlusPercent: 100,
    },
    notes: 'Running at 78% efficiency; target reached on Day 4.',
  },
  {
    id: 'mps-2',
    lineId: 'Line 04',
    lineName: 'Sewing Line 04 (Heavy Denim)',
    orderNumber: 'PO-ZARA-4482',
    buyerName: 'Inditex / Zara',
    styleNumber: 'STY-DN-502',
    styleDescription: 'Slim Fit Washed Indigo Denim Jeans 12oz',
    orderQuantity: 28000,
    smv: 22.4,
    allocatedOperators: 48,
    plannedDailyTarget: 950,
    startDate: '2026-09-29',
    endDate: '2026-10-28',
    daysRequired: 29,
    status: 'SCHEDULED',
    learningCurveRampUp: {
      day1Percent: 40,
      day2Percent: 60,
      day3Percent: 80,
      day4PlusPercent: 100,
    },
    notes: 'Tooling setup complete; folder guides tested.',
  },
  {
    id: 'mps-3',
    lineId: 'Line 06',
    lineName: 'Sewing Line 06 (Polo Specialist)',
    orderNumber: 'PO-PVH-7729',
    buyerName: 'PVH Tommy Hilfiger',
    styleNumber: 'STY-PL-889',
    styleDescription: 'Pique Cotton Polo with Flat-Knit Collar',
    orderQuantity: 32000,
    smv: 15.0,
    allocatedOperators: 34,
    plannedDailyTarget: 1400,
    startDate: '2026-10-05',
    endDate: '2026-11-02',
    daysRequired: 23,
    status: 'SCHEDULED',
    learningCurveRampUp: {
      day1Percent: 42,
      day2Percent: 65,
      day3Percent: 82,
      day4PlusPercent: 100,
    },
    notes: 'Placket automated machine scheduled for maintenance prior to line feed.',
  },
];

export const INITIAL_TIME_STUDIES: TimeMotionStudy[] = [
  {
    id: 'tms-1',
    studyCode: 'TMS-2026-041',
    date: '2026-09-25',
    lineName: 'Sewing Line 03',
    operatorName: 'Rasheda Begum',
    operatorId: 'OP-4412',
    operationName: 'Shoulder Join (with Mobilon Tape)',
    machineType: '4-Thread Overlock',
    cycleTimesSec: [21.8, 22.4, 21.2, 23.0, 22.1],
    avgCycleTimeSec: 22.1,
    performanceRatingPercent: 105,
    basicTimeSec: 23.2,
    allowancePercent: 14,
    standardMinuteValue: 0.65,
    status: 'VERIFIED',
    studiedBy: 'Kamal Hossain (IE Executive)',
  },
  {
    id: 'tms-2',
    studyCode: 'TMS-2026-042',
    date: '2026-09-25',
    lineName: 'Sewing Line 03',
    operatorName: 'Sharmin Akter',
    operatorId: 'OP-4489',
    operationName: 'Rib Collar Prepare & Loop Join',
    machineType: 'SNLS',
    cycleTimesSec: [27.0, 26.2, 28.1, 26.5, 27.8],
    avgCycleTimeSec: 27.1,
    performanceRatingPercent: 95,
    basicTimeSec: 25.7,
    allowancePercent: 15,
    standardMinuteValue: 0.55,
    status: 'NEEDS_TRAINING',
    studiedBy: 'Kamal Hossain (IE Executive)',
  },
  {
    id: 'tms-3',
    studyCode: 'TMS-2026-043',
    date: '2026-09-26',
    lineName: 'Sewing Line 04',
    operatorName: 'Abdul Malek',
    operatorId: 'OP-5102',
    operationName: 'Front Fly Zipper Attach & J-Stitch',
    machineType: 'SNLS with Template',
    cycleTimesSec: [29.2, 30.0, 28.8, 29.5, 30.2],
    avgCycleTimeSec: 29.5,
    performanceRatingPercent: 110,
    basicTimeSec: 32.5,
    allowancePercent: 16,
    standardMinuteValue: 2.3,
    status: 'BENCHMARK_EXCEEDED',
    studiedBy: 'Mohiuddin Ahmed (Senior IE)',
  },
];

// Helper functions for localStorage
const BULLETIN_STORAGE_KEY = 'erp_operation_bulletins_v1';
const SCHEDULE_STORAGE_KEY = 'erp_production_schedules_v1';
const TIMESTUDY_STORAGE_KEY = 'erp_time_motion_studies_v1';

export function getStoredBulletins(): StyleOperationBulletin[] {
  if (typeof window === 'undefined') return INITIAL_OPERATION_BULLETINS;
  try {
    const raw = localStorage.getItem(BULLETIN_STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch {
    // ignore
  }
  return INITIAL_OPERATION_BULLETINS;
}

export function saveStoredBulletins(bulletins: StyleOperationBulletin[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(BULLETIN_STORAGE_KEY, JSON.stringify(bulletins));
    window.dispatchEvent(new Event('erp_bulletins_updated'));
  } catch {
    // ignore
  }
}

export function getStoredSchedules(): ProductionPlanSchedule[] {
  if (typeof window === 'undefined') return INITIAL_PRODUCTION_SCHEDULES;
  try {
    const raw = localStorage.getItem(SCHEDULE_STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch {
    // ignore
  }
  return INITIAL_PRODUCTION_SCHEDULES;
}

export function saveStoredSchedules(schedules: ProductionPlanSchedule[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(SCHEDULE_STORAGE_KEY, JSON.stringify(schedules));
    window.dispatchEvent(new Event('erp_schedules_updated'));
  } catch {
    // ignore
  }
}

export function getStoredTimeStudies(): TimeMotionStudy[] {
  if (typeof window === 'undefined') return INITIAL_TIME_STUDIES;
  try {
    const raw = localStorage.getItem(TIMESTUDY_STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch {
    // ignore
  }
  return INITIAL_TIME_STUDIES;
}

export function saveStoredTimeStudies(studies: TimeMotionStudy[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(TIMESTUDY_STORAGE_KEY, JSON.stringify(studies));
    window.dispatchEvent(new Event('erp_timestudies_updated'));
  } catch {
    // ignore
  }
}
