import {
  StyleOperationBulletin,
  ProductionPlanSchedule,
  TimeMotionStudy,
  FactoryMaster,
  ProductionLineMaster,
  MachineMasterItem,
  OperatorMasterItem,
  SkillMatrixItem,
  OperationMasterItem,
  ProductionOrderPlan,
  CapacityPlanningRecord,
  LinePlanningRecord,
  ManpowerPlanningRecord,
  MethodStudyRecord,
  MotionStudyRecord,
  TargetSettingRecord,
  ProductionExecutionRecord,
  HourlyMonitoringRecord,
  WipManagementRecord,
  ProductionLossRecord,
  DowntimeManagementRecord,
  ProductionQualityLink,
  ProductionReworkRecord,
  ProductionRejectionRecord,
  ProductionFollowUpRecord,
  KaizenImprovementRecord,
  ProductionAlertItem,
  UniversalAuditRecord,
} from '@/lib/types/planning-ie';

export const INITIAL_OPERATION_BULLETINS: StyleOperationBulletin[] = [
  {
    id: 'ob-1',
    styleNumber: 'STY-TS-2026',
    styleDescription: 'Men Heavyweight Cotton Crewneck Tee',
    buyerName: 'H&M Hennes & Mauritz',
    garmentType: 'T-Shirt',
    totalSmv: 11.2,
    targetLineOperators: 28,
    linePitchTimeSec: 24.0,
    targetEfficiency: 82,
    plannedDailyOutput: 1800,
    balancingEfficiency: 89.2,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
    operations: [
      {
        id: 'op-1',
        seqNumber: 1,
        operationName: 'Shoulder Join (with Mobilon Tape)',
        section: 'PREPARATION',
        machineType: '4-Thread Overlock',
        machineCode: '4T-OVL-01',
        smv: 0.65,
        theoreticalOperators: 1.6,
        allocatedOperators: 2,
        cycleTimeSec: 22.0,
        pitchTimeSec: 24.0,
        isBottleneck: false,
        remarks: 'Ensure clear mobilon elastic tension',
      },
      {
        id: 'op-2',
        seqNumber: 2,
        operationName: 'Rib Collar Prepare & Loop Join',
        section: 'PREPARATION',
        machineType: 'Single Needle Lockstitch (SNLS)',
        machineCode: 'SNLS-02',
        smv: 0.55,
        theoreticalOperators: 1.4,
        allocatedOperators: 1,
        cycleTimeSec: 26.5,
        pitchTimeSec: 24.0,
        isBottleneck: true,
        remarks: 'Operator needs helper for trimming notches',
      },
      {
        id: 'op-3',
        seqNumber: 3,
        operationName: 'Attach Rib Neck to Body',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock (Differential)',
        machineCode: '4T-OVL-02',
        smv: 1.15,
        theoreticalOperators: 2.9,
        allocatedOperators: 3,
        cycleTimeSec: 23.5,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
      {
        id: 'op-4',
        seqNumber: 4,
        operationName: 'Neck Topstitch / Binding',
        section: 'ASSEMBLY',
        machineType: 'Flatlock 2-Needle 4-Thread',
        machineCode: 'FL-01',
        smv: 0.90,
        theoreticalOperators: 2.2,
        allocatedOperators: 2,
        cycleTimeSec: 25.0,
        pitchTimeSec: 24.0,
        isBottleneck: true,
      },
      {
        id: 'op-5',
        seqNumber: 5,
        operationName: 'Back Neck Tape Attach & Folder',
        section: 'ASSEMBLY',
        machineType: 'Single Needle Chainstitch',
        machineCode: 'SNCS-01',
        smv: 0.80,
        theoreticalOperators: 2.0,
        allocatedOperators: 2,
        cycleTimeSec: 23.0,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
      {
        id: 'op-6',
        seqNumber: 6,
        operationName: 'Sleeve Open Hem Fold & Stitch',
        section: 'PREPARATION',
        machineType: 'Flatlock Bottom Hem',
        machineCode: 'FL-02',
        smv: 1.10,
        theoreticalOperators: 2.7,
        allocatedOperators: 3,
        cycleTimeSec: 22.5,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
      {
        id: 'op-7',
        seqNumber: 7,
        operationName: 'Sleeve Attach to Armhole (Both sides)',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock',
        machineCode: '4T-OVL-03',
        smv: 1.45,
        theoreticalOperators: 3.6,
        allocatedOperators: 4,
        cycleTimeSec: 22.0,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
      {
        id: 'op-8',
        seqNumber: 8,
        operationName: 'Side Seam Close with Care Label Insert',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock',
        machineCode: '4T-OVL-04',
        smv: 1.55,
        theoreticalOperators: 3.8,
        allocatedOperators: 4,
        cycleTimeSec: 23.8,
        pitchTimeSec: 24.0,
        isBottleneck: false,
        remarks: 'Care label inserted at 10cm from bottom hem',
      },
      {
        id: 'op-9',
        seqNumber: 9,
        operationName: 'Bottom Hem Fold & Flatlock Stitch',
        section: 'ASSEMBLY',
        machineType: 'Flatlock 3-Needle Cylinder Bed',
        machineCode: 'FL-03',
        smv: 1.30,
        theoreticalOperators: 3.2,
        allocatedOperators: 3,
        cycleTimeSec: 25.2,
        pitchTimeSec: 24.0,
        isBottleneck: true,
      },
      {
        id: 'op-10',
        seqNumber: 10,
        operationName: 'Bartack at Neck Joint & Side Seam Ends',
        section: 'FINISHING',
        machineType: 'Electronic Bartack',
        machineCode: 'BT-01',
        smv: 0.60,
        theoreticalOperators: 1.5,
        allocatedOperators: 2,
        cycleTimeSec: 18.0,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
      {
        id: 'op-11',
        seqNumber: 11,
        operationName: 'Thread Trimming & In-Line Inspection',
        section: 'FINISHING',
        machineType: 'Manual Trimming & QC Table',
        machineCode: 'MANUAL',
        smv: 1.15,
        theoreticalOperators: 2.9,
        allocatedOperators: 3,
        cycleTimeSec: 23.0,
        pitchTimeSec: 24.0,
        isBottleneck: false,
      },
    ],
  },
  {
    id: 'ob-2',
    styleNumber: 'STY-DN-502',
    styleDescription: 'Slim Fit Washed Indigo Denim Jeans 12oz',
    buyerName: 'Inditex / Zara',
    garmentType: 'Denim Jeans',
    totalSmv: 22.4,
    targetLineOperators: 48,
    linePitchTimeSec: 28.0,
    targetEfficiency: 80,
    plannedDailyOutput: 950,
    balancingEfficiency: 86.8,
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-22T14:30:00Z',
    operations: [
      {
        id: 'op-201',
        seqNumber: 1,
        operationName: 'Front Pocket Bag Prepare & Serging',
        section: 'PREPARATION',
        machineType: '3-Thread Overlock',
        machineCode: '3T-OVL',
        smv: 1.2,
        theoreticalOperators: 2.1,
        allocatedOperators: 2,
        cycleTimeSec: 27.0,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-202',
        seqNumber: 2,
        operationName: 'Coin Pocket Attach & Rivet Marking',
        section: 'PREPARATION',
        machineType: 'Double Needle Lockstitch (DNLS)',
        machineCode: 'DNLS-01',
        smv: 0.85,
        theoreticalOperators: 1.5,
        allocatedOperators: 2,
        cycleTimeSec: 24.0,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-203',
        seqNumber: 3,
        operationName: 'Back Pocket Hem & Decorative Embroidery',
        section: 'PREPARATION',
        machineType: 'Pattern Sewing Automated CNC',
        machineCode: 'CNC-01',
        smv: 1.4,
        theoreticalOperators: 2.4,
        allocatedOperators: 2,
        cycleTimeSec: 30.5,
        pitchTimeSec: 28.0,
        isBottleneck: true,
      },
      {
        id: 'op-204',
        seqNumber: 4,
        operationName: 'Back Pocket Attach to Back Panel',
        section: 'ASSEMBLY',
        machineType: 'Twin Needle Post Bed with Guide',
        machineCode: 'DNLS-02',
        smv: 2.1,
        theoreticalOperators: 3.6,
        allocatedOperators: 4,
        cycleTimeSec: 27.5,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-205',
        seqNumber: 5,
        operationName: 'Back Yoke Join & Double Topstitch',
        section: 'ASSEMBLY',
        machineType: 'Feed-off-the-Arm Lap Seam',
        machineCode: 'FOA-01',
        smv: 1.6,
        theoreticalOperators: 2.8,
        allocatedOperators: 3,
        cycleTimeSec: 26.0,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-206',
        seqNumber: 6,
        operationName: 'Back Rise Join (Fell Seam)',
        section: 'ASSEMBLY',
        machineType: 'Feed-off-the-Arm 3-Needle',
        machineCode: 'FOA-02',
        smv: 1.5,
        theoreticalOperators: 2.6,
        allocatedOperators: 3,
        cycleTimeSec: 27.0,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-207',
        seqNumber: 7,
        operationName: 'Front Fly Zipper Attach & J-Stitch',
        section: 'ASSEMBLY',
        machineType: 'SNLS with J-Stitch Template',
        machineCode: 'SNLS-04',
        smv: 2.3,
        theoreticalOperators: 4.0,
        allocatedOperators: 4,
        cycleTimeSec: 29.5,
        pitchTimeSec: 28.0,
        isBottleneck: true,
      },
      {
        id: 'op-208',
        seqNumber: 8,
        operationName: 'Inseam Join with Double Lap Seam',
        section: 'ASSEMBLY',
        machineType: 'Feed-off-the-Arm Chainstitch',
        machineCode: 'FOA-03',
        smv: 2.2,
        theoreticalOperators: 3.8,
        allocatedOperators: 4,
        cycleTimeSec: 27.5,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-209',
        seqNumber: 9,
        operationName: 'Outseam Join (Safety 5-Thread Overlock)',
        section: 'ASSEMBLY',
        machineType: '5-Thread Heavy Overlock',
        machineCode: '5T-OVL',
        smv: 1.9,
        theoreticalOperators: 3.3,
        allocatedOperators: 3,
        cycleTimeSec: 31.0,
        pitchTimeSec: 28.0,
        isBottleneck: true,
      },
      {
        id: 'op-210',
        seqNumber: 10,
        operationName: 'Waistband Attach (Kansai Special Multi-Needle)',
        section: 'ASSEMBLY',
        machineType: 'Kansai Special Waistband Machine',
        machineCode: 'KANSAI-01',
        smv: 2.8,
        theoreticalOperators: 4.8,
        allocatedOperators: 5,
        cycleTimeSec: 27.8,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-211',
        seqNumber: 11,
        operationName: 'Belt Loop Attach (5 positions)',
        section: 'ASSEMBLY',
        machineType: 'Automated Belt Loop Setter',
        machineCode: 'BLS-01',
        smv: 1.5,
        theoreticalOperators: 2.6,
        allocatedOperators: 3,
        cycleTimeSec: 25.0,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-212',
        seqNumber: 12,
        operationName: 'Bottom Hemming (Union Special Chainstitch)',
        section: 'ASSEMBLY',
        machineType: 'Union Special Lockstitch / Chainstitch',
        machineCode: 'US-01',
        smv: 1.4,
        theoreticalOperators: 2.4,
        allocatedOperators: 3,
        cycleTimeSec: 24.5,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
      {
        id: 'op-213',
        seqNumber: 13,
        operationName: 'Button Hole, Shank Button & Riveting',
        section: 'FINISHING',
        machineType: 'Eyelet Buttonhole & Pneumatic Riveter',
        machineCode: 'EBH-01',
        smv: 1.6,
        theoreticalOperators: 2.8,
        allocatedOperators: 3,
        cycleTimeSec: 26.5,
        pitchTimeSec: 28.0,
        isBottleneck: false,
      },
    ],
  },
  {
    id: 'ob-3',
    styleNumber: 'STY-PL-889',
    styleDescription: 'Pique Cotton Polo with Flat-Knit Collar',
    buyerName: 'PVH Tommy Hilfiger',
    garmentType: 'Polo Shirt',
    totalSmv: 15.0,
    targetLineOperators: 34,
    linePitchTimeSec: 26.5,
    targetEfficiency: 82,
    plannedDailyOutput: 1400,
    balancingEfficiency: 87.5,
    createdAt: '2026-09-08T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z',
    operations: [
      {
        id: 'op-301',
        seqNumber: 1,
        operationName: 'Placket Fusing & Creasing',
        section: 'PREPARATION',
        machineType: 'Mini Fusing Press',
        machineCode: 'FUSE-01',
        smv: 0.8,
        theoreticalOperators: 1.8,
        allocatedOperators: 2,
        cycleTimeSec: 25.0,
        pitchTimeSec: 26.5,
        isBottleneck: false,
      },
      {
        id: 'op-302',
        seqNumber: 2,
        operationName: 'Box Placket Cut & Make on Front Body',
        section: 'PREPARATION',
        machineType: 'Automated Placket Setting Machine',
        machineCode: 'APS-01',
        smv: 2.4,
        theoreticalOperators: 5.4,
        allocatedOperators: 6,
        cycleTimeSec: 25.5,
        pitchTimeSec: 26.5,
        isBottleneck: false,
      },
      {
        id: 'op-303',
        seqNumber: 3,
        operationName: 'Collar Rib Attach & Overlock',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock',
        machineCode: '4T-OVL',
        smv: 1.6,
        theoreticalOperators: 3.6,
        allocatedOperators: 4,
        cycleTimeSec: 26.0,
        pitchTimeSec: 26.5,
        isBottleneck: false,
      },
      {
        id: 'op-304',
        seqNumber: 4,
        operationName: 'Collar Band Topstitch with Twill Tape',
        section: 'ASSEMBLY',
        machineType: 'SNLS with Tape Guide',
        machineCode: 'SNLS',
        smv: 1.5,
        theoreticalOperators: 3.4,
        allocatedOperators: 4,
        cycleTimeSec: 25.0,
        pitchTimeSec: 26.5,
        isBottleneck: false,
      },
      {
        id: 'op-305',
        seqNumber: 5,
        operationName: 'Side Vent Make & Herringbone Reinforcement',
        section: 'ASSEMBLY',
        machineType: 'SNLS',
        machineCode: 'SNLS',
        smv: 1.8,
        theoreticalOperators: 4.1,
        allocatedOperators: 4,
        cycleTimeSec: 29.0,
        pitchTimeSec: 26.5,
        isBottleneck: true,
      },
    ],
  },
  {
    id: 'ob-4',
    styleNumber: 'STY-HD-770',
    styleDescription: 'French Terry Heavyweight Kangaroo Hoodie 320 GSM',
    buyerName: 'Uniqlo Fast Retailing',
    garmentType: 'Hoodie',
    totalSmv: 19.5,
    targetLineOperators: 42,
    linePitchTimeSec: 27.8,
    targetEfficiency: 84,
    plannedDailyOutput: 1100,
    balancingEfficiency: 88.4,
    createdAt: '2026-09-12T08:30:00Z',
    updatedAt: '2026-09-26T15:00:00Z',
    operations: [
      {
        id: 'op-401',
        seqNumber: 1,
        operationName: 'Kangaroo Front Pocket Hem & Turn Top/Bottom',
        section: 'PREPARATION',
        machineType: 'Flatlock 2-Needle Top & Bottom Cover',
        machineCode: 'FL-04',
        smv: 1.25,
        theoreticalOperators: 2.7,
        allocatedOperators: 3,
        cycleTimeSec: 25.0,
        pitchTimeSec: 27.8,
        isBottleneck: false,
        remarks: 'Ensure edge clean fold with pneumatic hemmer',
      },
      {
        id: 'op-402',
        seqNumber: 2,
        operationName: 'Kangaroo Pocket Attach to Front Panel with Bartacks',
        section: 'PREPARATION',
        machineType: 'Double Needle Lockstitch (DNLS) + Bartack',
        machineCode: 'DNLS-03',
        smv: 2.10,
        theoreticalOperators: 4.5,
        allocatedOperators: 5,
        cycleTimeSec: 25.2,
        pitchTimeSec: 27.8,
        isBottleneck: false,
      },
      {
        id: 'op-403',
        seqNumber: 3,
        operationName: '3-Panel Hood Center Strip Join & Overlock',
        section: 'PREPARATION',
        machineType: '4-Thread Overlock Heavy Duty',
        machineCode: '4T-OVL-05',
        smv: 1.40,
        theoreticalOperators: 3.0,
        allocatedOperators: 3,
        cycleTimeSec: 28.0,
        pitchTimeSec: 27.8,
        isBottleneck: true,
      },
      {
        id: 'op-404',
        seqNumber: 4,
        operationName: 'Hood Eyelet Punching & Brass Eyelet Setting',
        section: 'PREPARATION',
        machineType: 'Automated Eyelet Setting Press',
        machineCode: 'EYE-01',
        smv: 0.90,
        theoreticalOperators: 1.9,
        allocatedOperators: 2,
        cycleTimeSec: 27.0,
        pitchTimeSec: 27.8,
        isBottleneck: false,
      },
      {
        id: 'op-405',
        seqNumber: 5,
        operationName: 'Drawcord Insertion & Knot Tying',
        section: 'PREPARATION',
        machineType: 'Pneumatic Drawcord Threader Table',
        machineCode: 'MANUAL',
        smv: 0.85,
        theoreticalOperators: 1.8,
        allocatedOperators: 2,
        cycleTimeSec: 25.5,
        pitchTimeSec: 27.8,
        isBottleneck: false,
      },
      {
        id: 'op-406',
        seqNumber: 6,
        operationName: 'Shoulder Join with Clear Mobilon Stabilizer Tape',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock',
        machineCode: '4T-OVL-06',
        smv: 0.95,
        theoreticalOperators: 2.0,
        allocatedOperators: 2,
        cycleTimeSec: 28.5,
        pitchTimeSec: 27.8,
        isBottleneck: true,
      },
      {
        id: 'op-407',
        seqNumber: 7,
        operationName: 'Hood Attach to Neck Opening',
        section: 'ASSEMBLY',
        machineType: '4-Thread Differential Overlock',
        machineCode: '4T-OVL-07',
        smv: 2.20,
        theoreticalOperators: 4.7,
        allocatedOperators: 5,
        cycleTimeSec: 26.4,
        pitchTimeSec: 27.8,
        isBottleneck: false,
      },
      {
        id: 'op-408',
        seqNumber: 8,
        operationName: 'Neck Seam Clean Finish with Herringbone Tape',
        section: 'ASSEMBLY',
        machineType: 'Single Needle Chainstitch Folder',
        machineCode: 'SNCS-02',
        smv: 1.30,
        theoreticalOperators: 2.8,
        allocatedOperators: 3,
        cycleTimeSec: 26.0,
        pitchTimeSec: 27.8,
        isBottleneck: false,
      },
      {
        id: 'op-409',
        seqNumber: 9,
        operationName: 'Raglan Sleeve Attach to Armholes (Front & Back)',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock',
        machineCode: '4T-OVL-08',
        smv: 2.40,
        theoreticalOperators: 5.2,
        allocatedOperators: 5,
        cycleTimeSec: 28.8,
        pitchTimeSec: 27.8,
        isBottleneck: true,
      },
      {
        id: 'op-410',
        seqNumber: 10,
        operationName: 'Underarm Sleeve & Body Side Seam Continuous Join',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock (5000 RPM)',
        machineCode: '4T-OVL-09',
        smv: 2.20,
        theoreticalOperators: 4.7,
        allocatedOperators: 5,
        cycleTimeSec: 26.4,
        pitchTimeSec: 27.8,
        isBottleneck: false,
      },
      {
        id: 'op-411',
        seqNumber: 11,
        operationName: 'Rib Sleeve Cuffs Loop Make & Attach',
        section: 'ASSEMBLY',
        machineType: '4-Thread Overlock Cylinder Bed',
        machineCode: '4T-CYL-01',
        smv: 1.65,
        theoreticalOperators: 3.6,
        allocatedOperators: 4,
        cycleTimeSec: 24.8,
        pitchTimeSec: 27.8,
        isBottleneck: false,
      },
      {
        id: 'op-412',
        seqNumber: 12,
        operationName: 'Rib Bottom Band Hem Join & Differential Overlock',
        section: 'ASSEMBLY',
        machineType: '4-Thread Differential Overlock',
        machineCode: '4T-OVL-10',
        smv: 1.85,
        theoreticalOperators: 4.0,
        allocatedOperators: 4,
        cycleTimeSec: 27.8,
        pitchTimeSec: 27.8,
        isBottleneck: false,
      },
      {
        id: 'op-413',
        seqNumber: 13,
        operationName: 'Bartack at Kangaroo Pocket Corners & Neck Tape Ends',
        section: 'FINISHING',
        machineType: 'Electronic Programmable Bartack',
        machineCode: 'BT-02',
        smv: 0.85,
        theoreticalOperators: 1.8,
        allocatedOperators: 2,
        cycleTimeSec: 25.5,
        pitchTimeSec: 27.8,
        isBottleneck: false,
      },
      {
        id: 'op-414',
        seqNumber: 14,
        operationName: 'Complete Trimming, Steaming & End-of-Line Audit',
        section: 'FINISHING',
        machineType: 'Suction Trimmer & Light Table',
        machineCode: 'QC-TABLE-02',
        smv: 1.10,
        theoreticalOperators: 2.4,
        allocatedOperators: 3,
        cycleTimeSec: 22.0,
        pitchTimeSec: 27.8,
        isBottleneck: false,
      },
    ],
  },
  {
    id: 'ob-5',
    styleNumber: 'STY-SH-410',
    styleDescription: 'Formal Long Sleeve Poplin Cotton Shirt with Collar Band & Cuffs',
    buyerName: 'Marks & Spencer (M&S)',
    garmentType: 'Woven Shirt',
    totalSmv: 18.2,
    targetLineOperators: 42,
    linePitchTimeSec: 26.0,
    targetEfficiency: 82,
    plannedDailyOutput: 1250,
    balancingEfficiency: 89.1,
    createdAt: '2026-09-14T09:00:00Z',
    updatedAt: '2026-09-25T11:20:00Z',
    operations: [
      {
        id: 'op-501',
        seqNumber: 1,
        operationName: 'Collar Leaf Runstitch & Point Trimming',
        section: 'PREPARATION',
        machineType: 'Single Needle Lockstitch (SNLS)',
        machineCode: 'SNLS-10',
        smv: 1.20,
        theoreticalOperators: 2.8,
        allocatedOperators: 3,
        cycleTimeSec: 24.0,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
      {
        id: 'op-502',
        seqNumber: 2,
        operationName: 'Collar Leaf Topstitch (1/16" edge gauge)',
        section: 'PREPARATION',
        machineType: 'SNLS with Compensating Foot',
        machineCode: 'SNLS-11',
        smv: 0.95,
        theoreticalOperators: 2.2,
        allocatedOperators: 2,
        cycleTimeSec: 28.5,
        pitchTimeSec: 26.0,
        isBottleneck: true,
      },
      {
        id: 'op-503',
        seqNumber: 3,
        operationName: 'Collar Band Sandwich Join & Crease',
        section: 'PREPARATION',
        machineType: 'SNLS with Edge Guide',
        machineCode: 'SNLS-12',
        smv: 1.30,
        theoreticalOperators: 3.0,
        allocatedOperators: 3,
        cycleTimeSec: 26.0,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
      {
        id: 'op-504',
        seqNumber: 4,
        operationName: 'Front Box Placket Fuse & Stitch (Left Front)',
        section: 'PREPARATION',
        machineType: 'Twin Needle Lockstitch with Placket Folder',
        machineCode: 'DNLS-04',
        smv: 1.45,
        theoreticalOperators: 3.3,
        allocatedOperators: 3,
        cycleTimeSec: 29.0,
        pitchTimeSec: 26.0,
        isBottleneck: true,
      },
      {
        id: 'op-505',
        seqNumber: 5,
        operationName: 'Sleeve Placket (Continuous Gauntlet & Triangle Point)',
        section: 'PREPARATION',
        machineType: 'Single Needle Lockstitch',
        machineCode: 'SNLS-13',
        smv: 1.80,
        theoreticalOperators: 4.2,
        allocatedOperators: 4,
        cycleTimeSec: 27.0,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
      {
        id: 'op-506',
        seqNumber: 6,
        operationName: 'Cuff Interlining Fuse, Runstitch & Turn',
        section: 'PREPARATION',
        machineType: 'SNLS with Corner Turner',
        machineCode: 'SNLS-14',
        smv: 1.40,
        theoreticalOperators: 3.2,
        allocatedOperators: 3,
        cycleTimeSec: 28.0,
        pitchTimeSec: 26.0,
        isBottleneck: true,
      },
      {
        id: 'op-507',
        seqNumber: 7,
        operationName: 'Back Yoke Sandwich Join with Back Body Pleats',
        section: 'ASSEMBLY',
        machineType: 'Single Needle Lockstitch',
        machineCode: 'SNLS-15',
        smv: 1.35,
        theoreticalOperators: 3.1,
        allocatedOperators: 3,
        cycleTimeSec: 27.0,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
      {
        id: 'op-508',
        seqNumber: 8,
        operationName: 'Front Shoulder Join to Yoke with Topstitch',
        section: 'ASSEMBLY',
        machineType: 'SNLS with Topstitch Guide',
        machineCode: 'SNLS-16',
        smv: 1.10,
        theoreticalOperators: 2.5,
        allocatedOperators: 3,
        cycleTimeSec: 22.0,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
      {
        id: 'op-509',
        seqNumber: 9,
        operationName: 'Collar Band Attach to Neckline Opening',
        section: 'ASSEMBLY',
        machineType: 'Single Needle Lockstitch',
        machineCode: 'SNLS-17',
        smv: 1.70,
        theoreticalOperators: 3.9,
        allocatedOperators: 4,
        cycleTimeSec: 25.5,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
      {
        id: 'op-510',
        seqNumber: 10,
        operationName: 'Collar Band Topstitch & Neck Closing',
        section: 'ASSEMBLY',
        machineType: 'SNLS with 1/16" Edge Gauge',
        machineCode: 'SNLS-18',
        smv: 1.25,
        theoreticalOperators: 2.9,
        allocatedOperators: 3,
        cycleTimeSec: 25.0,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
      {
        id: 'op-511',
        seqNumber: 11,
        operationName: 'Sleeve Set to Armhole (Both Sides)',
        section: 'ASSEMBLY',
        machineType: 'Twin Needle Chainstitch with Armhole Folder',
        machineCode: 'DNCS-01',
        smv: 1.85,
        theoreticalOperators: 4.3,
        allocatedOperators: 4,
        cycleTimeSec: 27.8,
        pitchTimeSec: 26.0,
        isBottleneck: true,
      },
      {
        id: 'op-512',
        seqNumber: 12,
        operationName: 'Side Seam & Inseam Join (Double Felled Lap Seam)',
        section: 'ASSEMBLY',
        machineType: 'Feed-off-the-Arm 2-Needle Lap Seam',
        machineCode: 'FOA-04',
        smv: 1.95,
        theoreticalOperators: 4.5,
        allocatedOperators: 5,
        cycleTimeSec: 23.4,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
      {
        id: 'op-513',
        seqNumber: 13,
        operationName: 'Cuff Attach to Sleeve Opening with Pleats',
        section: 'ASSEMBLY',
        machineType: 'Single Needle Lockstitch',
        machineCode: 'SNLS-19',
        smv: 1.60,
        theoreticalOperators: 3.7,
        allocatedOperators: 4,
        cycleTimeSec: 24.0,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
      {
        id: 'op-514',
        seqNumber: 14,
        operationName: 'Bottom Curved Hem Roll & Stitch with Side Reinforcements',
        section: 'ASSEMBLY',
        machineType: 'SNLS with Hemmer Folder Foot',
        machineCode: 'SNLS-20',
        smv: 1.40,
        theoreticalOperators: 3.2,
        allocatedOperators: 3,
        cycleTimeSec: 28.0,
        pitchTimeSec: 26.0,
        isBottleneck: true,
      },
      {
        id: 'op-515',
        seqNumber: 15,
        operationName: 'Button Hole Front (7x), Collar (1x), Cuffs (4x)',
        section: 'FINISHING',
        machineType: 'Electronic Automatic Buttonholer',
        machineCode: 'BH-02',
        smv: 1.25,
        theoreticalOperators: 2.9,
        allocatedOperators: 3,
        cycleTimeSec: 25.0,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
      {
        id: 'op-516',
        seqNumber: 16,
        operationName: 'Button Attach (12 buttons) & End Inspection',
        section: 'FINISHING',
        machineType: 'Electronic Button Attaching Machine',
        machineCode: 'BA-02',
        smv: 1.10,
        theoreticalOperators: 2.5,
        allocatedOperators: 3,
        cycleTimeSec: 22.0,
        pitchTimeSec: 26.0,
        isBottleneck: false,
      },
    ],
  },
  {
    id: 'ob-6',
    styleNumber: 'STY-LG-920',
    styleDescription: 'Women High-Rise Seamless Active Leggings with Gusset',
    buyerName: 'Target / JoyLab Athletic',
    garmentType: 'Activewear',
    totalSmv: 10.8,
    targetLineOperators: 28,
    linePitchTimeSec: 23.1,
    targetEfficiency: 86,
    plannedDailyOutput: 1950,
    balancingEfficiency: 90.2,
    createdAt: '2026-09-18T10:00:00Z',
    updatedAt: '2026-09-28T14:15:00Z',
    operations: [
      {
        id: 'op-601',
        seqNumber: 1,
        operationName: 'Diamond Crotch Gusset Serging & Stay Stitch',
        section: 'PREPARATION',
        machineType: '3-Thread Overlock Micro-Stitch',
        machineCode: '3T-OVL-02',
        smv: 0.70,
        theoreticalOperators: 1.8,
        allocatedOperators: 2,
        cycleTimeSec: 21.0,
        pitchTimeSec: 23.1,
        isBottleneck: false,
      },
      {
        id: 'op-602',
        seqNumber: 2,
        operationName: 'Contour High-Rise Waistband Make & Inner Pocket Stitch',
        section: 'PREPARATION',
        machineType: 'Flatlock 2-Needle 4-Thread',
        machineCode: 'FL-05',
        smv: 1.15,
        theoreticalOperators: 3.0,
        allocatedOperators: 3,
        cycleTimeSec: 23.0,
        pitchTimeSec: 23.1,
        isBottleneck: false,
      },
      {
        id: 'op-603',
        seqNumber: 3,
        operationName: 'Gusset Attach to Front & Back Rise',
        section: 'ASSEMBLY',
        machineType: '4-Needle 6-Thread Flatseam (Feed-off-the-Arm)',
        machineCode: 'FS-01',
        smv: 1.35,
        theoreticalOperators: 3.5,
        allocatedOperators: 4,
        cycleTimeSec: 20.3,
        pitchTimeSec: 23.1,
        isBottleneck: false,
      },
      {
        id: 'op-604',
        seqNumber: 4,
        operationName: 'Front & Back Rise Center Seam Flatseam',
        section: 'ASSEMBLY',
        machineType: '4-Needle Flatseam Machine',
        machineCode: 'FS-02',
        smv: 1.25,
        theoreticalOperators: 3.2,
        allocatedOperators: 3,
        cycleTimeSec: 25.0,
        pitchTimeSec: 23.1,
        isBottleneck: true,
      },
      {
        id: 'op-605',
        seqNumber: 5,
        operationName: 'Inseam Continuous Join across Gusset',
        section: 'ASSEMBLY',
        machineType: '4-Needle 6-Thread Flatseam',
        machineCode: 'FS-03',
        smv: 1.60,
        theoreticalOperators: 4.2,
        allocatedOperators: 4,
        cycleTimeSec: 24.0,
        pitchTimeSec: 23.1,
        isBottleneck: true,
      },
      {
        id: 'op-606',
        seqNumber: 6,
        operationName: 'Side Panel Ergonomic Curved Seam Join',
        section: 'ASSEMBLY',
        machineType: '4-Thread Stretch Overlock',
        machineCode: '4T-OVL-11',
        smv: 1.45,
        theoreticalOperators: 3.8,
        allocatedOperators: 4,
        cycleTimeSec: 21.8,
        pitchTimeSec: 23.1,
        isBottleneck: false,
      },
      {
        id: 'op-607',
        seqNumber: 7,
        operationName: 'Waistband Attach to Legging Body with Clear Elastic Tension',
        section: 'ASSEMBLY',
        machineType: '4-Thread Differential Overlock with Metering Device',
        machineCode: '4T-MTR-01',
        smv: 1.55,
        theoreticalOperators: 4.0,
        allocatedOperators: 4,
        cycleTimeSec: 23.2,
        pitchTimeSec: 23.1,
        isBottleneck: false,
      },
      {
        id: 'op-608',
        seqNumber: 8,
        operationName: 'Waistband Topstitch (Flatlock 3-Needle)',
        section: 'ASSEMBLY',
        machineType: 'Flatlock 3-Needle Cylinder Bed',
        machineCode: 'FL-06',
        smv: 0.95,
        theoreticalOperators: 2.5,
        allocatedOperators: 3,
        cycleTimeSec: 19.0,
        pitchTimeSec: 23.1,
        isBottleneck: false,
      },
      {
        id: 'op-609',
        seqNumber: 9,
        operationName: 'Ankle Leg Opening Hem Fold & Coverstitch',
        section: 'ASSEMBLY',
        machineType: 'Flatlock Small Cylinder Bed',
        machineCode: 'FL-CYL-02',
        smv: 1.05,
        theoreticalOperators: 2.7,
        allocatedOperators: 3,
        cycleTimeSec: 21.0,
        pitchTimeSec: 23.1,
        isBottleneck: false,
      },
      {
        id: 'op-610',
        seqNumber: 10,
        operationName: 'Heat Transfer Logo Apply & 100% Stretch Inspection',
        section: 'FINISHING',
        machineType: 'Pneumatic Heat Press & Stretch Gauge Board',
        machineCode: 'HP-01',
        smv: 0.80,
        theoreticalOperators: 2.1,
        allocatedOperators: 2,
        cycleTimeSec: 24.0,
        pitchTimeSec: 23.1,
        isBottleneck: true,
      },
    ],
  },
];

export const INITIAL_PRODUCTION_SCHEDULES: ProductionPlanSchedule[] = [
  {
    id: 'mps-1',
    lineId: 'Line 01',
    lineName: 'Sewing Line 01 (Knit Crewneck)',
    orderNumber: 'PO-HM-99201',
    buyerName: 'H&M Hennes & Mauritz',
    styleNumber: 'STY-TS-2026',
    styleDescription: 'Men Heavyweight Cotton Crewneck Tee',
    orderQuantity: 45000,
    smv: 11.2,
    allocatedOperators: 28,
    plannedDailyTarget: 1800,
    startDate: '2026-09-19',
    endDate: '2026-10-14',
    daysRequired: 25,
    status: 'RUNNING',
    learningCurveRampUp: {
      day1Percent: 45,
      day2Percent: 68,
      day3Percent: 85,
      day4PlusPercent: 100,
    },
    notes: 'Running at 78% efficiency; target reached on Day 4. 24,750 pcs completed to date.',
    actualProducedQty: 24750,
    planVsActualPercent: 96.5,
    fabricStatus: '100% Received in Store - Passed QC',
    targetEfficiency: 82,
    pitchTimeSec: 24.0,
  },
  {
    id: 'mps-2',
    lineId: 'Line 04',
    lineName: 'Sewing Line 04 (Heavy Denim 12oz)',
    orderNumber: 'PO-ZARA-4482',
    buyerName: 'Inditex / Zara',
    styleNumber: 'STY-DN-502',
    styleDescription: 'Slim Fit Washed Indigo Denim Jeans 12oz',
    orderQuantity: 28000,
    smv: 22.4,
    allocatedOperators: 48,
    plannedDailyTarget: 950,
    startDate: '2026-09-29',
    endDate: '2026-10-28',
    daysRequired: 29,
    status: 'SCHEDULED',
    learningCurveRampUp: {
      day1Percent: 40,
      day2Percent: 60,
      day3Percent: 80,
      day4PlusPercent: 100,
    },
    notes: 'Tooling setup complete; Kansai waistband folder guides tested.',
    actualProducedQty: 0,
    planVsActualPercent: 0,
    fabricStatus: '100% In-House - Cutting In-Progress',
    targetEfficiency: 78,
    pitchTimeSec: 28.0,
  },
  {
    id: 'mps-3',
    lineId: 'Line 02',
    lineName: 'Sewing Line 02 (Polo Specialist)',
    orderNumber: 'PO-PVH-7729',
    buyerName: 'PVH Tommy Hilfiger',
    styleNumber: 'STY-PL-889',
    styleDescription: 'Pique Cotton Polo with Flat-Knit Collar',
    orderQuantity: 32000,
    smv: 15.0,
    allocatedOperators: 34,
    plannedDailyTarget: 1400,
    startDate: '2026-10-05',
    endDate: '2026-11-02',
    daysRequired: 23,
    status: 'SCHEDULED',
    learningCurveRampUp: {
      day1Percent: 42,
      day2Percent: 65,
      day3Percent: 82,
      day4PlusPercent: 100,
    },
    notes: 'Placket automated machine scheduled for maintenance prior to line feed.',
    actualProducedQty: 0,
    planVsActualPercent: 0,
    fabricStatus: '100% Received - Trims Verified',
    targetEfficiency: 80,
    pitchTimeSec: 26.5,
  },
  {
    id: 'mps-4',
    lineId: 'Line 03',
    lineName: 'Sewing Line 03 (Heavy T-Shirt & Hoodies)',
    orderNumber: 'PO-UNI-6619',
    buyerName: 'Uniqlo Fast Retailing',
    styleNumber: 'STY-HD-770',
    styleDescription: 'French Terry Heavyweight Kangaroo Hoodie 320 GSM',
    orderQuantity: 40000,
    smv: 19.5,
    allocatedOperators: 42,
    plannedDailyTarget: 1100,
    startDate: '2026-10-12',
    endDate: '2026-11-18',
    daysRequired: 36,
    status: 'SCHEDULED',
    learningCurveRampUp: {
      day1Percent: 40,
      day2Percent: 62,
      day3Percent: 80,
      day4PlusPercent: 100,
    },
    notes: 'Fleece fabric relaxed 48h; kangaroo pocket jigs verified.',
    actualProducedQty: 0,
    planVsActualPercent: 0,
    fabricStatus: 'Fabric 100% In-House - Ready for Pilot Cut',
    targetEfficiency: 84,
    pitchTimeSec: 27.8,
  },
  {
    id: 'mps-5',
    lineId: 'Line 05',
    lineName: 'Sewing Line 05 (Woven Dress Shirts)',
    orderNumber: 'PO-MKS-3104',
    buyerName: 'Marks & Spencer (M&S)',
    styleNumber: 'STY-SH-410',
    styleDescription: 'Formal Long Sleeve Poplin Cotton Shirt with Collar Band & Cuffs',
    orderQuantity: 22000,
    smv: 18.2,
    allocatedOperators: 42,
    plannedDailyTarget: 1250,
    startDate: '2026-10-15',
    endDate: '2026-11-05',
    daysRequired: 18,
    status: 'SCHEDULED',
    learningCurveRampUp: {
      day1Percent: 45,
      day2Percent: 70,
      day3Percent: 88,
      day4PlusPercent: 100,
    },
    notes: 'Continuous fusing machine certified for collar band stiffness.',
    actualProducedQty: 0,
    planVsActualPercent: 0,
    fabricStatus: '100% In-House - Interlining Verified',
    targetEfficiency: 82,
    pitchTimeSec: 26.0,
  },
  {
    id: 'mps-6',
    lineId: 'Line 06',
    lineName: 'Sewing Line 06 (Technical Outerwear & Activewear)',
    orderNumber: 'PO-TGT-5501',
    buyerName: 'Target / JoyLab Athletic',
    styleNumber: 'STY-LG-920',
    styleDescription: 'Women High-Rise Seamless Active Leggings with Gusset',
    orderQuantity: 30000,
    smv: 10.8,
    allocatedOperators: 28,
    plannedDailyTarget: 1950,
    startDate: '2026-10-18',
    endDate: '2026-11-06',
    daysRequired: 16,
    status: 'SCHEDULED',
    learningCurveRampUp: {
      day1Percent: 48,
      day2Percent: 72,
      day3Percent: 88,
      day4PlusPercent: 100,
    },
    notes: 'Yamato 4-needle flatseam machines threaded with textured nylon thread.',
    actualProducedQty: 0,
    planVsActualPercent: 0,
    fabricStatus: 'Interlock Spandex In-House - 4-Point Passed',
    targetEfficiency: 86,
    pitchTimeSec: 23.1,
  },
];

export const INITIAL_TIME_STUDIES: TimeMotionStudy[] = [
  {
    id: 'tms-1',
    studyCode: 'TMS-2026-041',
    date: '2026-09-25',
    lineName: 'Sewing Line 03',
    operatorName: 'Rasheda Begum',
    operatorId: 'OP-4412',
    operationName: 'Shoulder Join (with Mobilon Tape)',
    machineType: '4-Thread Overlock',
    cycleTimesSec: [21.8, 22.4, 21.2, 23.0, 22.1],
    avgCycleTimeSec: 22.1,
    performanceRatingPercent: 105,
    basicTimeSec: 23.2,
    allowancePercent: 14,
    standardMinuteValue: 0.65,
    status: 'VERIFIED',
    studiedBy: 'Kamal Hossain (IE Executive)',
  },
  {
    id: 'tms-2',
    studyCode: 'TMS-2026-042',
    date: '2026-09-25',
    lineName: 'Sewing Line 03',
    operatorName: 'Sharmin Akter',
    operatorId: 'OP-4489',
    operationName: 'Rib Collar Prepare & Loop Join',
    machineType: 'SNLS',
    cycleTimesSec: [27.0, 26.2, 28.1, 26.5, 27.8],
    avgCycleTimeSec: 27.1,
    performanceRatingPercent: 95,
    basicTimeSec: 25.7,
    allowancePercent: 15,
    standardMinuteValue: 0.55,
    status: 'NEEDS_TRAINING',
    studiedBy: 'Kamal Hossain (IE Executive)',
  },
  {
    id: 'tms-3',
    studyCode: 'TMS-2026-043',
    date: '2026-09-26',
    lineName: 'Sewing Line 04',
    operatorName: 'Abdul Malek',
    operatorId: 'OP-5102',
    operationName: 'Front Fly Zipper Attach & J-Stitch',
    machineType: 'SNLS with Template',
    cycleTimesSec: [29.2, 30.0, 28.8, 29.5, 30.2],
    avgCycleTimeSec: 29.5,
    performanceRatingPercent: 110,
    basicTimeSec: 32.5,
    allowancePercent: 16,
    standardMinuteValue: 2.3,
    status: 'BENCHMARK_EXCEEDED',
    studiedBy: 'Mohiuddin Ahmed (Senior IE)',
  },
];

// Helper functions for localStorage
const BULLETIN_STORAGE_KEY = 'erp_operation_bulletins_v1';
const SCHEDULE_STORAGE_KEY = 'erp_production_schedules_v1';
const TIMESTUDY_STORAGE_KEY = 'erp_time_motion_studies_v1';

export function getStoredBulletins(): StyleOperationBulletin[] {
  if (typeof window === 'undefined') return INITIAL_OPERATION_BULLETINS;
  try {
    const raw = localStorage.getItem(BULLETIN_STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch {
    // ignore
  }
  return INITIAL_OPERATION_BULLETINS;
}

export function saveStoredBulletins(bulletins: StyleOperationBulletin[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(BULLETIN_STORAGE_KEY, JSON.stringify(bulletins));
    localStorage.setItem('erp_module_planning_bulletins', JSON.stringify(bulletins));
    window.dispatchEvent(new Event('erp_bulletins_updated'));
    fetch('/api/modules/planning_bulletins', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ data: bulletins }),
    }).catch(() => {});
  } catch {
    // ignore
  }
}

export function getStoredSchedules(): ProductionPlanSchedule[] {
  if (typeof window === 'undefined') return INITIAL_PRODUCTION_SCHEDULES;
  try {
    const raw = localStorage.getItem('erp_module_planning_schedules') || localStorage.getItem(SCHEDULE_STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch {
    // ignore
  }
  return INITIAL_PRODUCTION_SCHEDULES;
}

export function saveStoredSchedules(schedules: ProductionPlanSchedule[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(SCHEDULE_STORAGE_KEY, JSON.stringify(schedules));
    localStorage.setItem('erp_module_planning_schedules', JSON.stringify(schedules));
    window.dispatchEvent(new Event('erp_schedules_updated'));
    fetch('/api/modules/planning_schedules', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ data: schedules }),
    }).catch(() => {});
  } catch {
    // ignore
  }
}

export function getStoredTimeStudies(): TimeMotionStudy[] {
  if (typeof window === 'undefined') return INITIAL_TIME_STUDIES;
  try {
    const raw = localStorage.getItem('erp_module_planning_timestudies') || localStorage.getItem(TIMESTUDY_STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch {
    // ignore
  }
  return INITIAL_TIME_STUDIES;
}

export function saveStoredTimeStudies(studies: TimeMotionStudy[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(TIMESTUDY_STORAGE_KEY, JSON.stringify(studies));
    localStorage.setItem('erp_module_planning_timestudies', JSON.stringify(studies));
    window.dispatchEvent(new Event('erp_timestudies_updated'));
    fetch('/api/modules/planning_timestudies', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ data: studies }),
    }).catch(() => {});
  } catch {
    // ignore
  }
}

export * from './planning-ie-extended-store';
