import { MeetingMinutesItem } from '@/lib/types/modules';

export const INITIAL_MEETING_MINUTES: MeetingMinutesItem[] = [
  {
    id: 'mtg-001',
    meetingCode: 'MOM-2026-042',
    title: "Pre-Production (PP) Meeting: Style STY-DN-502 Men's Slim Denim Pant",
    meetingDate: '2026-09-22',
    meetingTime: '10:30 AM - 12:00 PM',
    durationMinutes: 90,
    venue: 'Executive Conference Room 1 & Sample Room',
    meetingType: 'PRE_PRODUCTION',
    chairperson: 'Tanzim Ahmed (Head of Quality)',
    scribeName: 'Farhana Akhter (QA Documentation Lead)',
    buyerName: 'H&M Hennes & Mauritz',
    orderPoNumber: 'PO-HM-88219',
    styleNumber: 'STY-DN-502',
    attendeesCount: 9,
    status: 'ACTIONS_PENDING',
    agenda: 'Review pilot sample wash effect, double-needle inseam chainstitch tension, approved size spec tolerances, and broken needle safety protocols for upcoming bulk cutting.',
    discussionNotes: [
      'Pilot run of 120 pcs completed with 2.4% DHU. Needle deflections observed at thick belt loop attachments.',
      'Buyer Technical QC Sarah approved Shade Band #2 with standard enzyme stone tint; Shade Band #3 rejected due to reddish cast.',
      'Double-needle chainstitch feed dog tension adjusted on Line 03 to eliminate puckering at crotch junction.',
      'Metal detector 9-point calibration confirmed with 1.0mm Fe and 1.2mm Non-Fe test cards before bulk packing.',
      'Care label placement standardized at 8.0 cm below waistband inside left pocket bag.'
    ],
    attendees: [
      {
        id: 'att-1',
        name: 'Tanzim Ahmed',
        organization: 'FACTORY',
        department: 'Quality Assurance',
        role: 'Head of Quality / Meeting Chair',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-2',
        name: 'Sarah Jenkins',
        organization: 'BUYER',
        department: 'H&M Technical QA',
        role: 'Buyer Quality Specialist',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-3',
        name: 'Kabir Hossain',
        organization: 'FACTORY',
        department: 'Cutting Department',
        role: 'Chief Cutting Master',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-4',
        name: 'Farhan Rahman',
        organization: 'FACTORY',
        department: 'Merchandising',
        role: 'Senior Merchandiser',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-5',
        name: 'Babul Akter',
        organization: 'FACTORY',
        department: 'Maintenance & Mechanics',
        role: 'Chief Sewing Mechanic',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-6',
        name: 'Mst. Shamima Nasrin',
        organization: 'FACTORY',
        department: 'Sewing Production',
        role: 'Floor In-Charge (Lines 01-04)',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-7',
        name: 'Rashedul Islam',
        organization: 'FACTORY',
        department: 'Physical Testing Lab',
        role: 'Quality Lab In-Charge',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-8',
        name: 'Md. Zahidul Haque',
        organization: 'SUPPLIER',
        department: 'YKK Fasteners Bangladesh',
        role: 'Technical Trims Representative',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-9',
        name: 'Farhana Akhter',
        organization: 'FACTORY',
        department: 'Quality Assurance',
        role: 'Minutes Scribe / QA Coordinator',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
    ],
    actionItems: [
      {
        id: 'act-1',
        task: 'Fit titanium heavy-duty needles (Groz-Beckert 140/22) on Line 03 waistband and belt loop stations',
        assignee: 'Babul Akter (Chief Mechanic)',
        department: 'Maintenance',
        dueDate: '2026-09-24',
        priority: 'HIGH',
        completed: true,
        completedDate: '2026-09-23',
        verificationNotes: 'All 8 waistband machines retrofitted with titanium needles. Verified by Floor QA.',
      },
      {
        id: 'act-2',
        task: 'Issue updated approved shade band swatch card #2 to cutting spreader tables and wash department',
        assignee: 'Rashedul Islam (Lab QA)',
        department: 'Testing Lab',
        dueDate: '2026-09-24',
        priority: 'HIGH',
        completed: true,
        completedDate: '2026-09-24',
        verificationNotes: 'Laminated swatches signed by buyer QC distributed to cutting spread master.',
      },
      {
        id: 'act-3',
        task: 'Calibrate digital button pull-test gauge up to 90N and conduct 10 pcs test on rivet reinforcement',
        assignee: 'Farhana Akhter (QA Documentation)',
        department: 'Quality Assurance',
        dueDate: '2026-09-26',
        priority: 'MEDIUM',
        completed: false,
        verificationNotes: 'Calibration scheduled with Intertek Bangladesh.',
      },
      {
        id: 'act-4',
        task: 'Prepare golden production sample with approved trim placements and display on Line 03 headboard',
        assignee: 'Mst. Shamima Nasrin',
        department: 'Sewing Production',
        dueDate: '2026-09-25',
        priority: 'MEDIUM',
        completed: false,
      },
    ],
    preparedBy: 'Farhana Akhter (QA Documentation Lead)',
    approvedBy: 'Tanzim Ahmed (Head of Quality)',
    targetClosureDate: '2026-09-26',
    createdAt: '2026-09-22',
    updatedAt: '2026-09-24',
  },
  {
    id: 'mtg-002',
    meetingCode: 'MOM-2026-041',
    title: 'Customer Claim CAPA Review: CLM-084 Rib Collar Shade Variance',
    meetingDate: '2026-09-18',
    meetingTime: '02:00 PM - 03:30 PM',
    durationMinutes: 90,
    venue: 'QA Conference Room B',
    meetingType: 'CUSTOMER_CLAIM_CAPA',
    chairperson: 'Tanzim Ahmed (Head of Quality)',
    scribeName: 'Md. Al-Amin (Senior QA Auditor)',
    buyerName: 'Zara / Inditex',
    orderPoNumber: 'PO-ZR-90142',
    styleNumber: 'STY-TS-108',
    attendeesCount: 8,
    status: 'ACTIONS_PENDING',
    agenda: 'Root cause analysis on customer complaint CLM-084 regarding shade variation between body single jersey and 1x1 rib collar in European distribution center.',
    discussionNotes: [
      '5-Why analysis revealed rib knit fabric was dyed in Dyeing Lot #4 while body fabric was sourced from Dyeing Lot #2.',
      'Shade matching under D65 artificial daylight was verified inside factory, but metameric breakdown occurred under TL84 store lighting.',
      'Spectrophotometer Delta-E readings between body and collar showed Delta-E of 1.48 (buyer specification threshold is max 0.80).',
      'Immediate quarantine placed on 4,200 pcs remaining in finished goods warehouse for lot-to-lot re-sorting.'
    ],
    attendees: [
      {
        id: 'att-201',
        name: 'Tanzim Ahmed',
        organization: 'FACTORY',
        department: 'Quality Assurance',
        role: 'Head of Quality / Meeting Chair',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-202',
        name: 'Kamrul Hassan',
        organization: 'FACTORY',
        department: 'Fabric Sourcing & Dyeing',
        role: 'Fabric GM',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-203',
        name: 'Kabir Hossain',
        organization: 'FACTORY',
        department: 'Cutting Department',
        role: 'Chief Cutting Master',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-204',
        name: 'Jahid Chowdhury',
        organization: 'SUPPLIER',
        department: 'Apex Textile Dyeing Mills',
        role: 'Dyeing QA Lead',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-205',
        name: 'Md. Al-Amin',
        organization: 'FACTORY',
        department: 'Quality Assurance',
        role: 'Senior QA Auditor / Scribe',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-206',
        name: 'Monirul Islam',
        organization: 'FACTORY',
        department: 'Finishing & Warehouse',
        role: 'Finishing In-Charge',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
    ],
    actionItems: [
      {
        id: 'act-201',
        task: 'Implement mandatory UV ink stamp on all body and rib cut parts to guarantee 100% same-roll bundling',
        assignee: 'Kabir Hossain (Cutting Master)',
        department: 'Cutting',
        dueDate: '2026-09-20',
        priority: 'HIGH',
        completed: true,
        completedDate: '2026-09-20',
        verificationNotes: 'UV light inspection checkpoints set up at cutting end line.',
      },
      {
        id: 'act-202',
        task: 'Enforce dual light source evaluation (D65 + TL84) in VeriVide light box for all knit-to-rib components',
        assignee: 'Md. Al-Amin (QA Auditor)',
        department: 'Testing Lab',
        dueDate: '2026-09-22',
        priority: 'HIGH',
        completed: true,
        completedDate: '2026-09-22',
        verificationNotes: 'Light cabinet bulbs replaced and certified; SOP-QA-014 updated.',
      },
      {
        id: 'act-203',
        task: 'Re-inspect and spectrophotometer test 4,200 quarantined garments in Finished Goods warehouse',
        assignee: 'Monirul Islam (Finishing In-Charge)',
        department: 'Finishing',
        dueDate: '2026-09-26',
        priority: 'HIGH',
        completed: false,
      },
    ],
    preparedBy: 'Md. Al-Amin (Senior QA Auditor)',
    approvedBy: 'Tanzim Ahmed (Head of Quality)',
    targetClosureDate: '2026-09-26',
    createdAt: '2026-09-18',
    updatedAt: '2026-09-22',
  },
  {
    id: 'mtg-003',
    meetingCode: 'MOM-2026-040',
    title: 'Weekly Quality Assurance & Factory DHU Defect Reduction Review',
    meetingDate: '2026-09-14',
    meetingTime: '09:00 AM - 10:15 AM',
    durationMinutes: 75,
    venue: 'Production Floor Meeting Area Line 06',
    meetingType: 'WEEKLY_QMS',
    chairperson: 'Tanzim Ahmed (Head of Quality)',
    scribeName: 'Farhana Akhter (QA Documentation Lead)',
    buyerName: 'Target USA & C&A Europe',
    orderPoNumber: 'PO-TG-74011',
    styleNumber: 'STY-PL-220',
    attendeesCount: 11,
    status: 'CLOSED',
    agenda: 'Weekly floor defect Pareto analysis. Address high skip-stitch rate on Line 04 flatlock hem operations and puckering on twill collar bands.',
    discussionNotes: [
      'Line 04 weekly DHU decreased from 3.8% to 2.1% after replacing looper thread tensions and installing silicone thread lubricators.',
      'Needle heating caused melted synthetic threads on polyester-blend polo shirts; needle coolers installed on 14 workstations.',
      'End-line inspection 100% check pass rate reached 98.4%, exceeding the factory weekly KPI target of 97.5%.'
    ],
    attendees: [
      {
        id: 'att-301',
        name: 'Tanzim Ahmed',
        organization: 'FACTORY',
        department: 'Quality Assurance',
        role: 'Head of Quality / Meeting Chair',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-302',
        name: 'Babul Akter',
        organization: 'FACTORY',
        department: 'Maintenance & Mechanics',
        role: 'Chief Sewing Mechanic',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-303',
        name: 'Nasrin Sultana',
        organization: 'FACTORY',
        department: 'Sewing Production',
        role: 'Line 04 Supervisor',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-304',
        name: 'Nurul Islam',
        organization: 'FACTORY',
        department: 'Quality Assurance',
        role: 'Line 04 Quality Inspector',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
    ],
    actionItems: [
      {
        id: 'act-301',
        task: 'Fit silicone needle thread lubricators on all Pegasus 5-thread interlock machines on Line 04',
        assignee: 'Babul Akter (Chief Mechanic)',
        department: 'Maintenance',
        dueDate: '2026-09-16',
        priority: 'HIGH',
        completed: true,
        completedDate: '2026-09-15',
        verificationNotes: 'All 12 machines fitted and verified. Skip stitch rate dropped by 80%.',
      },
      {
        id: 'act-302',
        task: 'Conduct 15-minute morning briefing for all line operators regarding collar notch alignment',
        assignee: 'Nasrin Sultana',
        department: 'Sewing Production',
        dueDate: '2026-09-15',
        priority: 'MEDIUM',
        completed: true,
        completedDate: '2026-09-15',
      },
    ],
    preparedBy: 'Farhana Akhter (QA Documentation Lead)',
    approvedBy: 'Tanzim Ahmed (Head of Quality)',
    targetClosureDate: '2026-09-16',
    createdAt: '2026-09-14',
    updatedAt: '2026-09-16',
  },
  {
    id: 'mtg-004',
    meetingCode: 'MOM-2026-039',
    title: 'Needle Safety, Metal Detection & Broken Needle Compliance Audit',
    meetingDate: '2026-09-07',
    meetingTime: '11:00 AM - 12:15 PM',
    durationMinutes: 75,
    venue: 'Needle Control Room & Security Office',
    meetingType: 'NEEDLE_SAFETY',
    chairperson: 'Sarah Jenkins (Quality Governance Lead)',
    scribeName: 'Md. Al-Amin (Senior QA Auditor)',
    buyerName: 'Marks & Spencer / Next UK',
    orderPoNumber: 'PO-MS-60912',
    styleNumber: 'STY-KD-304',
    attendeesCount: 7,
    status: 'CLOSED',
    agenda: 'Audit 100% Lock & Key needle exchange policy, broken needle reconstructive tape register, and conveyor metal detector 9-point calibration logs.',
    discussionNotes: [
      'Needle log book reconciliation: 14 broken needles logged during week 36; all 14 broken pieces successfully reconstituted on sticky tape.',
      'Safeline metal detector sensitivity re-certified: successfully detects 1.0mm Ferrous sphere in all 9 positions of the search head.',
      'Calibration frequency re-confirmed: mandatory check at start of shift, after lunch break, and end of shift.'
    ],
    attendees: [
      {
        id: 'att-401',
        name: 'Sarah Jenkins',
        organization: 'FACTORY',
        department: 'Quality Governance',
        role: 'Governance Lead / Chair',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-402',
        name: 'Md. Delwar Hossain',
        organization: 'FACTORY',
        department: 'Needle Control Room',
        role: 'Needle Controller Officer',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-403',
        name: 'Monirul Islam',
        organization: 'FACTORY',
        department: 'Finishing & Warehouse',
        role: 'Finishing In-Charge',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
    ],
    actionItems: [
      {
        id: 'act-401',
        task: 'Replace lock mechanism on Needle Dispensing Cabinet Station #2',
        assignee: 'Md. Delwar Hossain',
        department: 'Needle Control Room',
        dueDate: '2026-09-09',
        priority: 'HIGH',
        completed: true,
        completedDate: '2026-09-08',
      },
      {
        id: 'act-402',
        task: 'Issue fresh 9-point calibration test cards with NIST traceability certificate to metal detector operator',
        assignee: 'Md. Al-Amin',
        department: 'Quality Assurance',
        dueDate: '2026-09-10',
        priority: 'MEDIUM',
        completed: true,
        completedDate: '2026-09-09',
      },
    ],
    preparedBy: 'Md. Al-Amin (Senior QA Auditor)',
    approvedBy: 'Sarah Jenkins (Quality Governance Lead)',
    targetClosureDate: '2026-09-10',
    createdAt: '2026-09-07',
    updatedAt: '2026-09-09',
  },
  {
    id: 'mtg-005',
    meetingCode: 'MOM-2026-038',
    title: 'Executive Management Review: ISO 9001:2015 & Buyer QMS Performance',
    meetingDate: '2026-08-30',
    meetingTime: '03:00 PM - 05:00 PM',
    durationMinutes: 120,
    venue: 'Boardroom (Head Office Tower)',
    meetingType: 'MANAGEMENT_REVIEW',
    chairperson: 'Engr. M. A. Jalil (Executive Managing Director)',
    scribeName: 'Tanzim Ahmed (Head of Quality)',
    buyerName: 'Enterprise-Wide Governance',
    attendeesCount: 14,
    status: 'CLOSED',
    agenda: 'Semi-annual ISO 9001:2015 management review meeting (Clause 9.3). Assessment of QA objectives, customer satisfaction index, calibration records, and internal audit non-conformances.',
    discussionNotes: [
      'Customer Satisfaction Index scored 92.4% for H1 2026, surpassing the minimum acceptable threshold of 90.0%.',
      'Total factory rework rate decreased by 1.2% year-over-year following the introduction of real-time tablet inspection.',
      'Approved capital expenditure for 2 new automated Gerber pattern cutters to improve cutting precision.'
    ],
    attendees: [
      {
        id: 'att-501',
        name: 'Engr. M. A. Jalil',
        organization: 'FACTORY',
        department: 'Executive Management',
        role: 'Managing Director / Meeting Chair',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
      {
        id: 'att-502',
        name: 'Tanzim Ahmed',
        organization: 'FACTORY',
        department: 'Quality Assurance',
        role: 'Head of Quality / Scribe',
        attendanceStatus: 'PRESENT',
        signatureConfirmed: true,
      },
    ],
    actionItems: [
      {
        id: 'act-501',
        task: 'Publish H2 2026 Quality Policy & Objectives booklet and distribute to all line boards',
        assignee: 'Tanzim Ahmed',
        department: 'Quality Assurance',
        dueDate: '2026-09-15',
        priority: 'MEDIUM',
        completed: true,
        completedDate: '2026-09-12',
      },
    ],
    preparedBy: 'Tanzim Ahmed (Head of Quality)',
    approvedBy: 'Engr. M. A. Jalil (Managing Director)',
    targetClosureDate: '2026-09-15',
    createdAt: '2026-08-30',
    updatedAt: '2026-09-12',
  },
];

export const MEETING_TYPE_LABELS: Record<string, { label: string; badgeClass: string }> = {
  PRE_PRODUCTION: {
    label: 'Pre-Production (PP)',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  BUYER_QUALITY_REVIEW: {
    label: 'Buyer Quality Review',
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-200',
  },
  WEEKLY_QMS: {
    label: 'Weekly QA / DHU Review',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  NEEDLE_SAFETY: {
    label: 'Needle & Metal Detection',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200',
  },
  CUSTOMER_CLAIM_CAPA: {
    label: 'Claim & CAPA Review',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  MANAGEMENT_REVIEW: {
    label: 'ISO Management Review',
    badgeClass: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  },
  INTERNAL_AUDIT: {
    label: 'Internal Audit Review',
    badgeClass: 'bg-cyan-50 text-cyan-700 border-cyan-200',
  },
};
