import { AuditChecklistItem } from '@/lib/types/modules';

/**
 * Complete Official ISO 9001:2015 Audit Questionnaire
 * Total marks: 100
 * Pass threshold: 80 marks (>= 80%)
 */
export const ISO_9001_DEFAULT_CHECKLIST: AuditChecklistItem[] = [
  // ─── CLAUSE 4: CONTEXT OF THE ORGANIZATION ──────────────────────────────────
  {
    id: 'iso-4.1a',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.1a',
    subClauseTitle: 'Context & Strategic Direction',
    question: 'How has the organization determined external and internal issues relevant to its purpose and strategic direction? How do these affect the ability to achieve the intended result of the QMS?',
    guidance: 'Verify SWOT/PESTLE matrix, strategic plans, factory policy alignment, and risk registers.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Annual strategic context analysis documented and reviewed during Q1 Management Review meeting.',
  },
  {
    id: 'iso-4.1b',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.1b',
    subClauseTitle: 'Monitoring & Reviewing Context',
    question: 'How do you monitor and review information about these internal and external issues?',
    guidance: 'Check meeting minutes, KPI reviews, and management updates.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Quarterly review conducted with departmental heads; market trends and labor regulations updated.',
  },
  {
    id: 'iso-4.2a',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.2a',
    subClauseTitle: 'Interested Parties Identification',
    question: 'How have you determined what interested parties are relevant to the QMS? How have you determined what requirements those parties have that are relevant to the QMS? How has impact or potential impact been determined?',
    guidance: 'Review buyer requirements register, statutory & regulatory stakeholder matrix.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Stakeholder expectations matrix covers buyers (H&M, Inditex, PVH), workers, and government bodies.',
  },
  {
    id: 'iso-4.2b',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.2b',
    subClauseTitle: 'Monitoring Interested Parties',
    question: 'How do you monitor and review the information about interested parties and their relevant requirements?',
    guidance: 'Inspect buyer COC updates, legal compliance audit records, and customer feedback logs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Monthly legal compliance and buyer protocol tracker actively monitored by Compliance department.',
  },
  {
    id: 'iso-4.3a',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.3a',
    subClauseTitle: 'Boundaries & Applicability of Scope',
    question: 'How have the boundaries and applicability of the QMS been used to establish the scope of the organization?',
    guidance: 'Verify Quality Manual Section 1 for scope definitions.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Scope defines readymade garments manufacturing spanning cutting, sewing, washing, finishing, and packing.',
  },
  {
    id: 'iso-4.3b',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.3b',
    subClauseTitle: 'Scope Considerations',
    question: 'How have: The external and internal issues; The requirements of relevant interested parties and; The products and services of the organization been considered when determining the scope of the organization?',
    guidance: 'Check documented scope justifications against buyer standards and product range.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Scope considered full garment product lifecycle and buyer technical requirements.',
  },
  {
    id: 'iso-4.3c',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.3c',
    subClauseTitle: 'Application of Standard within Scope',
    question: 'How has the application of the International Standard within the scope been determined, and how has it been applied by the organization?',
    guidance: 'Review clause applicability matrix.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'ISO 9001 standard clauses applied across all operational departments.',
  },
  {
    id: 'iso-4.3d',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.3d',
    subClauseTitle: 'Exclusions & Non-Applicability',
    question: 'How have any requirements of the International Standard been determined as not applicable? Show me how conformity of products and services are not affected by this.',
    guidance: 'Verify justification for non-applicable requirements (e.g. Design 8.3 if build-to-print).',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Design 8.3 tailored to buyer tech pack execution with full pattern & fit sample validation.',
  },
  {
    id: 'iso-4.3e',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.3e',
    subClauseTitle: 'Documented Scope Availability',
    question: 'Where is the scope available? Where is it maintained as documented information? Does it state what products and services are covered by the QMS? Does it justify how instances of requirements of the QMS cannot be applied?',
    guidance: 'Inspect Quality Manual master controlled copy.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Maintained in QM Rev 14, Section 1.2; accessible on factory intranet and QA master binder.',
  },
  {
    id: 'iso-4.4a',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.4a',
    subClauseTitle: 'QMS Establishment & Interaction',
    question: 'How has the QMS been established? Show me how this is implemented. How is it maintained and continually improved? How have the processes been determined and how do they interact?',
    guidance: 'Inspect overall factory process interaction diagram and turtle diagrams.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Macro process flow clearly maps inputs, production stages, inspections, and dispatch.',
  },
  {
    id: 'iso-4.4b',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.4b',
    subClauseTitle: 'Process Operation & Control Criteria',
    question: 'How have the processes been determined for the QMS? What are the inputs and outputs for those processes? What is the sequence and interaction of the processes? What are the criteria, methods, measurement and related performance indicators needed to operate and control those processes? What resources are needed and how are these made available? How are responsibilities and authorities assigned for those processes? How are risks and opportunities considered and what plans are made to implement actions to address them? What methods are used to monitor, measure and evaluate processes and, if needed, what changes are made to achieve intended results? How are opportunities to improve the processes and the QMS determined?',
    guidance: 'Review departmental SOPs, KPI scorecards, and control plans for cutting, sewing, and finishing.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Comprehensive SOPs and KPI targets defined for each line; daily monitoring via ERP dashboard.',
  },
  {
    id: 'iso-4.4c',
    clause: 'Clause 4: Context of the Organization',
    clauseNumber: '4.4c',
    subClauseTitle: 'Process Documented Information',
    question: 'What documented information exists to support the operation of processes? How is this documented information retained? How is confidence that the processes are being carried out as planned determined?',
    guidance: 'Review record retention logs, daily QC report archives, and digital logs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Inspection logs, calibration certs, and test reports retained digitally for a minimum of 3 years.',
  },

  // ─── CLAUSE 5: LEADERSHIP ───────────────────────────────────────────────────
  {
    id: 'iso-5.1.1a',
    clause: 'Clause 5: Leadership',
    clauseNumber: '5.1.1a',
    subClauseTitle: 'Leadership & Commitment',
    question: 'Demonstrate their leadership as it applies to their areas of responsibility. Show me how top management demonstrates leadership and commitment w.r.t. the QMS by taking accountability of the effectiveness of the QMS. How is the quality policy and objectives established for the QMS and how are they compatible with the strategic direction and the organizational context? How is the quality policy communicated within the organization? Show me how this is understood and applied. How are the requirements of the QMS integrated into the business processes? How do you promote awareness of the process approach? How do you ensure that resources needed for the QMS are available? How do you communicate the importance of effective quality management? How do you communicate the importance of conforming to the QMS requirements? How do you ensure that the QMS achieves its intended results? How do you engage, direct and support people to contribute to the effectiveness of the QMS? How do you promote continual improvement? How do you support other relevant management roles to demonstrate leadership in their areas of responsibility?',
    guidance: 'Interview GM / Managing Director; inspect budget allocations, MRM attendance, and QA resource approvals.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Top management leads monthly quality performance reviews and allocated budget for modern QC machinery.',
  },
  {
    id: 'iso-5.1.2a',
    clause: 'Clause 5: Leadership',
    clauseNumber: '5.1.2a',
    subClauseTitle: 'Customer Focus',
    question: 'Show me how top management demonstrates leadership and commitment w.r.t. customer focus ensuring requirements and applicable statutory and regulatory requirements are determined and met. How are risks and opportunities that can affect conformity of products and services determined? How is the ability to enhance customer satisfaction determined and addressed? How is the focus on consistently providing products and services that meet customer and applicable statutory and regulatory requirements maintained? How is customer satisfaction maintained?',
    guidance: 'Review buyer contract review records, customer complaint resolutions, and AQL target achievements.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Customer feedback and buyer scorecard KPIs directly linked to production manager bonuses.',
  },
  {
    id: 'iso-5.2.1a',
    clause: 'Clause 5: Leadership',
    clauseNumber: '5.2.1a',
    subClauseTitle: 'Establishing Quality Policy',
    question: 'How does top management establish, review and maintain a quality policy? How is it determined to be appropriate to the purpose and context of the organization? Does it provide a framework for setting and reviewing quality objectives? Does it contain a commitment to satisfy applicable requirements? Does it include a commitment to continual improvement of the QMS?',
    guidance: 'Review the written Quality Policy signed by Managing Director.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Quality Policy signed by MD; reviewed annually during management review meetings.',
  },
  {
    id: 'iso-5.2.2a',
    clause: 'Clause 5: Leadership',
    clauseNumber: '5.2.2a',
    subClauseTitle: 'Communicating Quality Policy',
    question: 'Where is the quality policy available as documented information? How is it communicated? Show me how it is understood and applied within the organization. How have you made it available to relevant interested parties?',
    guidance: 'Check floor display boards, ID card reverse side, and operator interview understanding.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Policy posted in Bengali and English across factory floors and included in worker induction booklet.',
  },
  {
    id: 'iso-5.3a',
    clause: 'Clause 5: Leadership',
    clauseNumber: '5.3a',
    subClauseTitle: 'Roles, Responsibilities & Authorities',
    question: 'How does top management ensure that responsibilities and authorities for relevant roles are assigned, communicated and understood within the organization?',
    guidance: 'Review factory organogram, job descriptions, and delegation of authority matrix.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Detailed job descriptions and organogram signed by department heads and HR.',
  },
  {
    id: 'iso-5.3b',
    clause: 'Clause 5: Leadership',
    clauseNumber: '5.3b',
    subClauseTitle: 'QMS Conformity & Reporting Authority',
    question: 'How does top management assign the responsibility and authority for: Ensuring that the QMS conforms to the International standard? Ensuring processes are delivering their intended outputs? How is the performance of the QMS, opportunities for improvement and the need for change or innovation reported to top management? How is customer focus promoted within the organization? How is the integrity of the QMS maintained when changes to the QMS are planned and implemented?',
    guidance: 'Verify QA Manager appointment letter and documented authority to stop nonconforming lines.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'QA Manager has documented stop-line authority and reports directly to Executive Director.',
  },

  // ─── CLAUSE 6: PLANNING ─────────────────────────────────────────────────────
  {
    id: 'iso-6.1.1a',
    clause: 'Clause 6: Planning',
    clauseNumber: '6.1.1a',
    subClauseTitle: 'Addressing Risks & Opportunities',
    question: 'How are the internal and external issues and interested parties considered when planning for the QMS? How are risks and opportunities determined and addressed so that the QMS can: a) achieve its intended results; b) Prevent or reduce undesired effects; c) Achieve continual improvement?',
    guidance: 'Review Risk Assessment Matrix, FMEA records, and mitigation plans.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Risk register active with mitigation plans for supply chain delay, broken needles, and color bleeding.',
  },
  {
    id: 'iso-6.1.2a',
    clause: 'Clause 6: Planning',
    clauseNumber: '6.1.2a',
    subClauseTitle: 'Action Planning for Risks',
    question: 'How are actions planned to address risks and opportunities? How are actions integrated and implemented into the QMS processes? How do you evaluate the effectiveness of the actions?',
    guidance: 'Inspect PPM risk evaluation checklist and preventative maintenance plans.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'PPM risk actions integrated into cutting and sewing line setup protocols.',
  },
  {
    id: 'iso-6.1.2b',
    clause: 'Clause 6: Planning',
    clauseNumber: '6.1.2b',
    subClauseTitle: 'Risk Action Proportionality',
    question: 'How are actions taken to address risks and opportunities determined as being appropriate to the potential impact on the conformity of products and services?',
    guidance: 'Review risk rating calculation (Likelihood x Severity).',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Risk severity scoring ensures high-impact items receive priority engineering controls.',
  },
  {
    id: 'iso-6.2.2.1q1a',
    clause: 'Clause 6: Planning',
    clauseNumber: '6.2.2.1q1a',
    subClauseTitle: 'Design Competency & Tooling Skills',
    question: 'The organization shall ensure that personnel with product design responsibility are competent to achieve design requirements and are skilled in applicable tools and techniques. Applicable tools and techniques shall be identified by the organization. How do you determine that personnel with product design responsibility are competent to achieve design requirements? How do you determine skills required in applicable tools and techniques? How do you identify applicable tools and techniques?',
    guidance: 'Review CAD/CAM pattern maker qualifications, sample room master skills assessment.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'CAD pattern makers trained on Lectra/Gerber software with annual competency evaluations.',
  },
  {
    id: 'iso-6.2.1a',
    clause: 'Clause 6: Planning',
    clauseNumber: '6.2.1a',
    subClauseTitle: 'Quality Objectives Deployment',
    question: 'Where are the quality objectives and are these at all relevant functions, levels and processes? Are they consistent with the quality policy? Are they measureable? Do they consider applicable requirements? Are they relevant to the conformity of products and services and do they enhance customer satisfaction? Are they monitored? How? How often? How are they communicated? How are they updated? Where is the documented information on the quality objectives?',
    guidance: 'Check departmental KPI boards for Cutting, Sewing, Finishing, Lab.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Measurable targets (DHU < 3.0%, Cutting wastage < 1.5%, OTD > 98%) displayed on floor whiteboards.',
  },
  {
    id: 'iso-6.2.2a',
    clause: 'Clause 6: Planning',
    clauseNumber: '6.2.2a',
    subClauseTitle: 'Planning Quality Objectives Execution',
    question: 'How does the organization determine what will be done, with what resources, when completed and how will results be evaluated for quality objectives?',
    guidance: 'Inspect monthly Quality Objective Action Plan and progress reviews.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Action plans specify responsible manager, required resources, and target milestones.',
  },
  {
    id: 'iso-6.3a',
    clause: 'Clause 6: Planning',
    clauseNumber: '6.3a',
    subClauseTitle: 'Planning of Changes',
    question: 'How are changes to the QMS planned systematically? Demonstrate the purpose and potential consequences of changes; Demonstrate the integrity of the QMS; Demonstrate how resources are made available? Demonstrate how responsibility and authority is allocated or reallocated.',
    guidance: 'Verify Change Request Form (CRF) records for machine layout and process updates.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Formal Engineering Change Notice (ECN) protocol followed for style technical changes.',
  },

  // ─── CLAUSE 7: SUPPORT ──────────────────────────────────────────────────────
  {
    id: 'iso-7.1.1a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.1a',
    subClauseTitle: 'Resource Determination',
    question: 'Demonstrate how resources are determined for the establishment, implementation, maintenance and continual improvement of the QMS. Show me how the capabilities and constraints on internal resources are considered. Show me how needs from external providers are considered.',
    guidance: 'Review annual budget allocations and resource requisition logs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Management allocates budget for QA lab calibration, certified auditors, and testing consumables.',
  },
  {
    id: 'iso-7.1.2a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.2a',
    subClauseTitle: 'People & Staffing',
    question: 'How do you provide persons necessary to consistently meet customer, applicable statutory and regulatory requirements for the QMS including the necessary processes?',
    guidance: 'Check production man-to-machine ratio and QC inspector allocation per sewing line.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Dedicated roster ensures 2 roving QC inspectors and 1 end-line QC per sewing line.',
  },
  {
    id: 'iso-7.1.3a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.3a',
    subClauseTitle: 'Infrastructure Maintenance',
    question: 'How do you determine, provide and maintain the infrastructure for the operation of processes to achieve products and service conformity?',
    guidance: 'Inspect machinery preventive maintenance logs, backup generators, and compressed air systems.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Preventive maintenance schedule executed weekly; machine maintenance tags up to date.',
  },
  {
    id: 'iso-7.1.4a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.4a',
    subClauseTitle: 'Work Environment & Lighting',
    question: 'How do you determine, provide and maintain the environment for the operation of processes to achieve products and service conformity?',
    guidance: 'Inspect Lux level lighting records (1000 Lux for inspection tables), temperature and humidity logs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Inspection areas verified at >1000 Lux; fabric relaxation room humidity maintained at 65% RH.',
  },
  {
    id: 'iso-7.1.5a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.5a',
    subClauseTitle: 'Monitoring & Measuring Resources',
    question: 'How are the resources determined for ensuring valid and reliable monitoring and measuring results, where used?',
    guidance: 'Check master equipment register (GSM cutter, digital scale, pull gauge, lightbox).',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'All testing devices identified and assigned unique asset tags with calibration schedules.',
  },
  {
    id: 'iso-7.1.5b',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.5b',
    subClauseTitle: 'Fitness for Purpose of Equipment',
    question: 'How do you ensure that resources provided are suitable for the specific monitoring and measurement activities and are maintained to ensure continued fitness for purpose?',
    guidance: 'Inspect daily check logs for metal detectors and pull test gauges.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Daily verification logs signed before start of shift; 9-point metal detector check performed hourly.',
  },
  {
    id: 'iso-7.1.5c',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.5c',
    subClauseTitle: 'Evidence of Fitness (Records)',
    question: 'Show me the documented information which is evidence of fitness for purpose of monitoring and measurement resources.',
    guidance: 'Check calibration certificate files and routine service logs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Calibration certificates maintained digitally in the Calibration Module with zero overdue items.',
    evidencePhotos: [
      {
        id: 'photo-715c-1',
        url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
        caption: 'Master Calibration Certificate & Gauge Verification Record',
        timestamp: '10:45 AM',
      },
      {
        id: 'photo-715c-2',
        url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80',
        caption: 'Digital Micrometer Caliper Physical Verification Seal',
        timestamp: '10:48 AM',
      },
    ],
  },
  {
    id: 'iso-7.1.5d',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.5d',
    subClauseTitle: 'Traceability & Calibration Safeguards',
    question: 'Where applicable, show me how measurement instruments are: Verified or calibrated at specified intervals against national or international measurement standards; If there are no standards, show me the documented information which is used as the basis used for calibration or verification. Show me how measurement instruments are identified to determine their calibration status. Show me how they are safeguarded from adjustments. Show me how they are safeguarded from damage and deterioration.',
    guidance: 'Inspect physical calibration status stickers, tamper-proof seals on scale adjustment screws.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'External calibration done by ISO 17025 accredited labs; tamper-evident seals intact.',
  },
  {
    id: 'iso-7.1.5e',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.5e',
    subClauseTitle: 'Invalid Calibration Impact Assessment',
    question: 'How do you determine the validity of previous measurements if you find an instrument to be defective during verification or calibration? What appropriate actions can you take?',
    guidance: 'Verify Out-of-Calibration SOP and containment recall records.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'SOP mandates re-inspection of all garments produced during the preceding 4 hours if calibration fails.',
  },
  {
    id: 'iso-7.1.6a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.6a',
    subClauseTitle: 'Organizational Knowledge Determination',
    question: 'How do you determine necessary knowledge for the operation of processes? How do you determine necessary knowledge to achieve conformity of products and services?',
    guidance: 'Inspect Garment Construction manuals, defect libraries, and buyer quality guideline binders.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Digital defects library and buyer workmanship standards catalogued in ERP.',
  },
  {
    id: 'iso-7.1.6b',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.6b',
    subClauseTitle: 'Knowledge Maintenance & Sharing',
    question: 'How do you maintain this knowledge and how do you make it available to the extent necessary?',
    guidance: 'Review QA technical library and morning line mock-up board briefings.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Visual mock-up boards and defect sample boards placed at the head of every sewing line.',
  },
  {
    id: 'iso-7.1.6c',
    clause: 'Clause 7: Support',
    clauseNumber: '7.1.6c',
    subClauseTitle: 'Acquiring Emerging Knowledge',
    question: 'How do you consider current knowledge and how do you acquire additional knowledge when addressing changing needs and trends?',
    guidance: 'Verify technical seminars, buyer master class certifications, and machinery maker training.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Technical team attends annual buyer regional QA workshops and automated machine vendor training.',
  },
  {
    id: 'iso-7.2q1a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.2q1a',
    subClauseTitle: 'Personnel Competence & Training Matrix',
    question: 'The organization shall: a) determine the necessary competence of person(s) doing work under its control that affects its quality performance; b) ensure that these persons are competent on the basis of appropriate education, training, or experience; c) where applicable, take actions to acquire the necessary competence, and evaluate the effectiveness of the actions taken; d) retain appropriate documented information as evidence of competence. Show me how: You determine the necessary competence of people doing work under your control that affects quality performance; How do you determine competence on the basis of appropriate education, training or experience? How do you take actions to acquire necessary competence where applicable and how do you evaluate the effectiveness of those actions? Show me documented information where appropriate of competence.',
    guidance: 'Inspect training records, operator skill matrix (traffic light skill levels), and QC certifications.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Skill matrix updated monthly; all QC inspectors passed Farnsworth-Munsell 100 Hue Color Test.',
  },
  {
    id: 'iso-7.3a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.3a',
    subClauseTitle: 'Quality Awareness & Contribution',
    question: 'How are people aware of: The quality policy? Relevant quality objectives? Their contribution to the effectiveness of the QMS? The benefits of improved performance? The implications of not conforming with the QMS requirements?',
    guidance: 'Interview 3 line operators and 2 packing checkers.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Operators interviewed understood customer rejection consequences and daily target contributions.',
  },
  {
    id: 'iso-7.4a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.4a',
    subClauseTitle: 'Internal & External Communications',
    question: 'How do you determine internal and external communications relevant to the QMS? How do you determine: What? When? With Whom? How?',
    guidance: 'Review Communications Matrix and buyer alert notification SOP.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Communication protocol specifies notification channels for buyer comments and critical floor defects.',
  },
  {
    id: 'iso-7.5.1a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.5.1a',
    subClauseTitle: 'Documented Information Extent',
    question: 'What documented information do you have as required by this standard? What documented information do you have as being necessary for the effectiveness of your QMS?',
    guidance: 'Verify Master Document List for Quality Manual, Procedures, Work Instructions, and Forms.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Master document register catalogues 42 operational SOPs and 68 controlled QA formats.',
  },
  {
    id: 'iso-7.5.2a',
    clause: 'Clause 7: Support',
    clauseNumber: '7.5.2a',
    subClauseTitle: 'Document Identification & Approval',
    question: 'Show me that your documented information contains: Identification; Description; In what media format? Show me how the documented information is reviewed and approved for suitability and adequacy.',
    guidance: 'Check document headers for Title, Doc No, Revision No, Effective Date, and Authorizing Signatures.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Standard document headers and approval stamps strictly verified on all floor forms.',
  },

  // ─── CLAUSE 8: OPERATION ────────────────────────────────────────────────────
  {
    id: 'iso-8.1a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.1a',
    subClauseTitle: 'Operational Planning & Process Criteria',
    question: 'How are processes needed to meet requirements for provision of products and services planned, implemented and controlled? How are requirements for products and services determined? How is criteria for processes and acceptance for products and services determined? How are resources determined? How is process control implemented? Show me the documented information that shows confidence in that the processes have been carried out as planned and can demonstrate conformity of products and services.',
    guidance: 'Inspect Production Planning sheets, Pre-Production Meeting (PPM) minutes, and AQL sample plans.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'PPM records verified for all active styles; line setup verified against approved tech pack.',
  },
  {
    id: 'iso-8.1b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.1b',
    subClauseTitle: 'Planning Output Suitability',
    question: 'How have you determined that the output from the planning process is suitable for your operations?',
    guidance: 'Review pilot run (size-set 50 pcs) results prior to bulk cutting.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Pilot run 50-piece audit conducted and signed off by buyer technical assessor prior to bulk release.',
  },
  {
    id: 'iso-8.1c',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.1c',
    subClauseTitle: 'Control of Planned & Unintended Changes',
    question: 'How do you control planned changes? How do you review the consequences of unintended changes? What action is taken to mitigate any adverse effects?',
    guidance: 'Inspect machine changeover logs, trim substitution approvals.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Material substitutions require written buyer concession before cutting.',
  },
  {
    id: 'iso-8.1d',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.1d',
    subClauseTitle: 'Outsourced Process Control',
    question: 'How do you control outsourced processes?',
    guidance: 'Review printing, embroidery, and washing subcontractor audit records.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Dedicated vendor quality inspectors stationed at approved washing and printing subcontractors.',
  },
  {
    id: 'iso-8.2.1a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.2.1a',
    subClauseTitle: 'Customer Communication Channels',
    question: 'What are your processes for communicating with customers? How do you communicate information relating to: Products; Services; Enquiries; Contracts; Order handling; Customer views, perceptions and complaints; Handling or treatment of customer property; Specific requirements for contingency actions?',
    guidance: 'Review merchandising order files and buyer weekly status reports.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Merchandising maintains real-time tracking portals and weekly WIP progress reports for buyers.',
  },
  {
    id: 'iso-8.2.2a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.2.2a',
    subClauseTitle: 'Product Requirements Determination',
    question: 'What is your process to determine the requirements for products and services to be offered to potential customers? How do you establish, implement and maintain this process?',
    guidance: 'Inspect tech pack reviews and capability evaluations.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Contract review protocol evaluates machinery capability and stitch density requirements.',
  },
  {
    id: 'iso-8.2.2b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.2.2b',
    subClauseTitle: 'Regulatory & Claims Compliance',
    question: 'How do you define product and service requirements including statutory and regulatory requirements? How do you ensure that you have the ability to meet the defined requirements and substantiate any claims for your products and services?',
    guidance: 'Verify OEKO-TEX Standard 100, flammability test reports, and organic cotton GOTS certs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'OEKO-TEX and GOTS certificates valid; chemical compliance verified against buyer RSL.',
  },
  {
    id: 'iso-8.2.3a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.2.3a',
    subClauseTitle: 'Customer Requirements Review',
    question: 'How do you review: Customer requirements for delivery and post-delivery? Requirements necessary for customers\' specified or intended use, where known; Additional statutory and regulatory requirements applicable to products and services; Any other contract or order requirements.',
    guidance: 'Inspect purchase order review sheets and merchandising sign-offs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'PO terms, packing ratios, barcode specifications, and ex-factory dates systematically verified.',
  },
  {
    id: 'iso-8.2.3b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.2.3b',
    subClauseTitle: 'Prior Review Commitment',
    question: 'Show me that the review is conducted prior to your commitment to supply products and services to your customers. How do you resolve contract or order requirements which differ from those previously defined?',
    guidance: 'Check buyer contract signature dates vs production planning start.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Factory commitments confirmed only after Technical and Merchandising sign feasibility report.',
  },
  {
    id: 'iso-8.2.3c',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.2.3c',
    subClauseTitle: 'Unwritten Customer Requirements',
    question: 'How do you confirm customer requirements where the customer does not provide a documented statement?',
    guidance: 'Review email confirmations and approved reference physical samples.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Verbal buyer approvals formally documented through written email confirmations.',
  },
  {
    id: 'iso-8.2.3d',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.2.3d',
    subClauseTitle: 'Retaining Review Records',
    question: 'Show me where you retain documented information which describes results of the review including any new or changed requirements.',
    guidance: 'Check Order File archives.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Complete order file archives maintained with revision timestamps in Buyer Order module.',
  },
  {
    id: 'iso-8.2.3e',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.2.3e',
    subClauseTitle: 'Personnel Awareness of Spec Changes',
    question: 'Show me the documented information containing changes to products and services. How do you ensure that relevant personnel are made aware of those changes?',
    guidance: 'Check cutting master and supervisor signed revision acknowledgments.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Revised tech packs stamped "REVISED" and signed by cutting in-charge before spreading.',
  },
  {
    id: 'iso-8.3.1a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.3.1a',
    subClauseTitle: 'Design & Development Process',
    question: 'How do you establish, implement and maintain a design and development process (where detailed requirements of your products and services are not already established or defined by the customer or other parties).',
    guidance: 'Inspect Sample Development Stage Gate protocol.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Prototypes, fit samples, and size-sets developed following structured stage-gate milestones.',
  },
  {
    id: 'iso-8.3.2a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.3.2a',
    subClauseTitle: 'Design Stages & Controls',
    question: 'When determining the stages and control for design and development, show me how you consider: The nature, duration and complexity of the activities; Requirements that specify particular process stages including applicable reviews; Required verification and validation; Responsibilities and authorities; How interfaces are controlled between individuals and parties; The need for involvement of customer and user groups. Show me documented information that confirms design and development requirements have been met.',
    guidance: 'Review Gold Seal sample approvals and pattern grading verification.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Gold Seal samples approved and sealed by buyer technical team with measurement charts.',
  },
  {
    id: 'iso-8.3.3a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.3.3a',
    subClauseTitle: 'Design Inputs Determination',
    question: 'Can you show me how you determine: Requirements essential for the type of products and services being designed and developed, including as applicable: Functional & performance requirements; Statutory and regulatory requirements; Standards or codes of practice where there is a commitment to implement; Internal and external resources needed for the design and development of products and services; Potential consequences of failure; Level of control expected of the design and development process by customers and other relevant parties.',
    guidance: 'Check buyer design packs, fabric shrinkage allowance rules, and seam strength requirements.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Fabric shrinkage and torque tests conducted before pattern cutting to adjust pattern dimensions.',
  },
  {
    id: 'iso-8.3.3b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.3.3b',
    subClauseTitle: 'Resolving Input Conflicts',
    question: 'How do you determine that inputs are adequate, complete and unambiguous for design and development? How do you resolve conflicts among inputs?',
    guidance: 'Inspect design query logs sent to buyer technical designers.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Technical discrepancy log tracked via email with buyer design confirmation.',
  },
  {
    id: 'iso-8.3.4a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.3.4a',
    subClauseTitle: 'Design Verification & Validation',
    question: 'How do controls that are applied to the design and development process ensure: Results achieved by design and development activities are clearly defined? Design and development reviews are conducted as planned? Outputs meet the input requirements by verification/ Validation is conducted to ensure that the resulting products and services are capable of meeting the requirements for the specified application or intended use (when known)?',
    guidance: 'Review wash test reports, shrinkage reports, and fitting mannequin validations.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Wash fastness, pilling, and dimensional stability tested in in-house lab before production.',
  },
  {
    id: 'iso-8.3.5a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.3.5a',
    subClauseTitle: 'Design Outputs Adequacy',
    question: 'How do you ensure that design and development outputs: Meet the input requirements for design and development? Are adequate for the subsequent processes for the provision of products and services? Include or reference monitoring and measuring requirements, and acceptance criteria, as applicable? Ensure products to be produced, or services to be provided, are fit for intended purpose and their safe and proper use?',
    guidance: 'Inspect production specification sheets, bill of materials (BOM), and stitch manuals.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Approved BOM and construction sequence sheets issued to cutting and sewing sections.',
  },
  {
    id: 'iso-8.3.5b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.3.5b',
    subClauseTitle: 'Documented Design Outputs',
    question: 'Show me the documented information which results from the design and development process.',
    guidance: 'Review CAD patterns, tech packs, approved sample comment sheets.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'CAD pattern master files stored on secure network drive with version control.',
  },
  {
    id: 'iso-8.3.6a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.3.6a',
    subClauseTitle: 'Design Changes Control',
    question: 'How do you review, control and identify changes made to the design inputs and outputs during design and development of products and services ensuring no impact on conformity to requirements?',
    guidance: 'Check Sample Revision History sheets.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Pattern adjustments tracked with revision suffixes (e.g. Fit-1, Fit-2, Pre-Prod).',
  },
  {
    id: 'iso-8.3.6b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.3.6b',
    subClauseTitle: 'Documented Design Change Records',
    question: 'Show me the documented information for design and development changes.',
    guidance: 'Inspect change logbooks and buyer email approvals.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Documented approvals from buyer technical manager retained in sample room archives.',
  },
  {
    id: 'iso-8.4.1a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.4.1a',
    subClauseTitle: 'External Providers Conformance',
    question: 'How do you ensure externally provided processes, products and services conform to specified requirements?',
    guidance: 'Inspect Incoming QC (IQC) fabric 4-point inspection and trim test records.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: '100% incoming fabric tested for GSM, shade, and defects under 4-Point System.',
  },
  {
    id: 'iso-8.4.1b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.4.1b',
    subClauseTitle: 'Scope of External Control Application',
    question: 'Show me how you apply specified requirements for the control of externally provided products and services when: Products and services are provided by external providers for incorporation into your own products and services; You provide products and services directly to customers by external providers on your behalf; A process or part-process is provided by an external provider as a result of a decision to outsource a process or function.',
    guidance: 'Check Purchase Orders issued to yarn suppliers, trims vendors, and outsource wash plants.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Subcontract agreements mandate adherence to buyer technical manual and zero-lead zipper trims.',
  },
  {
    id: 'iso-8.4.1c',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.4.1c',
    subClauseTitle: 'Vendor Evaluation & Selection Criteria',
    question: 'Show me how you establish and apply criteria for evaluation, selection, monitoring of performance and re-evaluation of external providers. How do you assess their ability to provide processes or products and services in accordance with specified requirements?',
    guidance: 'Review Approved Vendor List (AVL) and supplier audit scorecards.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Suppliers audited annually using 100-mark evaluation (80 mark pass threshold required).',
  },
  {
    id: 'iso-8.4.1d',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.4.1d',
    subClauseTitle: 'Vendor Evaluation Records',
    question: 'What documented information do you have of the results of evaluations, monitoring of performance and re-evaluations of external providers?',
    guidance: 'Check Supplier Evaluation Files in Sub-Supplier Module.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Records maintained for fabric mills and trim suppliers with monthly on-time delivery ratings.',
  },
  {
    id: 'iso-8.4.2a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.4.2a',
    subClauseTitle: 'Controls on External Providers',
    question: 'How do you determine the controls applied to the external provision of processes, products and services and take into consideration: a) The potential impact of the externally provided processes, products and services on the ability to consistently meet customer and applicable statutory and regulatory requirements? b) The perceived effectiveness of the controls applied by the external provider?',
    guidance: 'Inspect risk-based incoming inspection sampling plans (Level II AQL).',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Critical trims (interlinings, safety snaps) tested 100% for pull strength and bond durability.',
  },
  {
    id: 'iso-8.4.2b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.4.2b',
    subClauseTitle: 'Verification of External Deliveries',
    question: 'What verification or other activities do you have to ensure externally provided processes, products and services do not adversely affect your ability to consistently deliver conforming products and services to your customers?',
    guidance: 'Review Goods Received Note (GRN) quality gate logs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Warehouse quarantine zone ensures materials released to cutting only after QC PASS stamp.',
  },
  {
    id: 'iso-8.4.2c',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.4.2c',
    subClauseTitle: 'Outsourced Function Controls',
    question: 'When processes or functions have been outsourced to external providers, how do you consider a) and b) in 8.4.1 and how do you define the controls intended to be applied to the external provider and to the resulting process output?',
    guidance: 'Inspect embroidery and printing piece-rate inspection sheets.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Printed and embroidered panels inspected 100% prior to sewing line feeding.',
  },
  {
    id: 'iso-8.4.3a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.4.3a',
    subClauseTitle: 'Purchasing Information Communication',
    question: 'Show me how you communicate to external providers, applicable requirements for: Products and services to be provided or the processes to be performed on behalf of the organization; Approval or release of products and services, methods, processes or equipment; Competence of personnel, including necessary qualification; Their interactions with the organization\'s quality management system; The control and monitoring of the external provider\'s performance to be applied by the organization; Verification activities that the organization, or its customer, intends to perform at the external provider\'s premises.',
    guidance: 'Review Purchase Order terms & conditions and technical specifications attached to POs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'POs include exact color Pantone codes, shrinkage limits, and Oeko-Tex certification clauses.',
  },
  {
    id: 'iso-8.5.1a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.1a',
    subClauseTitle: 'Controlled Production Conditions',
    question: 'What controlled conditions do you have for production and service provision, including delivery and post-delivery activities?',
    guidance: 'Check sewing line layout sheets, machinery setup parameters, and approved production samples.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Production line setups validated by industrial engineering and QA supervisors.',
  },
  {
    id: 'iso-8.5.1b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.1b',
    subClauseTitle: 'Operational Criteria & Equipment Controls',
    question: 'Can you show me controlled conditions for: a) the availability of documented information defining the characteristics of the products and services; b) the availability of documented information defining the activities to be performed and the results to be achieved; c) monitoring and measurement activities at appropriate stages to verify that criteria for control of processes and process outputs, and acceptance criteria for products and services, have been met. d) the use, and control of suitable infrastructure and process environment; e) the availability and use of suitable monitoring and measuring resources; f) the competence and, where applicable, required qualification of persons; g) the validation, and periodic revalidation, of the ability to achieve planned results of any process for production and service provision where the resulting output cannot be verified by subsequent monitoring or measurement; h) the implementation of products and services release, delivery and post-delivery activities.',
    guidance: 'Inspect inline inspection sheets, fusing press temperature/pressure test strips, and needle logs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Fusing peel strength tested every 2 hours; inline roving audits conduct 7-piece checks.',
  },
  {
    id: 'iso-8.5.2a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.2a',
    subClauseTitle: 'Identification of Process Outputs',
    question: 'What means do you use to identify process outputs to ensure conformity of products and services?',
    guidance: 'Check bundle cards, cut lot numbering, and fabric roll shade tags.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Bundle ticket system ensures every panel carries cut number, bundle ID, and size sequence.',
  },
  {
    id: 'iso-8.5.2b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.2b',
    subClauseTitle: 'Status Identification Throughout Production',
    question: 'How do you identify the status of process outputs?',
    guidance: 'Inspect color-coded status stickers: Red (Defect), Green (Pass), Yellow (Rework).',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Defective garments tagged with red arrow stickers pointing to exact flaw location.',
  },
  {
    id: 'iso-8.5.2c',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.2c',
    subClauseTitle: 'Unique Traceability Records',
    question: 'How do you control the unique identification of process outputs, where applicable? What documented information do you retain?',
    guidance: 'Verify traceability from carton barcode back to sewing line, operator, and fabric roll batch.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Full backward traceability demonstrated from finished carton to specific knitted yarn lot.',
  },
  {
    id: 'iso-8.5.3a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.3a',
    subClauseTitle: 'Customer / Provider Property Safeguarding',
    question: 'What care do you provide for customer or external provider\'s property while under your control? How do you identify, verify, protect and safeguard that property which is provided for use or incorporation into your products or services?',
    guidance: 'Inspect buyer supplied hanger, label, and barcode sticker storage room.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Buyer-supplied labels stored in locked security cage with inventory reconciliation ledger.',
  },
  {
    id: 'iso-8.5.3b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.3b',
    subClauseTitle: 'Reporting Damaged Customer Property',
    question: 'What means do you use to report to the customer or external provider if their property is incorrectly used, lost, damaged or found to be unsuitable for use?',
    guidance: 'Review Buyer Property Damage Notification log.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Immediate email notification sent to buyer merchandiser with photo proof if trims damaged in transit.',
  },
  {
    id: 'iso-8.5.4a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.4a',
    subClauseTitle: 'Preservation of Outputs',
    question: 'How do you ensure preservation of process outputs during production and service provision to maintain conformity to product requirements?',
    guidance: 'Inspect polybag packing, silica gel desiccant bags, and warehouse carton stacking limits.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Cartons stacked on pallets with shrink wrap; maximum 6 tiers height respected.',
  },
  {
    id: 'iso-8.5.5a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.5a',
    subClauseTitle: 'Post-Delivery Obligations',
    question: 'How do you meet requirements for post-delivery activities associated with products and services?',
    guidance: 'Review customer claim warranty handling and shipment feedback files.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Technical team provides 90-day post-delivery technical support and root-cause analysis on chargebacks.',
  },
  {
    id: 'iso-8.5.5b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.5b',
    subClauseTitle: 'Post-Delivery Risk Factors',
    question: 'How do you determine: Risk; Nature, use and intended lifetime; Customer feedback; Statutory and Regulatory requirements, when determining the extent of post-delivery activities required with products and services?',
    guidance: 'Review buyer vendor compliance manuals.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Post-delivery risk evaluated against consumer safety standards (e.g. drawstring strangulation hazard).',
  },
  {
    id: 'iso-8.5.6a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.6a',
    subClauseTitle: 'Review of Unplanned Changes',
    question: 'How do you review and control unplanned changes to ensure continuing conformity with specified requirements?',
    guidance: 'Inspect machine breakdown emergency rerouting protocol.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Line balancing protocol applied if operator absent; backup operators certified on identical stitch operations.',
  },
  {
    id: 'iso-8.5.6b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.5.6b',
    subClauseTitle: 'Documented Change Authorizations',
    question: 'What documented information can you show me which describes the results of reviews of changes, the personnel authorizing change and any necessary actions?',
    guidance: 'Verify Production Change Order (PCO) signatures.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'PCO signed by Production GM and QA Manager before executing layout modifications.',
  },
  {
    id: 'iso-8.6a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.6a',
    subClauseTitle: 'Release of Products & Services Verification',
    question: 'Show me how planned arrangement have been implemented at appropriate stages to verify product and service requirements have been met. Show me what evidence you retain.',
    guidance: 'Inspect Final Inspection Reports (FIR) and AQL 1.5/2.5 inspection certificates.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Final AQL inspection conducted by buyer-certified QA; 100% carton drop test verified.',
    evidencePhotos: [
      {
        id: 'photo-86a-1',
        url: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=600&q=80',
        caption: 'Garment Finishing & AQL 2.5 Audit Inspection Table Verification',
        timestamp: '02:15 PM',
      },
      {
        id: 'photo-86a-2',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
        caption: 'Warehouse Shipping Lot Inspection & Carton Barcode Verification',
        timestamp: '02:30 PM',
      },
    ],
  },
  {
    id: 'iso-8.6b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.6b',
    subClauseTitle: 'Traceability of Release Authorization',
    question: 'Show me how the release of products and services is held until planned arrangements for verification of conformity have been satisfactorily completed, unless approved by a relevant authority, or the customer if applicable. Show me documented information which shows traceability to the person authorizing release of products and services.',
    guidance: 'Inspect QA Inspection Certificate stamp on packing list prior to container loading.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Security gate pass issued only upon presentation of signed Final QA Release Certificate.',
  },
  {
    id: 'iso-8.7a',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.7a',
    subClauseTitle: 'Control of Nonconforming Outputs',
    question: 'How do you identify and control process outputs, products and services that do not conform to requirements and prevent their unintended use or delivery?',
    guidance: 'Inspect Rejection Bins and Red Tag quarantine area on finishing floor.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Defective garments placed in locked red bins; rejected cartons segregated in fenced quarantine zone.',
  },
  {
    id: 'iso-8.7b',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.7b',
    subClauseTitle: 'Corrective Action Proportionality on Nonconformity',
    question: 'What appropriate corrective actions are taken based on the nature of the nonconformity and its impact on the conformity of products and services? How do you apply this to nonconformity detected after delivery?',
    guidance: 'Check CAPA logs for sewing defects (e.g. broken stitches, oil stains).',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Spot cleaning protocols strictly controlled; oil contaminated garments quarantined for wash test.',
  },
  {
    id: 'iso-8.7c',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.7c',
    subClauseTitle: 'Handling Nonconforming Outputs',
    question: 'How you deal with nonconforming process outputs, products and services in terms of: Correction; Segregation, containment, return or suspension of provision of products and services? Informing the customer? Obtaining authorization for use as-is? Release, continuation or re-provision of the products and service? Acceptance under concession?',
    guidance: 'Review Concession Authorization log.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Garments accepted as B-grade sold to local market only with buyer brand labels completely removed.',
  },
  {
    id: 'iso-8.7d',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.7d',
    subClauseTitle: 'Verification After Correction',
    question: 'are corrected, conformity to the requirements shall be verified. How do you verify conformance where process outputs, products and services are corrected following nonconformance?',
    guidance: 'Inspect Rework Re-inspection records.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: '100% of reworked garments re-inspected and re-passed through metal detector before packing.',
  },
  {
    id: 'iso-8.7e',
    clause: 'Clause 8: Operation',
    clauseNumber: '8.7e',
    subClauseTitle: 'Retaining Nonconformance Records',
    question: 'What documented information do you keep following actions taken to address nonconformities, including any concessions obtained and on the person or authority that made the decision regarding dealing with the nonconformance.',
    guidance: 'Check Defect & Scrap Logbook.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Daily defect records logged in ERP with defect Pareto analysis reviewed in daily QA huddle.',
  },

  // ─── CLAUSE 9: PERFORMANCE EVALUATION ───────────────────────────────────────
  {
    id: 'iso-9.1.1a',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.1.1a',
    subClauseTitle: 'Determining Monitoring & Measurement Needs',
    question: 'Show me how you determine: What needs to be monitored and measured? Methods for monitoring, measurement, analysis and evaluation to ensure valid results? When to perform monitoring and measuring? When results shall be analysed and evaluated?',
    guidance: 'Inspect QA Inspection Plan and QC frequency matrix.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Quality plan details inspection points at fabric inward, cutting, sewing, finishing, and carton packing.',
  },
  {
    id: 'iso-9.1.1b',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.1.1b',
    subClauseTitle: 'Documented Measurement Activities',
    question: 'What documented information can you show me that monitoring and measurement activities have been implemented in accordance with determined requirements?',
    guidance: 'Review hourly DHU tracking charts on production lines.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Hourly inspection sheets filled out by line QC inspectors with defect tally counts.',
  },
  {
    id: 'iso-9.1.1c',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.1.1c',
    subClauseTitle: 'Evaluating QMS Quality Performance',
    question: 'Show me how you evaluate the quality performance and the effectiveness of the QMS.',
    guidance: 'Inspect monthly QA Dashboard and executive quality KPI reviews.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Factory QMS performance evaluated monthly against RFT, DHU, and buyer inspection pass rate.',
  },
  {
    id: 'iso-9.1.2a',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.1.2a',
    subClauseTitle: 'Customer Perception Monitoring',
    question: 'How do you monitor customer perception of the degree to which requirements have been met?',
    guidance: 'Check buyer scorecard rankings (Gold/Silver status) and quarterly customer ratings.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Buyer performance scorecards reviewed quarterly; current factory status rated Gold Tier.',
  },
  {
    id: 'iso-9.1.2b',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.1.2b',
    subClauseTitle: 'Obtaining Customer Feedback',
    question: 'How do you obtain information relating to customer views and opinions of your products and services?',
    guidance: 'Inspect buyer technical feedback emails and customer survey questionnaires.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Annual buyer satisfaction survey sent to all buyer regional technical directors.',
  },
  {
    id: 'iso-9.1.2c',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.1.2c',
    subClauseTitle: 'Methods for Using Customer Feedback',
    question: 'What methods for obtaining and using this information do you have?',
    guidance: 'Review feedback agenda items in Management Review Meetings.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Customer suggestions analyzed and translated into technical process improvement projects.',
  },
  {
    id: 'iso-9.1.3a',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.1.3a',
    subClauseTitle: 'Analysis & Evaluation Usage',
    question: 'Show me how the output of analysis and evaluation is used to: Demonstrate conformity of products and services to requirements? Assess and enhance customer satisfaction? Ensure conformity and effectiveness of the QMS? Demonstrate that planning has been successfully implemented? Assess process performance? Assess performance of external providers? Determine the need or opportunities for improvements within the QMS?',
    guidance: 'Inspect statistical Pareto charts, trend analysis of sewing rejects, and vendor scorecards.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Defect trends analyzed by style and fabric type; preventive actions assigned to mechanics.',
  },
  {
    id: 'iso-9.1.3b',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.1.3b',
    subClauseTitle: 'Inputs to Management Review',
    question: 'Show me where the results of analysis and evaluation are used to provide inputs to management review.',
    guidance: 'Check MRM presentation decks and analysis charts.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Aggregated KPI trends presented as mandatory agenda items during bi-annual MRM.',
  },
  {
    id: 'iso-9.2.1a',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.2.1a',
    subClauseTitle: 'Internal Audit Program Execution',
    question: 'Are internal audits being conducted at planned intervals? Do they determine whether the QMS conforms to the requirements of ISO 9001 and to the other requirements established by Organization? (Review records to demonstrate conformance) Do they determine whether the QMS is effectively implemented and maintained? (Review records)',
    guidance: 'Review annual Internal Audit Schedule and completed audit report archives.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Internal audit schedule executed bi-annually; all clauses and departments covered systematically.',
  },
  {
    id: 'iso-9.2.2a',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.2.2a',
    subClauseTitle: 'Audit Programme Governance & Impartiality',
    question: 'Can you show me audit programme(s) that takes into consideration the quality objectives, importance of the processes, customer feedback, changes impacting the organization and the results of previous audits? Where are the audit criteria and scope for each audit? Can you demonstrate that selection of auditors and the conduct of audits are objective and impartial and that auditors don\'t audit their own work? How are audit results reported to relevant management? Can you demonstrate that necessary correction and corrective actions are taken without undue delay? Can you show me documented information of the audit programme and the audit results?',
    guidance: 'Verify Lead Auditor training certificates and cross-department audit assignments.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Auditors are certified and cross-audit departments outside their operational line of reporting.',
  },
  {
    id: 'iso-9.3.1a',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.3.1a',
    subClauseTitle: 'Management Review Frequency',
    question: 'What is the frequency that top management reviews the organization\'s QMS? How is the QMS deemed suitable, adequate and effective?',
    guidance: 'Inspect Management Review Meeting schedule.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'MRM conducted twice a year; chaired by Managing Director with full executive committee.',
  },
  {
    id: 'iso-9.3.1b',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.3.1b',
    subClauseTitle: 'Management Review Inputs Comprehensive Check',
    question: 'What kinds of information are reviewed in management reviews? These must include: action status of previous reviews; changes to internal/external issues relevant to the QMS; issues that affect strategy; KPIs for nonconformities and corrective actions; monitor and measurement of results; audit results; customer satisfaction; issues concerning external providers; issues concerning other relevant parties; adequacy of resources and effectiveness of QMS; process performance; conformity of products and services; actions taken to address risks and opportunities and their effectiveness; new potential opportunities for continual improvement.',
    guidance: 'Check MRM agenda to confirm all 12 mandatory ISO 9001:2015 inputs are covered.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'All 12 mandatory inputs verified in June 2026 MRM minutes with documented action owners.',
  },
  {
    id: 'iso-9.3.2a',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.3.2a',
    subClauseTitle: 'Management Review Outputs & Decisions',
    question: 'Show me that management reviews include decisions and actions relating to: Continual improvement opportunities; The need for changes to the QMS including resource needs.',
    guidance: 'Review MRM Action Tracker and budget approval sign-offs.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Decisions recorded with assigned deadlines; resource approvals included automatic fabric spreader.',
  },
  {
    id: 'iso-9.3.2b',
    clause: 'Clause 9: Performance Evaluation',
    clauseNumber: '9.3.2b',
    subClauseTitle: 'Documented Evidence of MRM',
    question: 'Show me what documented information you have as evidence of management reviews.',
    guidance: 'Inspect signed MRM Minutes file.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Signed MRM minutes file with attendance sheet retained in Document Control center.',
  },

  // ─── CLAUSE 10: IMPROVEMENT ─────────────────────────────────────────────────
  {
    id: 'iso-10.1a',
    clause: 'Clause 10: Improvement',
    clauseNumber: '10.1a',
    subClauseTitle: 'Determining Opportunities for Improvement',
    question: 'How do you determine and select opportunities for improvement? What necessary actions have you implemented so that you have met customer requirements and enhanced customer satisfaction?',
    guidance: 'Review Kaizen project register and lean manufacturing suggestions.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Continuous improvement suggestion scheme actively operated with monthly worker rewards.',
  },
  {
    id: 'iso-10.1b',
    clause: 'Clause 10: Improvement',
    clauseNumber: '10.1b',
    subClauseTitle: 'Process & Product Enhancement',
    question: 'Show me how you have: Improved processes to prevent nonconformities; Improved products and services to meet known and predicted requirements; Improved QMS results.',
    guidance: 'Inspect automated template sewing attachments and poke-yoke guides.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Installed automatic collar and cuff folding templates, reducing seam puckering by 42%.',
  },
  {
    id: 'iso-10.2.1a',
    clause: 'Clause 10: Improvement',
    clauseNumber: '10.2.1a',
    subClauseTitle: 'Nonconformity Response & CAPA Process',
    question: 'When nonconformities occur, show me how; You react; Take action to control and correct it; Deal with the consequences; Evaluate the need for action to eliminate the cause so that it does not recur or occur elsewhere by: Reviewing the nonconformity; Determining the cause of the nonconformity; Determining if similar nonconformities exist or could potentially occur; Actions needed are implemented; Review the effectiveness of corrective actions taken, if any; Make necessary changes to the QMS.',
    guidance: 'Review 3 verified CAPA reports with 5-Whys root cause analysis.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'CAPA registry verified; root cause investigated using 5-Whys and Fishbone diagram methodology.',
  },
  {
    id: 'iso-10.2.1b',
    clause: 'Clause 10: Improvement',
    clauseNumber: '10.2.1b',
    subClauseTitle: 'Corrective Action Proportionality',
    question: 'Show me how correction actions were appropriate to the effects of the nonconformities encountered.',
    guidance: 'Check containment actions speed vs recurrence rate.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Containment actions initiated within 2 hours; preventive tooling changes implemented.',
  },
  {
    id: 'iso-10.2.2a',
    clause: 'Clause 10: Improvement',
    clauseNumber: '10.2.2a',
    subClauseTitle: 'Retaining CAPA Documented Evidence',
    question: 'What documented information can you show me as evidence of: The nature of the nonconformities and subsequent actions taken; The results of any corrective action.',
    guidance: 'Check closed CAPA records with QA Manager verification signatures.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'CAPA files archived with closure audit sign-off 30 days after implementation.',
  },
  {
    id: 'iso-10.3a',
    clause: 'Clause 10: Improvement',
    clauseNumber: '10.3a',
    subClauseTitle: 'Continual Improvement of QMS',
    question: 'Demonstrate that you continually improve the suitability, adequacy and effectiveness of the QMS.',
    guidance: 'Review annual QMS audit performance trends (year-over-year score improvements).',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Year-over-year audit performance improved from 91.2% in 2024 to 96.8% in 2026.',
  },
  {
    id: 'iso-10.3b',
    clause: 'Clause 10: Improvement',
    clauseNumber: '10.3b',
    subClauseTitle: 'Addressing Underperformance Areas',
    question: 'Demonstrate that outputs of analysis and evaluation and the outputs from management review are considered to confirm if there are areas of underperformance or opportunities that shall be addressed as part of continual improvement.',
    guidance: 'Check target action plans for underperforming production lines.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: 'Underperforming lines receive targeted operator retraining and dedicated senior mechanics.',
  },
  {
    id: 'iso-10.3c',
    clause: 'Clause 10: Improvement',
    clauseNumber: '10.3c',
    subClauseTitle: 'Tools & Methodologies for Continual Improvement',
    question: 'What applicable tools and methodologies for investigation of the causes of underperformance and to support continual improvement are selected?',
    guidance: 'Verify 5S audit logs, Pareto defect analysis, 5-Whys, and Kaizen action registers.',
    status: 'CONFORMITY',
    maxScore: 1,
    score: 1,
    remark: '5S visual management, Pareto defect ranking, and 5-Whys root cause analysis standard across all lines.',
  },
];

/**
 * Normalized 100-mark scoring engine:
 * Total Marks: 100
 * Pass Threshold: 80 Marks (80%)
 * Scoring Rules:
 *  - Conformity  → 100% of question marks
 *  - Minor NC    → 75% of question marks
 *  - Major NC    → 50% of question marks
 *  - Critical NC → 0% of question marks
 *  - N/A         → Excluded from calculation (omitted from applicable pool)
 *  - Critical Failure Rule: If 1 Critical NC is found → Audit Fail immediately!
 */
export function calculateAuditScore(checklist: AuditChecklistItem[]): {
  totalMarks: number;
  obtainedMarks: number;
  scorePercentage: number;
  isPassed: boolean;
  hasCriticalFail: boolean;
  conformityCount: number;
  minorNcCount: number;
  majorNcCount: number;
  criticalNcCount: number;
  nonConformityCount: number;
  naCount: number;
  unansweredCount: number;
} {
  const totalAvailableMarks = 100;
  let conformityCount = 0;
  let minorNcCount = 0;
  let majorNcCount = 0;
  let criticalNcCount = 0;
  let naCount = 0;
  let unansweredCount = 0;

  let totalApplicableMax = 0;
  let earnedScore = 0;

  checklist.forEach((item) => {
    const weight = item.maxScore || 1;
    if (item.status === 'CONFORMITY') {
      conformityCount++;
      totalApplicableMax += weight;
      earnedScore += weight * 1.0; // 100% of question marks
    } else if (item.status === 'MINOR_NC') {
      minorNcCount++;
      totalApplicableMax += weight;
      earnedScore += weight * 0.75; // 75% of question marks
    } else if (item.status === 'MAJOR_NC') {
      majorNcCount++;
      totalApplicableMax += weight;
      earnedScore += weight * 0.50; // 50% of question marks
    } else if (item.status === 'CRITICAL_NC') {
      criticalNcCount++;
      totalApplicableMax += weight;
      earnedScore += 0; // 0% of question marks
    } else if (item.status === 'NON_CONFORMITY') {
      // Legacy compatibility: treated as Minor NC
      minorNcCount++;
      totalApplicableMax += weight;
      earnedScore += weight * 0.75;
    } else if (item.status === 'NA') {
      naCount++;
      // Excluded from calculation: does not add to totalApplicableMax nor earnedScore
    } else {
      unansweredCount++;
      totalApplicableMax += weight;
    }
  });

  const scorePercentage =
    totalApplicableMax > 0
      ? Number(((earnedScore / totalApplicableMax) * 100).toFixed(1))
      : 100;

  const obtainedMarks = Number(((scorePercentage / 100) * totalAvailableMarks).toFixed(1));
  const hasCriticalFail = criticalNcCount > 0;
  // If 1 Critical NC found -> Audit Fail regardless of score!
  const isPassed = !hasCriticalFail && obtainedMarks >= 80;
  const nonConformityCount = minorNcCount + majorNcCount + criticalNcCount;

  return {
    totalMarks: totalAvailableMarks,
    obtainedMarks,
    scorePercentage,
    isPassed,
    hasCriticalFail,
    conformityCount,
    minorNcCount,
    majorNcCount,
    criticalNcCount,
    nonConformityCount,
    naCount,
    unansweredCount,
  };
}

/**
 * Intelligent parser to parse raw question texts into structured AuditChecklistItems
 */
export function parseQuestionsFromText(text: string): AuditChecklistItem[] {
  if (!text || !text.trim()) return [];
  const lines = text.split('\n').map((l) => l.trim()).filter(Boolean);
  const items: AuditChecklistItem[] = [];
  let current: AuditChecklistItem | null = null;

  for (const line of lines) {
    const match = line.match(/^([0-9\.]+[a-z0-9]*)\s+(.*)/i);
    if (match) {
      if (current) items.push(current);
      const clauseNum = match[1].trim();
      const qText = match[2].trim();
      const major = parseInt(clauseNum.split('.')[0], 10);
      let clauseTitle = 'Clause ' + major;
      if (major === 4) clauseTitle = 'Clause 4: Context of the Organization';
      else if (major === 5) clauseTitle = 'Clause 5: Leadership';
      else if (major === 6) clauseTitle = 'Clause 6: Planning';
      else if (major === 7) clauseTitle = 'Clause 7: Support';
      else if (major === 8) clauseTitle = 'Clause 8: Operation';
      else if (major === 9) clauseTitle = 'Clause 9: Performance Evaluation';
      else if (major === 10) clauseTitle = 'Clause 10: Improvement';
      else clauseTitle = 'Custom Verification Clause';

      current = {
        id: `imported-${clauseNum.replace(/[^a-zA-Z0-9]/g, '-')}-${Date.now().toString().slice(-4)}`,
        clause: clauseTitle,
        clauseNumber: clauseNum,
        subClauseTitle: `Section ${clauseNum} Requirement`,
        question: qText,
        guidance: 'Verify operational documented evidence, SOP registers, and compliance logs.',
        status: 'CONFORMITY',
        maxScore: 1,
        score: 1,
        remark: 'Documented evidence and physical implementation verified.',
        evidencePhotos: [],
      };
    } else if (current) {
      current.question += ' ' + line;
    }
  }
  if (current) items.push(current);
  return items;
}

