import {
  TrainingMatrixItem,
  TrainingExamPaper,
  TrainingEvaluationRecord,
  TrainingAttendee,
  AnnualTrainingScheduleItem,
} from '@/lib/types/modules';

export const INITIAL_TRAINING_COURSES: TrainingMatrixItem[] = [
  {
    id: 'trn-1',
    courseCode: 'TRN-NDL-01',
    title: '9-Point Broken Needle Policy & Metal Contamination Prevention',
    category: 'SAFETY_COMPLIANCE',
    department: 'Sewing & Finishing',
    targetAudience: 'Sewing Operators, Line Supervisors, Metal Detector Operators',
    trainerName: 'Engr. Tariqul Islam & Kamal Hossain',
    frequency: 'MONTHLY',
    durationHours: 3.5,
    venue: 'Training Hall A (Floor 2)',
    maxCapacity: 45,
    trainedCount: 240,
    passRatePercent: 98.5,
    nextScheduledDate: '2026-10-05',
    status: 'SCHEDULED',
    isoClause: 'ISO 9001:2015 Clause 8.5.1 & 7.2',
    prerequisites: 'Basic sewing machine operation orientation',
    syllabusTopics: [
      'Understanding buyer metal-free apparel mandates and safety hazards',
      '9-point broken needle recovery protocol: mandatory 100% fragment matching',
      'Red lockbox quarantine procedure and supervisor sign-off',
      'Conveyor tunnel metal detector 1.0mm ferrous test card hourly calibration',
      'Handheld magnetic wand scanning techniques for alarmed garments',
    ],
    examCode: 'EXAM-NDL-01',
    examPaperId: 'exam-1',
    attendees: [
      {
        id: 'att-101',
        employeeId: 'EMP-2022-0481',
        name: 'Nasrin Sultana',
        department: 'Sewing Production',
        designation: 'Senior Sewing Operator',
        attendanceStatus: 'PRESENT',
        preTestScore: 65,
        postTestScore: 95,
        practicalScore: 98,
        finalScore: 96,
        result: 'PASSED',
        certificateNo: 'CERT-NDL-2026-081',
        remarks: 'Excellent practical recovery demonstration on locked needle board.',
      },
      {
        id: 'att-102',
        employeeId: 'EMP-2023-0192',
        name: 'Abdur Rahim',
        department: 'Sewing Production',
        designation: 'Line 4 Supervisor',
        attendanceStatus: 'PRESENT',
        preTestScore: 70,
        postTestScore: 100,
        practicalScore: 95,
        finalScore: 98,
        result: 'PASSED',
        certificateNo: 'CERT-NDL-2026-082',
        remarks: 'Mastered line-stop trigger and quarantine box documentation.',
      },
      {
        id: 'att-103',
        employeeId: 'EMP-2024-0044',
        name: 'Fatema Khatun',
        department: 'Finishing & Packing',
        designation: 'Metal Detector Operator',
        attendanceStatus: 'PRESENT',
        preTestScore: 60,
        postTestScore: 90,
        practicalScore: 92,
        finalScore: 91,
        result: 'PASSED',
        certificateNo: 'CERT-NDL-2026-083',
        remarks: 'Accurately demonstrated 9-zone calibration check with 1.0mm Fe card.',
      },
    ],
    notes: 'Mandatory certification course for all operators working on childrenswear and European export lines.',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'trn-2',
    courseCode: 'TRN-FAB-02',
    title: 'ASTM D5430 4-Point System Fabric Inspection & Defect Grading',
    category: 'TECHNICAL_QMS',
    department: 'Fabric Warehouse & Lab',
    targetAudience: 'Fabric Warehouse Quality Inspectors, Lab Technicians',
    trainerName: 'Farida Yasmin (Lab Manager)',
    frequency: 'QUARTERLY',
    durationHours: 6.0,
    venue: 'Central Fabric Laboratory',
    maxCapacity: 25,
    trainedCount: 85,
    passRatePercent: 96.0,
    nextScheduledDate: '2026-10-12',
    status: 'SCHEDULED',
    isoClause: 'ISO 9001:2015 Clause 8.4.3 & 8.6',
    prerequisites: 'Munsell 100 Hue color vision test pass certificate',
    syllabusTopics: [
      'Standard inspection lighting parameters (D65 light source, 1000 Lux)',
      'Penalty point assignment criteria based on defect length (1 to 4 points)',
      'Calculating total penalty points per 100 square yards',
      'Roll acceptance threshold (maximum 28 points) and quarantine protocol',
      'Continuous running defects and automatic roll rejection rules',
      'Shade variation assessment using Grey Scale for color change',
    ],
    examCode: 'EXAM-FAB-01',
    examPaperId: 'exam-2',
    attendees: [
      {
        id: 'att-201',
        employeeId: 'EMP-2021-0310',
        name: 'Mizanur Rahman',
        department: 'Fabric Warehouse',
        designation: 'Senior Fabric Inspector',
        attendanceStatus: 'PRESENT',
        preTestScore: 75,
        postTestScore: 96,
        practicalScore: 94,
        finalScore: 95,
        result: 'PASSED',
        certificateNo: 'CERT-FAB-2026-033',
        remarks: 'Accurate penalty calculation on high-density knit spandex rolls.',
      },
      {
        id: 'att-202',
        employeeId: 'EMP-2023-0871',
        name: 'Sultana Parveen',
        department: 'Fabric Warehouse',
        designation: 'Fabric QC Inspector',
        attendanceStatus: 'PRESENT',
        preTestScore: 68,
        postTestScore: 92,
        practicalScore: 90,
        finalScore: 91,
        result: 'PASSED',
        certificateNo: 'CERT-FAB-2026-034',
        remarks: 'Demonstrated correct 45-degree angle inspection technique.',
      },
    ],
    notes: 'Certified inspectors receive official stamp authorization for Raw Material GRN release.',
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2026-09-18T11:30:00Z',
  },
  {
    id: 'trn-3',
    courseCode: 'TRN-AQL-03',
    title: 'ISO 2859-1 / AQL 1.5 Final Random Inspection Standards',
    category: 'TECHNICAL_QMS',
    department: 'Quality Assurance & Finishing',
    targetAudience: 'End-of-Line Quality Controllers, AQL Auditors, Merchandisers',
    trainerName: 'Tanzim Ahmed (QA Director)',
    frequency: 'QUARTERLY',
    durationHours: 5.0,
    venue: 'Auditorium Training Hall B',
    maxCapacity: 35,
    trainedCount: 160,
    passRatePercent: 94.5,
    nextScheduledDate: '2026-10-20',
    status: 'SCHEDULED',
    isoClause: 'ISO 9001:2015 Clause 8.6 & 9.1.3',
    prerequisites: 'Garment measurement & defect terminology orientation',
    syllabusTopics: [
      'Normal vs Tightened vs Reduced inspection level sampling plans',
      'Lot size determination and General Inspection Level II sample size letters',
      'Categorization of Critical (0), Major (1.5), and Minor (4.0) defects',
      'Workmanship defect identification (skipped stitches, puckering, shading)',
      'Carton sampling square root formula and barcode scanning verification',
      'Formal Inspection Certificate (IC) documentation and buyer upload',
    ],
    examCode: 'EXAM-AQL-01',
    examPaperId: 'exam-3',
    attendees: [
      {
        id: 'att-301',
        employeeId: 'EMP-2022-0401',
        name: 'Nasreen Akter',
        department: 'Finishing & Packing',
        designation: 'AQL Lead Inspector',
        attendanceStatus: 'PRESENT',
        preTestScore: 82,
        postTestScore: 98,
        practicalScore: 97,
        finalScore: 98,
        result: 'PASSED',
        certificateNo: 'CERT-AQL-2026-052',
        remarks: 'Perfect execution of lot sample extraction and measurement audit.',
      },
    ],
    notes: 'Pre-requisite for all personnel authorized to sign pre-shipment buyer release documents.',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2026-09-20T14:00:00Z',
  },
  {
    id: 'trn-4',
    courseCode: 'TRN-CHM-04',
    title: 'ZDHC MRSL Chemical Handling, SDS & Spillage Containment',
    category: 'CHEMICAL_ENVIRONMENTAL',
    department: 'Washing Plant & ETP',
    targetAudience: 'Washing Operators, Chemical Store Handlers, ETP Technicians',
    trainerName: 'Arif Hossain (Chemical Engineer)',
    frequency: 'SEMI_ANNUAL',
    durationHours: 4.0,
    venue: 'Washing Plant Training Room',
    maxCapacity: 30,
    trainedCount: 75,
    passRatePercent: 97.0,
    nextScheduledDate: '2026-09-28',
    status: 'COMPLETED',
    isoClause: 'ISO 14001:2015 Clause 8.1 & ZDHC MRSL v3.1',
    prerequisites: 'Basic industrial safety and PPE orientation',
    syllabusTopics: [
      'Reading Safety Data Sheets (SDS) in English and Bengali',
      'Mandatory chemical PPE usage: respirators, nitrile gloves, chemical aprons',
      'ZDHC Gateway Level 3 chemical verification and smart inventory logging',
      'Secondary containment inspection and eyewash station maintenance',
      'Emergency chemical spillage drill and neutralizing agent application',
    ],
    examCode: 'EXAM-CHM-01',
    examPaperId: 'exam-4',
    attendees: [],
    notes: 'Compliant with Higg FEM and European buyer chemical management audit standards.',
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2026-09-22T09:30:00Z',
  },
  {
    id: 'trn-5',
    courseCode: 'TRN-AUD-05',
    title: 'ISO 19011 Internal QMS Auditor Methodology & Non-Conformance Writing',
    category: 'MANAGEMENT_AUDITING',
    department: 'Internal Audit & Compliance',
    targetAudience: 'Internal Quality Auditors, Section Leads, Management Trainees',
    trainerName: 'Md. Rafiqul Islam (Lead Auditor)',
    frequency: 'ANNUAL',
    durationHours: 8.0,
    venue: 'Executive Boardroom & Production Floor',
    maxCapacity: 20,
    trainedCount: 42,
    passRatePercent: 93.0,
    nextScheduledDate: '2026-11-15',
    status: 'SCHEDULED',
    isoClause: 'ISO 9001:2015 Clause 9.2 & ISO 19011:2018',
    prerequisites: 'Minimum 2 years quality assurance experience',
    syllabusTopics: [
      'Auditing principles: integrity, fair presentation, and independence',
      'Developing process-based checklists and audit trail questioning',
      'Gathering objective evidence through interviews and sampling',
      'Writing constructive Non-Conformance Reports (NCR) using PLOR criteria',
      'Root cause analysis validation (5-Why, Ishikawa diagram) and CAPA closure',
    ],
    examCode: 'EXAM-AUD-01',
    examPaperId: 'exam-5',
    attendees: [],
    notes: 'Successful graduates receive official internal auditor appointment letters from the MD.',
    createdAt: '2024-01-05T08:00:00Z',
    updatedAt: '2026-09-10T16:00:00Z',
  },
];

export const INITIAL_EXAM_PAPERS: TrainingExamPaper[] = [
  {
    id: 'exam-1',
    examCode: 'EXAM-NDL-01',
    title: '9-Point Broken Needle & Metal Detection Competency Examination',
    courseCode: 'TRN-NDL-01',
    courseTitle: '9-Point Broken Needle Policy & Metal Contamination Prevention',
    targetDepartment: 'Sewing & Finishing',
    durationMinutes: 45,
    totalMarks: 100,
    passingPercentage: 85,
    status: 'ACTIVE',
    createdBy: 'Engr. Tariqul Islam (VP QA)',
    instructions:
      'Answer all questions. Practical reassembly test must achieve 100% precision with all fragments accounted for before needle issuance.',
    questions: [
      {
        id: 'q-101',
        questionNumber: 1,
        questionText:
          'When a sewing needle breaks on the production line, what is the mandatory first action the operator must take?',
        type: 'MCQ',
        options: [
          'A) Ask the helper to immediately fetch a new needle from the mechanic',
          'B) Stop sewing, collect all broken fragments, and inform the roving supervisor immediately',
          'C) Continue sewing with another needle and report at the end of the shift',
          'D) Throw away the broken eye and install a replacement',
        ],
        correctAnswer: 'B',
        points: 15,
        evaluationCriteria: 'Knowledge of immediate stoppage and fragment preservation',
      },
      {
        id: 'q-102',
        questionNumber: 2,
        questionText:
          'If only 8 out of 9 broken needle fragments are recovered on the garment and work table, can a replacement needle be issued?',
        type: 'TRUE_FALSE',
        options: ['True (Yes, with supervisor permission)', 'False (No, 100% fragments required)'],
        correctAnswer: 'False (No, 100% fragments required)',
        points: 15,
        evaluationCriteria: 'Strict adherence to 100% fragment reassembly rule',
      },
      {
        id: 'q-103',
        questionNumber: 3,
        questionText:
          'What is the standard test card diameter required for hourly metal detector calibration?',
        type: 'MCQ',
        options: [
          'A) 2.5mm Ferrous',
          'B) 1.5mm Non-Ferrous',
          'C) 1.0mm Ferrous test card (9-point calibration trigger)',
          'D) 3.0mm Stainless Steel',
        ],
        correctAnswer: 'C',
        points: 20,
        evaluationCriteria: 'Knowledge of buyer 1.0mm ferrous calibration requirement',
      },
      {
        id: 'q-104',
        questionNumber: 4,
        questionText:
          'Practical Demonstration: Accurately reassemble broken needle parts onto the numbered inspection board and complete the Red Lockbox Register.',
        type: 'PRACTICAL_CHECK',
        points: 35,
        evaluationCriteria: 'Full fragment physical matching and accurate log sheet record',
      },
      {
        id: 'q-105',
        questionNumber: 5,
        questionText:
          'Oral Viva: Explain what happens when a garment fails metal detection twice on the conveyor tunnel.',
        type: 'VIVA',
        points: 15,
        evaluationCriteria: 'Demonstrates clear understanding of quarantine and wand scanning protocol',
      },
    ],
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2026-09-12T10:00:00Z',
  },
  {
    id: 'exam-2',
    examCode: 'EXAM-FAB-01',
    title: 'ASTM D5430 4-Point System Fabric Inspection Technical Examination',
    courseCode: 'TRN-FAB-02',
    courseTitle: 'ASTM D5430 4-Point System Fabric Inspection & Defect Grading',
    targetDepartment: 'Fabric Warehouse & Lab',
    durationMinutes: 60,
    totalMarks: 100,
    passingPercentage: 80,
    status: 'ACTIVE',
    createdBy: 'Farida Yasmin (Lab Manager)',
    instructions:
      'Covers ASTM penalty point scoring, length threshold calculation, and Grey Scale color evaluation. Calculations must be shown clearly.',
    questions: [
      {
        id: 'q-201',
        questionNumber: 1,
        questionText:
          'Under the ASTM D5430 4-Point system, what penalty point value is assigned to a fabric flaw between 6 inches and 9 inches in length?',
        type: 'MCQ',
        options: [
          'A) 1 Point',
          'B) 2 Points',
          'C) 3 Points',
          'D) 4 Points',
        ],
        correctAnswer: 'C',
        points: 20,
        evaluationCriteria: 'Defect length grading table mastery',
      },
      {
        id: 'q-202',
        questionNumber: 2,
        questionText:
          'What is the formula used to calculate total points per 100 square yards of inspected fabric?',
        type: 'MCQ',
        options: [
          'A) (Total Points × 3600) / (Inspected Yards × Cuttable Width in Inches)',
          'B) (Total Points × 100) / Inspected Yards',
          'C) (Inspected Yards × Width) / Total Points',
          'D) Total Points / Fabric GSM',
        ],
        correctAnswer: 'A',
        points: 25,
        evaluationCriteria: 'Correct calculation formula knowledge',
      },
      {
        id: 'q-203',
        questionNumber: 3,
        questionText:
          'Practical Test: Inspect 20 yards of knit single jersey roll on inspection table and calculate final points per 100 sq yds.',
        type: 'PRACTICAL_CHECK',
        points: 40,
        evaluationCriteria: 'Speed, flaw detection accuracy, and arithmetic calculation correctness',
      },
      {
        id: 'q-204',
        questionNumber: 4,
        questionText:
          'True or False: Any hole or open defect exceeding 1 inch is automatically assigned the maximum 4 points.',
        type: 'TRUE_FALSE',
        options: ['True', 'False'],
        correctAnswer: 'True',
        points: 15,
        evaluationCriteria: 'Understanding severe defect penalty rules',
      },
    ],
    createdAt: '2024-02-15T08:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'exam-3',
    examCode: 'EXAM-AQL-01',
    title: 'ISO 2859-1 / AQL 1.5 Final Random Inspection Theory & Practical',
    courseCode: 'TRN-AQL-03',
    courseTitle: 'ISO 2859-1 / AQL 1.5 Final Random Inspection Standards',
    targetDepartment: 'Quality Assurance & Finishing',
    durationMinutes: 60,
    totalMarks: 100,
    passingPercentage: 85,
    status: 'ACTIVE',
    createdBy: 'Tanzim Ahmed (QA Director)',
    instructions:
      'Mandatory for all final AQL auditors. Must pass both statistical table reading and practical garment measurement inspection.',
    questions: [
      {
        id: 'q-301',
        questionNumber: 1,
        questionText:
          'For an export order lot size of 3,200 pcs under General Inspection Level II, what is the sample size and code letter?',
        type: 'MCQ',
        options: [
          'A) Code Letter J (80 Pcs)',
          'B) Code Letter K (125 Pcs)',
          'C) Code Letter L (200 Pcs)',
          'D) Code Letter M (315 Pcs)',
        ],
        correctAnswer: 'C',
        points: 25,
        evaluationCriteria: 'Mastery of ISO 2859-1 Table 1 Sample Code Letters',
      },
      {
        id: 'q-302',
        questionNumber: 2,
        questionText:
          'For Sample Size 200 at AQL 1.5 (Normal Single Sampling), what are the Accept (Ac) and Reject (Re) numbers?',
        type: 'MCQ',
        options: [
          'A) Ac = 3, Re = 4',
          'B) Ac = 5, Re = 6',
          'C) Ac = 7, Re = 8',
          'D) Ac = 10, Re = 11',
        ],
        correctAnswer: 'C',
        points: 25,
        evaluationCriteria: 'Accurate reading of Normal Inspection Sampling Plans',
      },
      {
        id: 'q-303',
        questionNumber: 3,
        questionText:
          'Practical Inspection: Audit 5 finished garments against spec sheet for chest, body length, sleeve length, and stitching defects.',
        type: 'PRACTICAL_CHECK',
        points: 35,
        evaluationCriteria: 'Tension, measurement tape precision, and defect categorization',
      },
      {
        id: 'q-304',
        questionNumber: 4,
        questionText:
          'Viva Question: How do you handle a lot where 1 Critical defect (e.g. sharp metal point) is discovered?',
        type: 'VIVA',
        points: 15,
        evaluationCriteria: 'Immediate lot rejection and 100% screening mandate',
      },
    ],
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2026-09-15T14:00:00Z',
  },
];

export const INITIAL_EVALUATION_RECORDS: TrainingEvaluationRecord[] = [
  {
    id: 'eval-1',
    evaluationCode: 'EVAL-NDL-2026-09',
    trainingId: 'trn-1',
    courseCode: 'TRN-NDL-01',
    courseTitle: '9-Point Broken Needle Policy & Metal Contamination Prevention',
    sessionDate: '2026-09-15',
    trainerName: 'Engr. Tariqul Islam',
    evaluatorName: 'Tanzim Ahmed',
    evaluatorTitle: 'Head of Quality Assurance (QMS Director)',
    totalAttendees: 3,
    passedCount: 3,
    failedCount: 0,
    averageScorePercent: 95.0,
    competencyCertified: true,
    status: 'COMPLETED',
    trainerRemarks:
      'All attendees demonstrated flawless practical fragment reassembly and metal detector calibration checks. Certified for export production lines.',
    trainees: [
      {
        id: 'att-101',
        employeeId: 'EMP-2022-0481',
        name: 'Nasrin Sultana',
        department: 'Sewing Production',
        designation: 'Senior Sewing Operator',
        attendanceStatus: 'PRESENT',
        preTestScore: 65,
        postTestScore: 95,
        practicalScore: 98,
        finalScore: 96,
        result: 'PASSED',
        certificateNo: 'CERT-NDL-2026-081',
        remarks: 'Demonstrated high competence in needle fragment recovery.',
      },
      {
        id: 'att-102',
        employeeId: 'EMP-2023-0192',
        name: 'Abdur Rahim',
        department: 'Sewing Production',
        designation: 'Line 4 Supervisor',
        attendanceStatus: 'PRESENT',
        preTestScore: 70,
        postTestScore: 100,
        practicalScore: 95,
        finalScore: 98,
        result: 'PASSED',
        certificateNo: 'CERT-NDL-2026-082',
        remarks: 'Excellent supervision log and quarantine box protocol.',
      },
      {
        id: 'att-103',
        employeeId: 'EMP-2024-0044',
        name: 'Fatema Khatun',
        department: 'Finishing & Packing',
        designation: 'Metal Detector Operator',
        attendanceStatus: 'PRESENT',
        preTestScore: 60,
        postTestScore: 90,
        practicalScore: 92,
        finalScore: 91,
        result: 'PASSED',
        certificateNo: 'CERT-NDL-2026-083',
        remarks: 'Accurately performed 9-zone conveyor tunnel calibration.',
      },
    ],
    updatedAt: '2026-09-15T17:00:00Z',
  },
  {
    id: 'eval-2',
    evaluationCode: 'EVAL-FAB-2026-08',
    trainingId: 'trn-2',
    courseCode: 'TRN-FAB-02',
    courseTitle: 'ASTM D5430 4-Point System Fabric Inspection & Defect Grading',
    sessionDate: '2026-08-20',
    trainerName: 'Farida Yasmin',
    evaluatorName: 'Tanzim Ahmed',
    evaluatorTitle: 'Head of Quality Assurance (QMS Director)',
    totalAttendees: 2,
    passedCount: 2,
    failedCount: 0,
    averageScorePercent: 93.0,
    competencyCertified: true,
    status: 'COMPLETED',
    trainerRemarks:
      'Both inspectors passed both theoretical formula calculations and physical fabric rolling inspection. Granted GRN release stamp authority.',
    trainees: [
      {
        id: 'att-201',
        employeeId: 'EMP-2021-0310',
        name: 'Mizanur Rahman',
        department: 'Fabric Warehouse',
        designation: 'Senior Fabric Inspector',
        attendanceStatus: 'PRESENT',
        preTestScore: 75,
        postTestScore: 96,
        practicalScore: 94,
        finalScore: 95,
        result: 'PASSED',
        certificateNo: 'CERT-FAB-2026-033',
        remarks: 'Outstanding speed and flaw detection accuracy.',
      },
      {
        id: 'att-202',
        employeeId: 'EMP-2023-0871',
        name: 'Sultana Parveen',
        department: 'Fabric Warehouse',
        designation: 'Fabric QC Inspector',
        attendanceStatus: 'PRESENT',
        preTestScore: 68,
        postTestScore: 92,
        practicalScore: 90,
        finalScore: 91,
        result: 'PASSED',
        certificateNo: 'CERT-FAB-2026-034',
        remarks: 'Clear understanding of ASTM 4-point penalty calculations.',
      },
    ],
    updatedAt: '2026-08-20T16:30:00Z',
  },
];

export const INITIAL_ANNUAL_TRAINING_SCHEDULE: AnnualTrainingScheduleItem[] = [
  // JANUARY
  {
    id: 'sch-01-cut',
    scheduleCode: 'SCH-2026-01-CUT',
    month: 'January',
    monthIndex: 1,
    dayOfWeek: 'Monday',
    date: '2026-01-12',
    timeSlot: '09:30 AM - 12:30 PM',
    durationHours: 3.0,
    section: 'CUTTING_SECTION',
    sectionName: 'Cutting Division',
    courseCode: 'TRN-CUT-01',
    topicTitle: 'Fabric Spreading Tension Control & Grainline Alignment',
    trainerName: 'Engr. Shafiqul Alam (Cutting Master)',
    venue: 'Cutting Floor Conference Room',
    targetSeats: 25,
    status: 'COMPLETED',
    mandatoryFor: 'CAD Operators, Spreader Operators, Table Cutters',
    notes: 'Zero tension spreading on elastic knit single jersey fabrics to avoid shrinkage distortion.',
  },
  {
    id: 'sch-01-sew',
    scheduleCode: 'SCH-2026-01-SEW',
    month: 'January',
    monthIndex: 1,
    dayOfWeek: 'Monday',
    date: '2026-01-19',
    timeSlot: '02:00 PM - 05:30 PM',
    durationHours: 3.5,
    section: 'SEWING_SECTION',
    sectionName: 'Sewing Production',
    courseCode: 'TRN-NDL-01',
    topicTitle: '9-Point Broken Needle Policy & Metal Contamination Prevention',
    trainerName: 'Engr. Tariqul Islam & Kamal Hossain',
    venue: 'Training Hall A (Floor 2)',
    targetSeats: 45,
    status: 'COMPLETED',
    mandatoryFor: 'Sewing Machine Operators, Line Supervisors, Roving QCs',
    notes: '100% fragments recovery validation on numbered board before issuing replacement needles.',
  },
  {
    id: 'sch-01-lab',
    scheduleCode: 'SCH-2026-01-LAB',
    month: 'January',
    monthIndex: 1,
    dayOfWeek: 'Saturday',
    date: '2026-01-24',
    timeSlot: '10:00 AM - 01:00 PM',
    durationHours: 3.0,
    section: 'FABRIC_LAB',
    sectionName: 'Fabric Warehouse & Lab',
    courseCode: 'TRN-LAB-01',
    topicTitle: 'GSM Verification & Dimensional Stability Wash Testing Protocol',
    trainerName: 'Farida Yasmin (Lab Manager)',
    venue: 'Central Fabric Laboratory',
    targetSeats: 15,
    status: 'COMPLETED',
    mandatoryFor: 'Lab Technicians, Fabric Inward Inspectors',
    notes: 'AATCC 135 dimensional stability testing and tumble dry percentage calculation.',
  },

  // FEBRUARY
  {
    id: 'sch-02-fin',
    scheduleCode: 'SCH-2026-02-FIN',
    month: 'February',
    monthIndex: 2,
    dayOfWeek: 'Wednesday',
    date: '2026-02-11',
    timeSlot: '09:30 AM - 12:30 PM',
    durationHours: 3.0,
    section: 'FINISHING_PACKING',
    sectionName: 'Finishing & Packing',
    courseCode: 'TRN-FIN-01',
    topicTitle: 'Conveyor Tunnel Metal Detector Calibration (1.0mm Fe) & Wand Technique',
    trainerName: 'Nasir Uddin (Finishing Manager)',
    venue: 'Finishing Hall Training Zone',
    targetSeats: 30,
    status: 'COMPLETED',
    mandatoryFor: 'Metal Detector Operators, Carton Packers, Packing Supervisors',
    notes: 'Hourly 9-zone tunnel sensitivity verification with certified ferrous test card.',
  },
  {
    id: 'sch-02-qms',
    scheduleCode: 'SCH-2026-02-QMS',
    month: 'February',
    monthIndex: 2,
    dayOfWeek: 'Monday',
    date: '2026-02-16',
    timeSlot: '02:00 PM - 05:00 PM',
    durationHours: 3.0,
    section: 'QUALITY_ASSURANCE',
    sectionName: 'Quality Assurance',
    courseCode: 'TRN-AQL-03',
    topicTitle: 'ISO 2859-1 / AQL 1.5 Sampling Plan & Lot Size Determination',
    trainerName: 'Tanzim Ahmed (QA Director)',
    venue: 'Auditorium Training Hall B',
    targetSeats: 35,
    status: 'COMPLETED',
    mandatoryFor: 'Final AQL Auditors, End-of-Line QCs, Quality Supervisors',
    notes: 'General Inspection Level II sample code letter tables and Ac/Re limits.',
  },
  {
    id: 'sch-02-mnt',
    scheduleCode: 'SCH-2026-02-MNT',
    month: 'February',
    monthIndex: 2,
    dayOfWeek: 'Thursday',
    date: '2026-02-26',
    timeSlot: '02:30 PM - 05:30 PM',
    durationHours: 3.0,
    section: 'MAINTENANCE_SAFETY',
    sectionName: 'Maintenance & Safety',
    courseCode: 'TRN-MNT-01',
    topicTitle: 'Sewing Machine Preventive Maintenance & Needle Bar Timing Alignment',
    trainerName: 'Engr. Delowar Hossain (Chief Engineer)',
    venue: 'Mechanical Workshop Room 3',
    targetSeats: 20,
    status: 'COMPLETED',
    mandatoryFor: 'Maintenance Mechanics, Line Technicians',
    notes: 'Lubrication schedules, needle guard clearance, and bobbin case tension gauge calibration.',
  },

  // MARCH
  {
    id: 'sch-03-cut',
    scheduleCode: 'SCH-2026-03-CUT',
    month: 'March',
    monthIndex: 3,
    dayOfWeek: 'Monday',
    date: '2026-03-09',
    timeSlot: '10:00 AM - 01:00 PM',
    durationHours: 3.0,
    section: 'CUTTING_SECTION',
    sectionName: 'Cutting Division',
    courseCode: 'TRN-CUT-02',
    topicTitle: 'Bundle Ticketing, Cut Numbering & Shade Band Separation',
    trainerName: 'Engr. Shafiqul Alam (Cutting Master)',
    venue: 'Cutting Floor Conference Room',
    targetSeats: 25,
    status: 'COMPLETED',
    mandatoryFor: 'Ticketing Staff, Bundle Handlers, Cutting QC',
    notes: 'Strict piece-numbering sequence to ensure 100% shade uniformity per garment assembly.',
  },
  {
    id: 'sch-03-sew',
    scheduleCode: 'SCH-2026-03-SEW',
    month: 'March',
    monthIndex: 3,
    dayOfWeek: 'Wednesday',
    date: '2026-03-18',
    timeSlot: '02:00 PM - 05:00 PM',
    durationHours: 3.0,
    section: 'SEWING_SECTION',
    sectionName: 'Sewing Production',
    courseCode: 'TRN-SEW-02',
    topicTitle: 'ISO 4915 Stitch Type Specifications, SPI & Thread Tension Calibration',
    trainerName: 'Kamal Hossain (Sewing Tech Specialist)',
    venue: 'Training Hall A (Floor 2)',
    targetSeats: 40,
    status: 'COMPLETED',
    mandatoryFor: 'Line Supervisors, Quality Controllers, Sample Machinists',
    notes: 'Stitches per inch (SPI) gauge audit and seam elasticity verification for activewear.',
  },
  {
    id: 'sch-03-lab',
    scheduleCode: 'SCH-2026-03-LAB',
    month: 'March',
    monthIndex: 3,
    dayOfWeek: 'Saturday',
    date: '2026-03-28',
    timeSlot: '09:30 AM - 03:30 PM',
    durationHours: 6.0,
    section: 'FABRIC_LAB',
    sectionName: 'Fabric Warehouse & Lab',
    courseCode: 'TRN-FAB-02',
    topicTitle: 'ASTM D5430 4-Point System Fabric Inspection & Defect Grading',
    trainerName: 'Farida Yasmin (Lab Manager)',
    venue: 'Central Fabric Laboratory',
    targetSeats: 25,
    status: 'COMPLETED',
    mandatoryFor: 'Fabric Warehouse Inspectors, Incoming QC Staff',
    notes: 'Flaw penalty point calculations per 100 sq yds and roll acceptance thresholds.',
  },

  // APRIL
  {
    id: 'sch-04-qms',
    scheduleCode: 'SCH-2026-04-QMS',
    month: 'April',
    monthIndex: 4,
    dayOfWeek: 'Monday',
    date: '2026-04-06',
    timeSlot: '09:30 AM - 01:00 PM',
    durationHours: 3.5,
    section: 'QUALITY_ASSURANCE',
    sectionName: 'Quality Assurance',
    courseCode: 'TRN-QMS-02',
    topicTitle: 'Garment Critical Defect Root Cause Analysis (5-Why & Ishikawa Diagram)',
    trainerName: 'Tanzim Ahmed (QA Director)',
    venue: 'Auditorium Training Hall B',
    targetSeats: 30,
    status: 'COMPLETED',
    mandatoryFor: 'QA Managers, Floor In-Charges, Production Executives',
    notes: 'Methodology for closing Corrective and Preventive Action (CAPA) with buyer proof.',
  },
  {
    id: 'sch-04-fin',
    scheduleCode: 'SCH-2026-04-FIN',
    month: 'April',
    monthIndex: 4,
    dayOfWeek: 'Wednesday',
    date: '2026-04-15',
    timeSlot: '02:00 PM - 05:00 PM',
    durationHours: 3.0,
    section: 'FINISHING_PACKING',
    sectionName: 'Finishing & Packing',
    courseCode: 'TRN-FIN-02',
    topicTitle: 'Industrial Pressing Temperature, Vacuum Suction & Shine Mark Prevention',
    trainerName: 'Nasir Uddin (Finishing Manager)',
    venue: 'Finishing Hall Training Zone',
    targetSeats: 35,
    status: 'COMPLETED',
    mandatoryFor: 'Ironing Operators, Final Pressers, Finishing QCs',
    notes: 'Teflon shoe soleplates and steam pressure regulation for delicate poly-cotton blends.',
  },
  {
    id: 'sch-04-mnt',
    scheduleCode: 'SCH-2026-04-MNT',
    month: 'April',
    monthIndex: 4,
    dayOfWeek: 'Thursday',
    date: '2026-04-23',
    timeSlot: '10:00 AM - 02:00 PM',
    durationHours: 4.0,
    section: 'MAINTENANCE_SAFETY',
    sectionName: 'Maintenance & Safety',
    courseCode: 'TRN-CHM-04',
    topicTitle: 'ZDHC MRSL Chemical Handling, SDS Compliance & Spillage Containment',
    trainerName: 'Arif Hossain (Chemical Engineer)',
    venue: 'Washing Plant Training Room',
    targetSeats: 30,
    status: 'COMPLETED',
    mandatoryFor: 'Chemical Store Keepers, Washing Operators, ETP Technicians',
    notes: 'Secondary containment inspection, chemical PPE, and neutralizing agent deployment.',
  },

  // MAY
  {
    id: 'sch-05-cut',
    scheduleCode: 'SCH-2026-05-CUT',
    month: 'May',
    monthIndex: 5,
    dayOfWeek: 'Monday',
    date: '2026-05-11',
    timeSlot: '09:30 AM - 12:30 PM',
    durationHours: 3.0,
    section: 'CUTTING_SECTION',
    sectionName: 'Cutting Division',
    courseCode: 'TRN-CUT-03',
    topicTitle: 'Continuous Fusing Machine Temperature, Pressure & Peel Strength Testing',
    trainerName: 'Engr. Shafiqul Alam (Cutting Master)',
    venue: 'Cutting Fusing Station Zone',
    targetSeats: 20,
    status: 'COMPLETED',
    mandatoryFor: 'Fusing Machine Operators, Interlining Controllers',
    notes: 'Thermo-paper heat strips and digital peel strength pull gauge calibrations.',
  },
  {
    id: 'sch-05-sew',
    scheduleCode: 'SCH-2026-05-SEW',
    month: 'May',
    monthIndex: 5,
    dayOfWeek: 'Wednesday',
    date: '2026-05-20',
    timeSlot: '02:00 PM - 05:30 PM',
    durationHours: 3.5,
    section: 'SEWING_SECTION',
    sectionName: 'Sewing Production',
    courseCode: 'TRN-NDL-01',
    topicTitle: 'Monthly 9-Point Broken Needle Refresher & New Operator Induction',
    trainerName: 'Engr. Tariqul Islam & Kamal Hossain',
    venue: 'Training Hall A (Floor 2)',
    targetSeats: 45,
    status: 'COMPLETED',
    mandatoryFor: 'New Sewing Operators, Apprentice Machinists, Shift Line Leaders',
    notes: 'Mandatory certification before placing workers onto childrenswear production lines.',
  },
  {
    id: 'sch-05-lab',
    scheduleCode: 'SCH-2026-05-LAB',
    month: 'May',
    monthIndex: 5,
    dayOfWeek: 'Saturday',
    date: '2026-05-30',
    timeSlot: '10:00 AM - 01:00 PM',
    durationHours: 3.0,
    section: 'FABRIC_LAB',
    sectionName: 'Fabric Warehouse & Lab',
    courseCode: 'TRN-LAB-02',
    topicTitle: 'Color Fastness to Washing, Crocking & Light (ISO 105 Standards)',
    trainerName: 'Farida Yasmin (Lab Manager)',
    venue: 'Central Fabric Laboratory',
    targetSeats: 15,
    status: 'COMPLETED',
    mandatoryFor: 'Color Matchers, Lab Quality Auditors',
    notes: 'Grey Scale rating evaluation under D65 / TL84 / CWF standardized light box cabinets.',
  },

  // JUNE
  {
    id: 'sch-06-fin',
    scheduleCode: 'SCH-2026-06-FIN',
    month: 'June',
    monthIndex: 6,
    dayOfWeek: 'Monday',
    date: '2026-06-08',
    timeSlot: '09:30 AM - 12:30 PM',
    durationHours: 3.0,
    section: 'FINISHING_PACKING',
    sectionName: 'Finishing & Packing',
    courseCode: 'TRN-FIN-03',
    topicTitle: 'Carton Barcode Verification, Solid/Assorted Packing Ratio & Drop Test',
    trainerName: 'Nasir Uddin (Finishing Manager)',
    venue: 'Packing Division Conference Hall',
    targetSeats: 30,
    status: 'COMPLETED',
    mandatoryFor: 'Carton Packers, Dispatch Supervisors, Final Packing QCs',
    notes: 'ASTM D5276 10-point carton drop test protocol and GS1-128 barcode scan validation.',
  },
  {
    id: 'sch-06-qms',
    scheduleCode: 'SCH-2026-06-QMS',
    month: 'June',
    monthIndex: 6,
    dayOfWeek: 'Wednesday',
    date: '2026-06-17',
    timeSlot: '02:00 PM - 05:00 PM',
    durationHours: 3.0,
    section: 'QUALITY_ASSURANCE',
    sectionName: 'Quality Assurance',
    courseCode: 'TRN-QMS-03',
    topicTitle: 'Traffic Light Quality System (Green/Yellow/Red) On-Line Inspection',
    trainerName: 'Tanzim Ahmed (QA Director)',
    venue: 'Auditorium Training Hall B',
    targetSeats: 40,
    status: 'COMPLETED',
    mandatoryFor: 'Line QCs, Sewing Supervisors, Floor Managers',
    notes: 'Immediate line stoppage protocol on discovering 2 consecutive defects on one operation.',
  },
  {
    id: 'sch-06-mnt',
    scheduleCode: 'SCH-2026-06-MNT',
    month: 'June',
    monthIndex: 6,
    dayOfWeek: 'Thursday',
    date: '2026-06-25',
    timeSlot: '02:30 PM - 05:30 PM',
    durationHours: 3.0,
    section: 'MAINTENANCE_SAFETY',
    sectionName: 'Maintenance & Safety',
    courseCode: 'TRN-SAF-01',
    topicTitle: 'Electrical Fire Safety, Eye-Wash Maintenance & Emergency Evacuation Drill',
    trainerName: 'Md. Nazmul Karim (Safety Officer)',
    venue: 'Central Assembly Ground & Floor 1',
    targetSeats: 50,
    status: 'COMPLETED',
    mandatoryFor: 'Safety Wardens, Department Floor In-Charges, Shift Leads',
    notes: 'Full facility timed evacuation drill, fire extinguisher discharge, and hydrants inspection.',
  },

  // JULY
  {
    id: 'sch-07-cut',
    scheduleCode: 'SCH-2026-07-CUT',
    month: 'July',
    monthIndex: 7,
    dayOfWeek: 'Monday',
    date: '2026-07-13',
    timeSlot: '09:30 AM - 12:30 PM',
    durationHours: 3.0,
    section: 'CUTTING_SECTION',
    sectionName: 'Cutting Division',
    courseCode: 'TRN-CUT-04',
    topicTitle: 'Band-Knife Cutting Precision & Glove Safety Standards',
    trainerName: 'Engr. Shafiqul Alam (Cutting Master)',
    venue: 'Cutting Floor Training Zone',
    targetSeats: 25,
    status: 'COMPLETED',
    mandatoryFor: 'Band-knife Operators, Straight Knife Handlers',
    notes: 'Mandatory stainless steel mesh glove usage and knife blade alignment verification.',
  },
  {
    id: 'sch-07-sew',
    scheduleCode: 'SCH-2026-07-SEW',
    month: 'July',
    monthIndex: 7,
    dayOfWeek: 'Monday',
    date: '2026-07-20',
    timeSlot: '02:00 PM - 05:30 PM',
    durationHours: 3.5,
    section: 'SEWING_SECTION',
    sectionName: 'Sewing Production',
    courseCode: 'TRN-NDL-01',
    topicTitle: 'Monthly 9-Point Needle Safety & Lockbox Reassembly Audit',
    trainerName: 'Engr. Tariqul Islam & Kamal Hossain',
    venue: 'Training Hall A (Floor 2)',
    targetSeats: 45,
    status: 'COMPLETED',
    mandatoryFor: 'Sewing Operators, Line 5-12 Supervisors',
    notes: 'Audit of red quarantine lockboxes across all production buildings.',
  },
  {
    id: 'sch-07-lab',
    scheduleCode: 'SCH-2026-07-LAB',
    month: 'July',
    monthIndex: 7,
    dayOfWeek: 'Saturday',
    date: '2026-07-25',
    timeSlot: '10:00 AM - 01:00 PM',
    durationHours: 3.0,
    section: 'FABRIC_LAB',
    sectionName: 'Fabric Warehouse & Lab',
    courseCode: 'TRN-LAB-03',
    topicTitle: 'Elastane Stretch & Recovery Testing (ASTM D3107) for Denim/Knits',
    trainerName: 'Farida Yasmin (Lab Manager)',
    venue: 'Central Fabric Laboratory',
    targetSeats: 15,
    status: 'COMPLETED',
    mandatoryFor: 'Lab Analysts, Denim Quality Controllers',
    notes: 'Static load stretch, immediate recovery, and 1-hour growth measurement.',
  },

  // AUGUST
  {
    id: 'sch-08-fin',
    scheduleCode: 'SCH-2026-08-FIN',
    month: 'August',
    monthIndex: 8,
    dayOfWeek: 'Wednesday',
    date: '2026-08-12',
    timeSlot: '09:30 AM - 12:30 PM',
    durationHours: 3.0,
    section: 'FINISHING_PACKING',
    sectionName: 'Finishing & Packing',
    courseCode: 'TRN-FIN-04',
    topicTitle: 'Apparel Odor, Mildew & Moisture Control in Polybag Export Packaging',
    trainerName: 'Nasir Uddin (Finishing Manager)',
    venue: 'Finishing Hall Training Zone',
    targetSeats: 30,
    status: 'COMPLETED',
    mandatoryFor: 'Packing Supervisors, Final Audit Team, Moisture Meter Technicians',
    notes: 'Digital pin-type moisture meter tolerance (max 10% moisture content) and silica gel pouch checks.',
  },
  {
    id: 'sch-08-qms',
    scheduleCode: 'SCH-2026-08-QMS',
    month: 'August',
    monthIndex: 8,
    dayOfWeek: 'Monday',
    date: '2026-08-17',
    timeSlot: '02:00 PM - 05:00 PM',
    durationHours: 3.0,
    section: 'QUALITY_ASSURANCE',
    sectionName: 'Quality Assurance',
    courseCode: 'TRN-AQL-03',
    topicTitle: 'Quarterly AQL Auditor Recertification & Defect Classification Matrix',
    trainerName: 'Tanzim Ahmed (QA Director)',
    venue: 'Auditorium Training Hall B',
    targetSeats: 35,
    status: 'COMPLETED',
    mandatoryFor: 'Final Inspection Auditors, Third-Party QC Escorts',
    notes: 'Recertification exam and hands-on measurement tolerance checks on production styles.',
  },
  {
    id: 'sch-08-mnt',
    scheduleCode: 'SCH-2026-08-MNT',
    month: 'August',
    monthIndex: 8,
    dayOfWeek: 'Thursday',
    date: '2026-08-27',
    timeSlot: '02:30 PM - 05:30 PM',
    durationHours: 3.0,
    section: 'MAINTENANCE_SAFETY',
    sectionName: 'Maintenance & Safety',
    courseCode: 'TRN-MNT-02',
    topicTitle: 'Air Compressor & Steam Boiler Line Preventive Safety Inspections',
    trainerName: 'Engr. Delowar Hossain (Chief Engineer)',
    venue: 'Boiler & Compressor Utility Plant',
    targetSeats: 20,
    status: 'COMPLETED',
    mandatoryFor: 'Boiler Attendants, Utility Mechanics, Energy Team',
    notes: 'Steam trap functioning, safety relief valve checks, and condensate recovery inspection.',
  },

  // SEPTEMBER (Current Month)
  {
    id: 'sch-09-sew',
    scheduleCode: 'SCH-2026-09-SEW',
    month: 'September',
    monthIndex: 9,
    dayOfWeek: 'Monday',
    date: '2026-09-14',
    timeSlot: '02:00 PM - 05:30 PM',
    durationHours: 3.5,
    section: 'SEWING_SECTION',
    sectionName: 'Sewing Production',
    courseCode: 'TRN-NDL-01',
    topicTitle: '9-Point Broken Needle Policy & Metal Contamination Prevention',
    trainerName: 'Engr. Tariqul Islam & Kamal Hossain',
    venue: 'Training Hall A (Floor 2)',
    targetSeats: 45,
    status: 'COMPLETED',
    mandatoryFor: 'Sewing Operators, Line Supervisors, Metal Detector Operators',
    notes: 'Monthly session completed with 100% pass rate recorded on evaluation roster.',
  },
  {
    id: 'sch-09-lab',
    scheduleCode: 'SCH-2026-09-LAB',
    month: 'September',
    monthIndex: 9,
    dayOfWeek: 'Saturday',
    date: '2026-09-19',
    timeSlot: '09:30 AM - 03:30 PM',
    durationHours: 6.0,
    section: 'FABRIC_LAB',
    sectionName: 'Fabric Warehouse & Lab',
    courseCode: 'TRN-FAB-02',
    topicTitle: 'ASTM D5430 4-Point System Fabric Inspection & Defect Grading',
    trainerName: 'Farida Yasmin (Lab Manager)',
    venue: 'Central Fabric Laboratory',
    targetSeats: 25,
    status: 'COMPLETED',
    mandatoryFor: 'Fabric Warehouse Quality Inspectors, Lab Technicians',
    notes: 'Penalty calculation exercises on knit spandex rolls and roll rejection protocols.',
  },
  {
    id: 'sch-09-chm',
    scheduleCode: 'SCH-2026-09-CHM',
    month: 'September',
    monthIndex: 9,
    dayOfWeek: 'Monday',
    date: '2026-09-28',
    timeSlot: '10:00 AM - 02:00 PM',
    durationHours: 4.0,
    section: 'MAINTENANCE_SAFETY',
    sectionName: 'Maintenance & Safety',
    courseCode: 'TRN-CHM-04',
    topicTitle: 'ZDHC MRSL Chemical Handling, SDS & Spillage Containment',
    trainerName: 'Arif Hossain (Chemical Engineer)',
    venue: 'Washing Plant Training Room',
    targetSeats: 30,
    status: 'UPCOMING',
    mandatoryFor: 'Washing Operators, Chemical Store Handlers, ETP Technicians',
    notes: 'Upcoming mandatory session scheduled for coming Monday.',
  },

  // OCTOBER (Upcoming Full Schedule)
  {
    id: 'sch-10-sew',
    scheduleCode: 'SCH-2026-10-SEW',
    month: 'October',
    monthIndex: 10,
    dayOfWeek: 'Monday',
    date: '2026-10-05',
    timeSlot: '09:30 AM - 01:00 PM',
    durationHours: 3.5,
    section: 'SEWING_SECTION',
    sectionName: 'Sewing Production',
    courseCode: 'TRN-NDL-01',
    topicTitle: '9-Point Broken Needle Policy & Metal Contamination Prevention',
    trainerName: 'Engr. Tariqul Islam & Kamal Hossain',
    venue: 'Training Hall A (Floor 2)',
    targetSeats: 45,
    status: 'UPCOMING',
    mandatoryFor: 'Sewing Operators, Line Supervisors, Metal Detector Operators',
    notes: 'Upcoming monthly scheduled session for childrenswear line operators.',
  },
  {
    id: 'sch-10-lab',
    scheduleCode: 'SCH-2026-10-LAB',
    month: 'October',
    monthIndex: 10,
    dayOfWeek: 'Monday',
    date: '2026-10-12',
    timeSlot: '09:30 AM - 03:30 PM',
    durationHours: 6.0,
    section: 'FABRIC_LAB',
    sectionName: 'Fabric Warehouse & Lab',
    courseCode: 'TRN-FAB-02',
    topicTitle: 'ASTM D5430 4-Point System Fabric Inspection & Defect Grading',
    trainerName: 'Farida Yasmin (Lab Manager)',
    venue: 'Central Fabric Laboratory',
    targetSeats: 25,
    status: 'UPCOMING',
    mandatoryFor: 'Fabric Warehouse Quality Inspectors, Lab Technicians',
    notes: 'Quarterly certification session for Raw Material GRN release authority.',
  },
  {
    id: 'sch-10-qms',
    scheduleCode: 'SCH-2026-10-QMS',
    month: 'October',
    monthIndex: 10,
    dayOfWeek: 'Tuesday',
    date: '2026-10-20',
    timeSlot: '09:30 AM - 02:30 PM',
    durationHours: 5.0,
    section: 'QUALITY_ASSURANCE',
    sectionName: 'Quality Assurance',
    courseCode: 'TRN-AQL-03',
    topicTitle: 'ISO 2859-1 / AQL 1.5 Final Random Inspection Standards',
    trainerName: 'Tanzim Ahmed (QA Director)',
    venue: 'Auditorium Training Hall B',
    targetSeats: 35,
    status: 'SCHEDULED',
    mandatoryFor: 'End-of-Line Quality Controllers, AQL Auditors, Merchandisers',
    notes: 'Pre-requisite for all personnel authorized to sign pre-shipment buyer release documents.',
  },
  {
    id: 'sch-10-cut',
    scheduleCode: 'SCH-2026-10-CUT',
    month: 'October',
    monthIndex: 10,
    dayOfWeek: 'Monday',
    date: '2026-10-26',
    timeSlot: '02:00 PM - 05:00 PM',
    durationHours: 3.0,
    section: 'CUTTING_SECTION',
    sectionName: 'Cutting Division',
    courseCode: 'TRN-CUT-05',
    topicTitle: 'Automatic CNC Cutter Maintenance, Vacuum Hold-Down & Notch Accuracy',
    trainerName: 'Engr. Shafiqul Alam (Cutting Master)',
    venue: 'Automated Cutting Room 1',
    targetSeats: 20,
    status: 'SCHEDULED',
    mandatoryFor: 'CNC Cutter Programmers, Cutting Technicians',
    notes: 'Blade sharpening frequency and laser pointer calibration against CAD marker.',
  },

  // NOVEMBER
  {
    id: 'sch-11-qms',
    scheduleCode: 'SCH-2026-11-QMS',
    month: 'November',
    monthIndex: 11,
    dayOfWeek: 'Sunday',
    date: '2026-11-15',
    timeSlot: '09:00 AM - 05:00 PM',
    durationHours: 8.0,
    section: 'QUALITY_ASSURANCE',
    sectionName: 'Quality Assurance',
    courseCode: 'TRN-AUD-05',
    topicTitle: 'ISO 19011 Internal QMS Auditor Methodology & Non-Conformance Writing',
    trainerName: 'Md. Rafiqul Islam (Lead Auditor)',
    venue: 'Executive Boardroom & Production Floor',
    targetSeats: 20,
    status: 'SCHEDULED',
    mandatoryFor: 'Internal Quality Auditors, Section Leads, Management Trainees',
    notes: 'Comprehensive annual training for certified internal ISO auditors.',
  },
  {
    id: 'sch-11-sew',
    scheduleCode: 'SCH-2026-11-SEW',
    month: 'November',
    monthIndex: 11,
    dayOfWeek: 'Monday',
    date: '2026-11-16',
    timeSlot: '02:00 PM - 05:30 PM',
    durationHours: 3.5,
    section: 'SEWING_SECTION',
    sectionName: 'Sewing Production',
    courseCode: 'TRN-NDL-01',
    topicTitle: 'Monthly 9-Point Broken Needle & Metal Detection Protocol',
    trainerName: 'Engr. Tariqul Islam & Kamal Hossain',
    venue: 'Training Hall A (Floor 2)',
    targetSeats: 45,
    status: 'SCHEDULED',
    mandatoryFor: 'Sewing Operators, Line Supervisors',
    notes: 'Monthly compliance refresher.',
  },
  {
    id: 'sch-11-fin',
    scheduleCode: 'SCH-2026-11-FIN',
    month: 'November',
    monthIndex: 11,
    dayOfWeek: 'Wednesday',
    date: '2026-11-25',
    timeSlot: '09:30 AM - 12:30 PM',
    durationHours: 3.0,
    section: 'FINISHING_PACKING',
    sectionName: 'Finishing & Packing',
    courseCode: 'TRN-FIN-05',
    topicTitle: 'Hangtag, Price Sticker, RFID Verification & Carton Marking Accuracy',
    trainerName: 'Nasir Uddin (Finishing Manager)',
    venue: 'Finishing Hall Training Zone',
    targetSeats: 30,
    status: 'SCHEDULED',
    mandatoryFor: 'Packing Supervisors, Final Tag Checkers, Export Documentation Staff',
    notes: 'Buyer UPC barcode scannability verification and retail label positioning audit.',
  },

  // DECEMBER
  {
    id: 'sch-12-sew',
    scheduleCode: 'SCH-2026-12-SEW',
    month: 'December',
    monthIndex: 12,
    dayOfWeek: 'Monday',
    date: '2026-12-07',
    timeSlot: '02:00 PM - 05:30 PM',
    durationHours: 3.5,
    section: 'SEWING_SECTION',
    sectionName: 'Sewing Production',
    courseCode: 'TRN-NDL-01',
    topicTitle: 'Year-End 9-Point Needle Policy Master Review & Machine Audit',
    trainerName: 'Engr. Tariqul Islam & Kamal Hossain',
    venue: 'Training Hall A (Floor 2)',
    targetSeats: 45,
    status: 'SCHEDULED',
    mandatoryFor: 'Sewing Operators, Mechanics, Quality Inspectors',
    notes: 'Year-end review of broken needle recovery logs and lockbox serial tags.',
  },
  {
    id: 'sch-12-mnt',
    scheduleCode: 'SCH-2026-12-MNT',
    month: 'December',
    monthIndex: 12,
    dayOfWeek: 'Wednesday',
    date: '2026-12-16',
    timeSlot: '10:00 AM - 01:00 PM',
    durationHours: 3.0,
    section: 'MAINTENANCE_SAFETY',
    sectionName: 'Maintenance & Safety',
    courseCode: 'TRN-SAF-02',
    topicTitle: 'Annual Facility Safety Compliance, PPE Re-licensing & Hazard Risk Review',
    trainerName: 'Md. Nazmul Karim (Safety Officer)',
    venue: 'Auditorium Training Hall B',
    targetSeats: 50,
    status: 'SCHEDULED',
    mandatoryFor: 'All Department Safety Wardens, Floor Heads',
    notes: 'Annual mandatory safety retraining compliant with local labor laws and buyer code of conduct.',
  },
  {
    id: 'sch-12-qms',
    scheduleCode: 'SCH-2026-12-QMS',
    month: 'December',
    monthIndex: 12,
    dayOfWeek: 'Monday',
    date: '2026-12-21',
    timeSlot: '09:30 AM - 03:30 PM',
    durationHours: 6.0,
    section: 'QUALITY_ASSURANCE',
    sectionName: 'Quality Assurance',
    courseCode: 'TRN-QMS-04',
    topicTitle: 'Annual Quality Policy, Management Review Meeting (MRM) Preparation & 2027 Goals',
    trainerName: 'Tanzim Ahmed (QA Director)',
    venue: 'Executive Boardroom',
    targetSeats: 30,
    status: 'SCHEDULED',
    mandatoryFor: 'Quality Managers, Production Managers, Factory GM',
    notes: 'ISO 9001 Clause 9.3 Management Review preparation and factory KPI scorecard presentation.',
  },
];

