import { KpiMetric } from '@/lib/types/modules';

export const INITIAL_KPIS: KpiMetric[] = [
  {
    id: 'kpi-001',
    kpiCode: 'KPI-QA-01',
    metricName: 'Sewing Floor DHU (Defects per Hundred Units)',
    category: 'QUALITY',
    department: 'Sewing Production (Lines 01-12)',
    ownerName: 'Tanzim Ahmed (Head of Quality)',
    currentValue: 1.8,
    targetValue: 1.5,
    unit: '%',
    benchmark: '< 2.0% World-Class Garment Standard',
    status: 'ON_TRACK',
    trend: 'DOWN',
    frequency: 'DAILY',
    formula: '(Total Defects Found / Total Units Inspected) * 100',
    desiredDirection: 'LOWER_IS_BETTER',
    toleranceThreshold: 0.3,
    description: 'Measures total cumulative defects identified at sewing end-line stations per hundred garments produced.',
    lastUpdated: '2026-09-24',
    history: [
      { id: 'h-1', period: 'Apr 2026', value: 2.6, target: 1.5, sampleSize: 125000, loggedBy: 'Md. Al-Amin', remarks: 'High broken stitch rate on denim styles' },
      { id: 'h-2', period: 'May 2026', value: 2.3, target: 1.5, sampleSize: 132000, loggedBy: 'Md. Al-Amin', remarks: 'Needle coolers installed on heavy machines' },
      { id: 'h-3', period: 'Jun 2026', value: 2.1, target: 1.5, sampleSize: 140000, loggedBy: 'Farhana Akhter', remarks: 'Thread lubrication improved' },
      { id: 'h-4', period: 'Jul 2026', value: 2.0, target: 1.5, sampleSize: 138000, loggedBy: 'Md. Al-Amin', remarks: 'Operator re-training completed' },
      { id: 'h-5', period: 'Aug 2026', value: 1.9, target: 1.5, sampleSize: 145000, loggedBy: 'Farhana Akhter', remarks: 'Stable feed dog alignment' },
      { id: 'h-6', period: 'Sep 2026', value: 1.8, target: 1.5, sampleSize: 110000, loggedBy: 'Tanzim Ahmed', remarks: 'Down from 2.6%; on track to reach 1.5%' },
    ],
    actionItems: [
      {
        id: 'act-kpi-1',
        task: 'Conduct line-by-line machine feed dog timing calibration on Line 07 & Line 08',
        assignee: 'Babul Akter (Chief Mechanic)',
        department: 'Maintenance',
        dueDate: '2026-09-30',
        priority: 'MEDIUM',
        completed: false,
      },
    ],
  },
  {
    id: 'kpi-002',
    kpiCode: 'KPI-QA-02',
    metricName: 'Right First Time (RFT) Rate',
    category: 'QUALITY',
    department: 'Sewing & Finishing Assembly',
    ownerName: 'Mst. Shamima Nasrin (Sewing Floor In-Charge)',
    currentValue: 94.6,
    targetValue: 96.0,
    unit: '%',
    benchmark: '> 95.0% Global Apparel Benchmark',
    status: 'AT_RISK',
    trend: 'UP',
    frequency: 'DAILY',
    formula: '(Garments Passed without Rework / Total Garments Produced) * 100',
    desiredDirection: 'HIGHER_IS_BETTER',
    toleranceThreshold: 1.5,
    description: 'Percentage of garment units that pass all end-line inspection criteria on the first pass without rework.',
    lastUpdated: '2026-09-24',
    history: [
      { id: 'h-201', period: 'Apr 2026', value: 92.1, target: 96.0, sampleSize: 120000, loggedBy: 'Shamima Nasrin' },
      { id: 'h-202', period: 'May 2026', value: 92.8, target: 96.0, sampleSize: 128000, loggedBy: 'Shamima Nasrin' },
      { id: 'h-203', period: 'Jun 2026', value: 93.4, target: 96.0, sampleSize: 135000, loggedBy: 'Md. Al-Amin' },
      { id: 'h-204', period: 'Jul 2026', value: 93.9, target: 96.0, sampleSize: 130000, loggedBy: 'Shamima Nasrin' },
      { id: 'h-205', period: 'Aug 2026', value: 94.2, target: 96.0, sampleSize: 142000, loggedBy: 'Md. Al-Amin' },
      { id: 'h-206', period: 'Sep 2026', value: 94.6, target: 96.0, sampleSize: 108000, loggedBy: 'Shamima Nasrin', remarks: '1.4% below 96% target due to collar puckering' },
    ],
    actionItems: [
      {
        id: 'act-kpi-2',
        task: 'Implement pre-sewing mock-up checking for all new style changeovers',
        assignee: 'Farhan Rahman (Merchandising Lead)',
        department: 'Merchandising & Technical',
        dueDate: '2026-09-28',
        priority: 'HIGH',
        completed: false,
      },
    ],
  },
  {
    id: 'kpi-003',
    kpiCode: 'KPI-PR-03',
    metricName: 'Cut-to-Ship Ratio (Material Yield)',
    category: 'PRODUCTIVITY',
    department: 'Cutting & Dispatch Logistics',
    ownerName: 'Kabir Hossain (Chief Cutting Master)',
    currentValue: 98.4,
    targetValue: 98.0,
    unit: '%',
    benchmark: '≥ 98.0% Benchmark Tier 1 Factory',
    status: 'ON_TRACK',
    trend: 'STABLE',
    frequency: 'WEEKLY',
    formula: '(Total First-Quality Shipped Units / Total Cut Quantity) * 100',
    desiredDirection: 'HIGHER_IS_BETTER',
    toleranceThreshold: 0.5,
    description: 'Evaluates production efficiency and fabric conversion from raw cut parts to final shipped export boxes.',
    lastUpdated: '2026-09-22',
    history: [
      { id: 'h-301', period: 'May 2026', value: 97.8, target: 98.0, sampleSize: 220000, loggedBy: 'Kabir Hossain' },
      { id: 'h-302', period: 'Jun 2026', value: 98.1, target: 98.0, sampleSize: 235000, loggedBy: 'Kabir Hossain' },
      { id: 'h-303', period: 'Jul 2026', value: 98.3, target: 98.0, sampleSize: 240000, loggedBy: 'Kabir Hossain' },
      { id: 'h-304', period: 'Aug 2026', value: 98.5, target: 98.0, sampleSize: 250000, loggedBy: 'Kabir Hossain' },
      { id: 'h-305', period: 'Sep 2026', value: 98.4, target: 98.0, sampleSize: 180000, loggedBy: 'Kabir Hossain' },
    ],
  },
  {
    id: 'kpi-004',
    kpiCode: 'KPI-CS-04',
    metricName: 'Cost of Quality (CoQ as % of FOB)',
    category: 'COST',
    department: 'Executive Quality & Finance',
    ownerName: 'Tanzim Ahmed (Head of Quality)',
    currentValue: 1.15,
    targetValue: 1.0,
    unit: '% of FOB',
    benchmark: '< 1.2% Six Sigma Enterprise',
    status: 'ON_TRACK',
    trend: 'DOWN',
    frequency: 'MONTHLY',
    formula: '((Appraisal Cost + Prevention Cost + Internal Failure + External Claims) / Total FOB Turnover) * 100',
    desiredDirection: 'LOWER_IS_BETTER',
    toleranceThreshold: 0.2,
    description: 'Tracks full enterprise expenditure on defect prevention, lab tests, inspection labor, scrap, and customer allowances.',
    lastUpdated: '2026-09-20',
    history: [
      { id: 'h-401', period: 'Apr 2026', value: 1.48, target: 1.0, loggedBy: 'Finance Dept', remarks: 'Air freight penalties included' },
      { id: 'h-402', period: 'May 2026', value: 1.35, target: 1.0, loggedBy: 'Finance Dept' },
      { id: 'h-403', period: 'Jun 2026', value: 1.28, target: 1.0, loggedBy: 'Finance Dept' },
      { id: 'h-404', period: 'Jul 2026', value: 1.22, target: 1.0, loggedBy: 'Finance Dept' },
      { id: 'h-405', period: 'Aug 2026', value: 1.18, target: 1.0, loggedBy: 'Finance Dept' },
      { id: 'h-406', period: 'Sep 2026', value: 1.15, target: 1.0, loggedBy: 'Finance Dept', remarks: 'Consistent reduction via automated trimming' },
    ],
  },
  {
    id: 'kpi-005',
    kpiCode: 'KPI-DL-05',
    metricName: 'On-Time In-Full (OTIF) Shipment Delivery',
    category: 'DELIVERY',
    department: 'Supply Chain & Commercial',
    ownerName: 'Farhan Rahman (Commercial GM)',
    currentValue: 97.2,
    targetValue: 98.5,
    unit: '%',
    benchmark: '≥ 98.0% Global Retailer SLA',
    status: 'AT_RISK',
    trend: 'UP',
    frequency: 'MONTHLY',
    formula: '(Orders Shipped on Agreed Ex-Factory Date with 100% PO Qty / Total Purchase Orders) * 100',
    desiredDirection: 'HIGHER_IS_BETTER',
    toleranceThreshold: 1.0,
    description: 'Key customer satisfaction metric measuring on-time ex-factory handover for sea and air shipments.',
    lastUpdated: '2026-09-23',
    history: [
      { id: 'h-501', period: 'May 2026', value: 95.8, target: 98.5, sampleSize: 48, loggedBy: 'Farhan Rahman' },
      { id: 'h-502', period: 'Jun 2026', value: 96.4, target: 98.5, sampleSize: 52, loggedBy: 'Farhan Rahman' },
      { id: 'h-503', period: 'Jul 2026', value: 96.9, target: 98.5, sampleSize: 55, loggedBy: 'Farhan Rahman' },
      { id: 'h-504', period: 'Aug 2026', value: 97.0, target: 98.5, sampleSize: 60, loggedBy: 'Farhan Rahman' },
      { id: 'h-505', period: 'Sep 2026', value: 97.2, target: 98.5, sampleSize: 42, loggedBy: 'Farhan Rahman' },
    ],
    actionItems: [
      {
        id: 'act-kpi-3',
        task: 'Expedite dye lot shade matching with Apex Mills to shorten fabric lead time by 3 days',
        assignee: 'Kamrul Hassan (Fabric Sourcing GM)',
        department: 'Fabric Sourcing',
        dueDate: '2026-10-05',
        priority: 'HIGH',
        completed: false,
      },
    ],
  },
  {
    id: 'kpi-006',
    kpiCode: 'KPI-QA-06',
    metricName: 'Final Buyer Audit Pass Rate (AQL 1.5/2.5)',
    category: 'QUALITY',
    department: 'Final Audit & Pre-Shipment Inspection',
    ownerName: 'Sarah Jenkins (Quality Governance Specialist)',
    currentValue: 98.8,
    targetValue: 99.0,
    unit: '%',
    benchmark: '≥ 98.5% Six Sigma Track',
    status: 'ON_TRACK',
    trend: 'UP',
    frequency: 'WEEKLY',
    formula: '(First-Pass Buyer Final Audits / Total Buyer Final Audits Conducted) * 100',
    desiredDirection: 'HIGHER_IS_BETTER',
    toleranceThreshold: 0.5,
    description: 'Pass percentage in 3rd party (SGS, Intertek, Bureau Veritas) and Buyer designated QA pre-shipment inspections.',
    lastUpdated: '2026-09-24',
    history: [
      { id: 'h-601', period: 'Apr 2026', value: 97.5, target: 99.0, sampleSize: 40, loggedBy: 'Sarah Jenkins' },
      { id: 'h-602', period: 'May 2026', value: 98.0, target: 99.0, sampleSize: 45, loggedBy: 'Sarah Jenkins' },
      { id: 'h-603', period: 'Jun 2026', value: 98.2, target: 99.0, sampleSize: 44, loggedBy: 'Sarah Jenkins' },
      { id: 'h-604', period: 'Jul 2026', value: 98.5, target: 99.0, sampleSize: 50, loggedBy: 'Sarah Jenkins' },
      { id: 'h-605', period: 'Aug 2026', value: 98.6, target: 99.0, sampleSize: 52, loggedBy: 'Sarah Jenkins' },
      { id: 'h-606', period: 'Sep 2026', value: 98.8, target: 99.0, sampleSize: 38, loggedBy: 'Sarah Jenkins' },
    ],
  },
  {
    id: 'kpi-007',
    kpiCode: 'KPI-SF-07',
    metricName: 'Broken Needle & Metal Detection Incident Rate',
    category: 'SAFETY',
    department: 'Needle Control Room & Security',
    ownerName: 'Md. Delwar Hossain (Needle Control Officer)',
    currentValue: 0.0,
    targetValue: 0.0,
    unit: 'Incidents',
    benchmark: '0 Incidents Zero Tolerance Policy',
    status: 'ON_TRACK',
    trend: 'STABLE',
    frequency: 'DAILY',
    formula: 'Total Unaccounted Broken Needle Parts in Bulk Cartons',
    desiredDirection: 'LOWER_IS_BETTER',
    toleranceThreshold: 0.0,
    description: 'Mandatory baby-wear and children-wear safety compliance requiring 100% needle part recovery and 9-point metal detector passage.',
    lastUpdated: '2026-09-25',
    history: [
      { id: 'h-701', period: 'Jun 2026', value: 0, target: 0, sampleSize: 140000, loggedBy: 'Delwar Hossain' },
      { id: 'h-702', period: 'Jul 2026', value: 0, target: 0, sampleSize: 135000, loggedBy: 'Delwar Hossain' },
      { id: 'h-703', period: 'Aug 2026', value: 0, target: 0, sampleSize: 145000, loggedBy: 'Delwar Hossain' },
      { id: 'h-704', period: 'Sep 2026', value: 0, target: 0, sampleSize: 110000, loggedBy: 'Delwar Hossain' },
    ],
  },
  {
    id: 'kpi-008',
    kpiCode: 'KPI-QA-08',
    metricName: 'Fabric Inspection 4-Point System Pass Rate',
    category: 'QUALITY',
    department: 'Fabric Warehouse & Inspection Lab',
    ownerName: 'Rashedul Islam (Lab QA In-Charge)',
    currentValue: 96.5,
    targetValue: 97.0,
    unit: '%',
    benchmark: '≥ 96.0% ASTM D5430 Standard',
    status: 'ON_TRACK',
    trend: 'UP',
    frequency: 'DAILY',
    formula: '(Fabric Rolls with Penalty Points < 28 per 100 sq yds / Total Rolls Inspected) * 100',
    desiredDirection: 'HIGHER_IS_BETTER',
    toleranceThreshold: 1.0,
    description: 'Incoming greige and finished knit/woven fabric inspection under ASTM D5430 4-point penalty system.',
    lastUpdated: '2026-09-24',
    history: [
      { id: 'h-801', period: 'Jul 2026', value: 95.2, target: 97.0, sampleSize: 1800, loggedBy: 'Rashedul Islam' },
      { id: 'h-802', period: 'Aug 2026', value: 96.0, target: 97.0, sampleSize: 2100, loggedBy: 'Rashedul Islam' },
      { id: 'h-803', period: 'Sep 2026', value: 96.5, target: 97.0, sampleSize: 1650, loggedBy: 'Rashedul Islam' },
    ],
  },
];

export const KPI_CATEGORY_CONFIG: Record<
  string,
  { label: string; badgeClass: string; tone: 'blue' | 'emerald' | 'amber' | 'indigo' | 'purple' | 'rose' }
> = {
  QUALITY: {
    label: 'Quality Assurance',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
    tone: 'blue',
  },
  PRODUCTIVITY: {
    label: 'Plant Productivity',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    tone: 'emerald',
  },
  DELIVERY: {
    label: 'Supply Chain & Delivery',
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-200',
    tone: 'purple',
  },
  COST: {
    label: 'Cost & Efficiency',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
    tone: 'amber',
  },
  SAFETY: {
    label: 'Product Safety & Metal',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200',
    tone: 'rose',
  },
  COMPLIANCE: {
    label: 'Social & ESG Compliance',
    badgeClass: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    tone: 'indigo',
  },
};
