import { QualityGoal } from '@/lib/types/modules';

export const INITIAL_QUALITY_GOALS: QualityGoal[] = [
  {
    id: 'qg-001',
    goalCode: 'QG-2026-01',
    goalTitle: 'Achieve Zero Buyer Major Claims for A/W 2026 Season',
    pillar: 'CUSTOMER_SATISFACTION',
    department: 'Executive Quality & Merchandising',
    targetMetric: 'Customer Complaints Count',
    baseline: '7 Claims in 2025',
    target: '0 Major Claims (<2 Minor Allowed)',
    currentAchievement: '1 Minor Claim (Resolved with Credit Note)',
    percentageAchieved: 85,
    ownerName: 'Tanzim Ahmed (Head of Quality)',
    startDate: '2026-01-01',
    deadline: '2026-12-31',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    reviewCycle: 'QUARTERLY',
    lastReviewedDate: '2026-09-15',
    approvedBy: 'Engr. M. A. Jalil (Managing Director)',
    description: 'Executive mandate aligned with ISO 9001:2015 Clause 6.2 to eliminate commercial claims through rigorous pre-shipment lot verification and real-time shade band approvals.',
    milestones: [
      { id: 'm-1', title: 'Q1 Review: Deploy UV ink lot tracking across all cutting lines', targetDate: '2026-03-31', completed: true, completedDate: '2026-03-28', weightPercentage: 25 },
      { id: 'm-2', title: 'Q2 Review: Zero shade variance rejections in EU distribution hub', targetDate: '2026-06-30', completed: true, completedDate: '2026-06-25', weightPercentage: 25 },
      { id: 'm-3', title: 'Q3 Review: Complete customer satisfaction survey (>92% score)', targetDate: '2026-09-30', completed: true, completedDate: '2026-09-20', weightPercentage: 25 },
      { id: 'm-4', title: 'Q4 Final Audit: Zero open claims at year-end book closure', targetDate: '2026-12-31', completed: false, weightPercentage: 25 },
    ],
    actionPlans: [
      { id: 'ap-1', task: 'Implement mandatory dual-light (D65+TL84) matching for rib-to-body trims', assignee: 'Md. Al-Amin', department: 'Testing Lab', dueDate: '2026-10-15', completed: true, completedDate: '2026-09-18' },
      { id: 'ap-2', task: 'Establish 24-hour rapid CAPA response protocol for buyer regional alerts', assignee: 'Tanzim Ahmed', department: 'Quality Assurance', dueDate: '2026-10-31', completed: false },
    ],
  },
  {
    id: 'qg-002',
    goalCode: 'QG-2026-02',
    goalTitle: 'Reduce Denim Inseam Chainstitch Puckering Defect Rate by 40%',
    pillar: 'DEFECT_REDUCTION',
    department: 'Sewing Production (Line 03 & 04)',
    targetMetric: 'Specific Defect Frequency (DHU)',
    baseline: '3.4% on Line 03 (Denim)',
    target: '< 1.2% Puckering Rate',
    currentAchievement: '1.4% Rate achieved (58% Reduction)',
    percentageAchieved: 92,
    ownerName: 'Sarah Jenkins (Denim Specialist)',
    startDate: '2026-04-01',
    deadline: '2026-10-31',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    reviewCycle: 'MONTHLY',
    lastReviewedDate: '2026-09-22',
    approvedBy: 'Tanzim Ahmed (Head of Quality)',
    description: 'Targeted technical reduction of sewing feed-dog puckering and needle cut on heavy twill denim styles through mechanical retrofit and thread tension balancing.',
    milestones: [
      { id: 'm-201', title: 'Phase 1: Retrofit differential feed dogs on all 14 double-needle machines', targetDate: '2026-05-15', completed: true, completedDate: '2026-05-12', weightPercentage: 30 },
      { id: 'm-202', title: 'Phase 2: Switch to Groz-Beckert titanium GEBEDUR needles', targetDate: '2026-07-31', completed: true, completedDate: '2026-07-20', weightPercentage: 35 },
      { id: 'm-203', title: 'Phase 3: Maintain <1.2% puckering over 60 consecutive bulk production days', targetDate: '2026-10-31', completed: false, weightPercentage: 35 },
    ],
    actionPlans: [
      { id: 'ap-201', task: 'Audit silicone needle thread lubricant dispenser daily before morning shift start', assignee: 'Babul Akter', department: 'Maintenance', dueDate: '2026-10-01', completed: true, completedDate: '2026-09-21' },
      { id: 'ap-202', task: 'Calibrate tension meters on Line 03 machines 10 through 18', assignee: 'Babul Akter', department: 'Maintenance', dueDate: '2026-10-10', completed: false },
    ],
  },
  {
    id: 'qg-003',
    goalCode: 'QG-2026-03',
    goalTitle: '100% On-Time In-House Lab Test Turnaround (<24 Hours)',
    pillar: 'LAB_TESTING',
    department: 'Physical & Chemical Testing Lab',
    targetMetric: 'Lab Test Turnaround Time (TAT)',
    baseline: '36 Hours Average in 2025',
    target: '< 24 Hours SLA (100% Compliance)',
    currentAchievement: '19.4 Hours Average (Zero Delayed Reports)',
    percentageAchieved: 100,
    ownerName: 'Farhana Akhter (Lab Manager)',
    startDate: '2026-01-15',
    deadline: '2026-09-30',
    status: 'ACHIEVED',
    priority: 'HIGH',
    reviewCycle: 'MONTHLY',
    lastReviewedDate: '2026-09-24',
    approvedBy: 'Tanzim Ahmed (Head of Quality)',
    description: 'ISO 17025 accredited laboratory commitment to deliver fabric shrinkage, torque, color fastness, and pull-test reports within 24 hours of fabric arrival.',
    milestones: [
      { id: 'm-301', title: 'Install automated digital barcode sample intake scanner', targetDate: '2026-03-31', completed: true, completedDate: '2026-03-15', weightPercentage: 30 },
      { id: 'm-302', title: 'Commission second Wascator FOM 71 CLS accelerated washing machine', targetDate: '2026-06-30', completed: true, completedDate: '2026-06-10', weightPercentage: 40 },
      { id: 'm-303', title: 'Sustain <24 hour turnaround for 3 consecutive months', targetDate: '2026-09-30', completed: true, completedDate: '2026-09-22', weightPercentage: 30 },
    ],
    actionPlans: [
      { id: 'ap-301', task: 'Publish weekly lab report turnaround statistics on ERP quality portal', assignee: 'Farhana Akhter', department: 'Testing Lab', dueDate: '2026-09-30', completed: true, completedDate: '2026-09-24' },
    ],
  },
  {
    id: 'qg-004',
    goalCode: 'QG-2026-04',
    goalTitle: 'Achieve 98.5% First-Pass Buyer Final Audit Score Across All Brands',
    pillar: 'COMPLIANCE_STANDARDS',
    department: 'Final Audit & Quality Assurance',
    targetMetric: 'First-Pass Pre-Shipment Inspection Pass Rate',
    baseline: '96.2% Pass Rate in 2025',
    target: '≥ 98.5% First-Pass Rate',
    currentAchievement: '98.8% First-Pass Rate across 224 shipments',
    percentageAchieved: 100,
    ownerName: 'Sarah Jenkins (Quality Governance Specialist)',
    startDate: '2026-02-01',
    deadline: '2026-11-30',
    status: 'ACHIEVED',
    priority: 'CRITICAL',
    reviewCycle: 'MONTHLY',
    lastReviewedDate: '2026-09-20',
    approvedBy: 'Engr. M. A. Jalil (Managing Director)',
    description: 'Ensure pre-shipment inspections conducted by H&M, Zara, Target, and third parties (SGS, Intertek) pass with AQL 1.5/2.5 on first presentation without re-auditing.',
    milestones: [
      { id: 'm-401', title: 'Standardize 100% pre-final internal carton audit protocol', targetDate: '2026-04-30', completed: true, completedDate: '2026-04-18', weightPercentage: 35 },
      { id: 'm-402', title: 'Zero AQL critical failures over 100 shipments', targetDate: '2026-08-31', completed: true, completedDate: '2026-08-25', weightPercentage: 35 },
      { id: 'm-403', title: 'Achieve annual factory gold-tier accreditation from H&M and Next', targetDate: '2026-11-30', completed: true, completedDate: '2026-09-15', weightPercentage: 30 },
    ],
    actionPlans: [
      { id: 'ap-401', task: 'Implement digital tablet AQL sampling check at carton sealing stage', assignee: 'Md. Al-Amin', department: 'Finishing QA', dueDate: '2026-10-15', completed: true, completedDate: '2026-08-10' },
    ],
  },
  {
    id: 'qg-005',
    goalCode: 'QG-2026-05',
    goalTitle: 'Zero Needle Contamination: 100% Lock & Key Policy Compliance',
    pillar: 'COMPLIANCE_STANDARDS',
    department: 'Needle Control & Safety Inspection',
    targetMetric: 'Broken Needle Reconstitution Rate',
    baseline: '98.5% Reconstitution in 2025',
    target: '100% Zero-Failure Reconstitution',
    currentAchievement: '100% (14 out of 14 pieces reconstituted)',
    percentageAchieved: 95,
    ownerName: 'Md. Delwar Hossain (Needle Controller)',
    startDate: '2026-01-01',
    deadline: '2026-12-31',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    reviewCycle: 'MONTHLY',
    lastReviewedDate: '2026-09-24',
    approvedBy: 'Tanzim Ahmed (Head of Quality)',
    description: 'Ensure strict 100% compliance with retailer needle and metal safety policies. Every broken needle must be reconstituted on adhesive tape before issuing a replacement.',
    milestones: [
      { id: 'm-501', title: 'Replace manual logbooks with digital barcode needle dispensing kiosks', targetDate: '2026-04-30', completed: true, completedDate: '2026-04-20', weightPercentage: 35 },
      { id: 'm-502', title: 'Audit 9-point metal detector calibration logs daily without failure', targetDate: '2026-08-31', completed: true, completedDate: '2026-08-28', weightPercentage: 35 },
      { id: 'm-503', title: 'Maintain 100% annual broken needle tape audit verification', targetDate: '2026-12-31', completed: false, weightPercentage: 30 },
    ],
    actionPlans: [
      { id: 'ap-501', task: 'Conduct bi-weekly surprise metal detector sensitivity verification using 1.0mm Fe sphere', assignee: 'Md. Delwar Hossain', department: 'Needle Control', dueDate: '2026-10-15', completed: false },
    ],
  },
  {
    id: 'qg-006',
    goalCode: 'QG-2026-06',
    goalTitle: 'Reduce Fabric Splicing Loss in Cutting Room Below 1.2%',
    pillar: 'PROCESS_EFFICIENCY',
    department: 'Cutting Department',
    targetMetric: 'Fabric Splicing & End-Bit Wastage (%)',
    baseline: '2.4% Loss in 2025',
    target: '< 1.2% Splicing Loss',
    currentAchievement: '1.6% Loss achieved',
    percentageAchieved: 70,
    ownerName: 'Kabir Hossain (Chief Cutting Master)',
    startDate: '2026-03-01',
    deadline: '2026-11-30',
    status: 'BEHIND',
    priority: 'MEDIUM',
    reviewCycle: 'MONTHLY',
    lastReviewedDate: '2026-09-18',
    approvedBy: 'Engr. M. A. Jalil (Managing Director)',
    description: 'Optimize fabric utilization by introducing laser-guided roll-end splicing and automatic nesting algorithms on automated spreading tables.',
    milestones: [
      { id: 'm-601', title: 'Install laser alignment guides on spreader table #3 & #4', targetDate: '2026-05-31', completed: true, completedDate: '2026-05-22', weightPercentage: 30 },
      { id: 'm-602', title: 'Implement roll-end remnant fabric bundling procedure', targetDate: '2026-08-31', completed: true, completedDate: '2026-08-15', weightPercentage: 35 },
      { id: 'm-603', title: 'Reach sustained <1.2% splicing loss for knit single jersey styles', targetDate: '2026-11-30', completed: false, weightPercentage: 35 },
    ],
    actionPlans: [
      { id: 'ap-601', task: 'Retrain fabric spreading operators on roll-end overlap tolerances (max 2 inches)', assignee: 'Kabir Hossain', department: 'Cutting Room', dueDate: '2026-10-05', completed: false },
    ],
  },
];

export const GOAL_PILLAR_CONFIG: Record<
  string,
  { label: string; badgeClass: string; tone: 'blue' | 'emerald' | 'amber' | 'indigo' | 'purple' | 'rose' }
> = {
  CUSTOMER_SATISFACTION: {
    label: 'Customer Satisfaction',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
    tone: 'blue',
  },
  DEFECT_REDUCTION: {
    label: 'Defect Reduction',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    tone: 'emerald',
  },
  PROCESS_EFFICIENCY: {
    label: 'Process Efficiency',
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-200',
    tone: 'purple',
  },
  COMPLIANCE_STANDARDS: {
    label: 'Compliance & Safety',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200',
    tone: 'rose',
  },
  LAB_TESTING: {
    label: 'Lab & Testing Speed',
    badgeClass: 'bg-cyan-50 text-cyan-700 border-cyan-200',
    tone: 'blue',
  },
  SUSTAINABILITY: {
    label: 'ESG & Sustainability',
    badgeClass: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    tone: 'indigo',
  },
};
