import { JobDescriptionItem } from '@/lib/types/modules';

export const INITIAL_JOB_DESCRIPTIONS: JobDescriptionItem[] = [
  {
    id: 'jd-1',
    roleCode: 'JD-QA-01',
    title: 'Head of Quality Assurance (QMS Director)',
    department: 'Quality Assurance',
    level: 'L7 Director',
    incumbentName: 'Tanzim Ahmed',
    companyIdNo: 'EMP-2020-0042',
    supervisorName: 'Engr. Tariqul Islam',
    supervisorTitle: 'VP of Manufacturing & Quality Assurance',
    supervisorIdNo: 'EMP-2018-0001',
    status: 'ACTIVE',
    employmentType: 'FULL_TIME',
    educationRequirement: 'B.Sc. in Textile Engineering / M.Sc. in Quality Management',
    experienceYears: 12,
    workstationLocation: 'Central QMS Tower 2, 3rd Floor',
    effectiveDate: '2024-01-15',
    revision: 'Rev 4.0',
    approvedBy: 'Managing Director & CEO',
    isoClauseMapping: [
      'ISO 9001:2015 Clause 5.3 (Organizational Roles, Responsibilities & Authorities)',
      'ISO 9001:2015 Clause 7.2 (Competence)',
      'ISO 9001:2015 Clause 9.2 (Internal Audit)',
      'ISO 9001:2015 Clause 10.2 (Nonconformity & Corrective Action)',
    ],
    decisionAuthority:
      'Autonomous corporate authority to mandate plant-wide line stops, reject defective fabric lots exceeding 28 penalty points, and authorize buyer final inspection certificates.',
    keyResponsibilities: [
      'Maintain corporate adherence to ISO 9001:2015, OEKO-TEX Standard 100, and Higg Index requirements.',
      'Lead a division of 65+ quality managers, laboratory technologists, and roving in-line quality auditors.',
      'Represent the factory during third-party buyer audits (Inditex, H&M, PVH, Target) and resolve major non-conformances.',
      'Formulate annual quality objective targets and review monthly factory DHU against the benchmark (<2.5%).',
      'Oversee the execution of 8D Corrective Action Preventative Action (CAPA) investigations.',
    ],
    technicalSkills: [
      'ISO 9001 Lead Auditor',
      'Six Sigma Green/Black Belt',
      'Statistical Process Control (SPC)',
      'AQL 1.5/2.5 Sampling Inspection',
      'Buyer Technical Protocol Mastery',
    ],
    certificationsRequired: [
      'IRCA Certified ISO 9001:2015 Lead Auditor',
      'ASQ Certified Quality Manager (CQM)',
      'Lean Six Sigma Green Belt',
    ],
    kpiMetrics: [
      { kpiName: 'Factory First-Time-Through (FTT) Rate', target: '≥ 96.5%', measurementFrequency: 'Monthly' },
      { kpiName: 'Buyer Final Audit Pass Rate', target: '≥ 98.8%', measurementFrequency: 'Per Shipment' },
      { kpiName: 'Customer Complaints & Claims', target: 'Zero Major Claims', measurementFrequency: 'Quarterly' },
    ],
    reportingSubordinates: [
      'Fabric & Testing Lab Manager',
      'Cutting Quality In-Charge',
      'Sewing Line Quality In-Charge',
      'Finishing & AQL Lead Inspector',
      'Internal QMS Lead Auditor',
    ],
    notes: 'Primary executive auditee during annual ISO 9001 surveillance and buyer technical compliance evaluations.',
    createdAt: '2023-01-01T08:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'jd-2',
    roleCode: 'JD-LAB-01',
    title: 'Central Fabric & Chemical Lab Manager',
    department: 'Fabric Laboratory & Testing',
    level: 'L5 Manager',
    incumbentName: 'Farida Yasmin',
    companyIdNo: 'EMP-2021-0118',
    supervisorName: 'Tanzim Ahmed',
    supervisorTitle: 'Head of Quality Assurance (QMS Director)',
    supervisorIdNo: 'EMP-2020-0042',
    status: 'ACTIVE',
    employmentType: 'FULL_TIME',
    educationRequirement: 'B.Sc. in Textile Chemistry / Chemical Engineering',
    experienceYears: 7,
    workstationLocation: 'Central Testing Laboratory, Building B',
    effectiveDate: '2024-03-01',
    revision: 'Rev 3.1',
    approvedBy: 'Head of Quality Assurance',
    isoClauseMapping: [
      'ISO 9001:2015 Clause 7.1.5 (Monitoring & Measuring Resources)',
      'ISO 17025:2017 (General Requirements for Testing Laboratories)',
      'ZDHC MRSL v3.1 (Chemical Management & Wastewater)',
    ],
    decisionAuthority:
      'Sole authorization to release raw fabric batches from quarantine into production cutting based on colorfastness, shrinkage, and GSM pass results.',
    keyResponsibilities: [
      'Supervise physical and chemical testing including wash fastness, rub fastness, tear strength, and pilling resistance.',
      'Operate spectrophotometer systems for digital color tolerance evaluations (Delta-E CMC 2:1 < 0.8).',
      'Maintain ISO 17025 laboratory calibration schedules for all tensile testers, Crockmeters, and light booths.',
      'Audit washing unit chemical recipes against ZDHC MRSL Level 3 compliance standards.',
    ],
    technicalSkills: [
      'Spectrophotometer & Datacolor Software',
      'Color Fastness Testing (ISO/AATCC)',
      'Fabric Tensile & Tear Testing (ASTM)',
      'ZDHC Gateway & Chemical Management',
      'Light Box Color Evaluation (D65/TL84)',
    ],
    certificationsRequired: [
      'Munsell 100 Hue Color Vision Test (Grade Superior)',
      'AATCC Certified Lab Technician',
      'ZDHC Chemical Manager Certification',
    ],
    kpiMetrics: [
      { kpiName: 'Lab Test Turnaround Time', target: '≤ 24 Hours', measurementFrequency: 'Daily' },
      { kpiName: 'Color Shade Batch Pass Rate', target: '≥ 97.0%', measurementFrequency: 'Weekly' },
      { kpiName: 'Equipment Calibration Adherence', target: '100% On-time', measurementFrequency: 'Monthly' },
    ],
    reportingSubordinates: [
      'Senior Physical Testing Technician',
      'Chemical & Wash Fastness Analyst',
      'Sample Colorist',
    ],
    notes: 'Laboratory holds valid accreditation from Inditex and H&M nominated third-party auditor bodies.',
    createdAt: '2023-02-10T08:00:00Z',
    updatedAt: '2026-02-10T11:30:00Z',
  },
  {
    id: 'jd-3',
    roleCode: 'JD-CUT-01',
    title: 'Spreading & Cutting Quality In-Charge',
    department: 'Cutting Division',
    level: 'L4 Section Head',
    incumbentName: 'Zahid Hasan',
    companyIdNo: 'EMP-2022-0245',
    supervisorName: 'Tanzim Ahmed',
    supervisorTitle: 'Head of Quality Assurance (QMS Director)',
    supervisorIdNo: 'EMP-2020-0042',
    status: 'ACTIVE',
    employmentType: 'FULL_TIME',
    educationRequirement: 'Diploma / B.Sc. in Garments Manufacturing Technology',
    experienceYears: 6,
    workstationLocation: 'Main Plant, 1st Floor Cutting Floor',
    effectiveDate: '2024-02-15',
    revision: 'Rev 2.5',
    approvedBy: 'Head of Quality Assurance',
    isoClauseMapping: [
      'ISO 9001:2015 Clause 8.5.1 (Control of Production and Service Provision)',
      'ISO 9001:2015 Clause 8.5.2 (Identification and Traceability)',
    ],
    decisionAuthority:
      'Unilateral authority to stop automated or manual fabric spreading if ply tension, end loss, or shade variation across plies exceeds 1/8 inch tolerance.',
    keyResponsibilities: [
      'Verify fabric roll relaxation times (minimum 24 hours for knit fabrics) prior to precision marker laying.',
      'Conduct 100% check of marker matching against master pattern grain lines, notches, and shrinkage allowances.',
      'Perform ply numbering audits to prevent shade mixing across garment bundle assemblies.',
      'Check top, middle, and bottom cut plies using contour templates for perimeter deviation (< 1.0mm).',
      'Inspect fusing machine temperature, pressure, and dwell time parameters with hourly peel-strength tests.',
    ],
    technicalSkills: [
      'ASTM D5430 4-Point Fabric Inspection',
      'Gerber / Lectra Automated Cutting Systems',
      'Cut Piece Measurement Tolerances',
      'Interlining Fusing Peel-Strength Testing',
      'Bundle Shade Sorting Control',
    ],
    certificationsRequired: [
      'Garment Pattern & Cutting Quality Certificate',
      'Industrial Safety & Mesh Glove Handling',
    ],
    kpiMetrics: [
      { kpiName: 'Cut Panel Measurement Accuracy', target: '≥ 99.2%', measurementFrequency: 'Daily' },
      { kpiName: 'Bundle Shade Mixing Incidents', target: 'Zero Incidents', measurementFrequency: 'Monthly' },
      { kpiName: 'Fabric Utilization Yield Ratio', target: '≥ 85.5%', measurementFrequency: 'Weekly' },
    ],
    reportingSubordinates: [
      'Spreading Quality Inspector',
      'Cut Panel Auditor',
      'Fusing Machine Quality Checker',
    ],
    notes: 'Directly ensures 100% traceability barcodes are attached to all cut bundles before sewing release.',
    createdAt: '2023-03-01T08:00:00Z',
    updatedAt: '2026-02-15T09:15:00Z',
  },
  {
    id: 'jd-4',
    roleCode: 'JD-SEW-01',
    title: 'Senior Sewing Line Quality In-Charge',
    department: 'Sewing Production Lines',
    level: 'L4 Section Head',
    incumbentName: 'Mohammad Ali',
    companyIdNo: 'EMP-2021-0312',
    supervisorName: 'Tanzim Ahmed',
    supervisorTitle: 'Head of Quality Assurance (QMS Director)',
    supervisorIdNo: 'EMP-2020-0042',
    status: 'ACTIVE',
    employmentType: 'FULL_TIME',
    educationRequirement: 'Diploma in Textile / Apparel Technology',
    experienceYears: 8,
    workstationLocation: 'Sewing Floor 2, Lines 1-12',
    effectiveDate: '2024-01-20',
    revision: 'Rev 3.0',
    approvedBy: 'Head of Quality Assurance',
    isoClauseMapping: [
      'ISO 9001:2015 Clause 8.5.1 (Control of Production)',
      'ISO 9001:2015 Clause 8.6 (Release of Products and Services)',
      'ISO 9001:2015 Clause 8.7 (Control of Nonconforming Outputs)',
    ],
    decisionAuthority:
      'Unilateral authority to trigger line-stop and red-tag sewing machines upon detecting 3 consecutive sewing defects on any single operation.',
    keyResponsibilities: [
      'Conduct hourly roving 7-piece quality audits on active sewing lines using standardized traffic light boards.',
      'Audit SPI (Stitches Per Inch), seam tension, thread trimming, and critical seam margin allowances.',
      'Enforce strict 9-point broken needle policy: ensure 100% of broken needle pieces are recovered before replacement.',
      'Verify first-output mockups against approved golden sample and tech pack prior to line handoff.',
      'Organize immediate line retraining for sewing operators generating DHU > 3.5%.',
    ],
    technicalSkills: [
      'Seam Engineering & SPI Measurement',
      'Traffic Light In-line Audit System',
      'Root Cause Problem Solving (5-Why)',
      '9-Point Broken Needle Log System',
      'AQL In-Process Sampling Protocols',
    ],
    certificationsRequired: [
      'Certified In-Line Sewing Quality Controller',
      'Needle Safety & Contamination Officer',
    ],
    kpiMetrics: [
      { kpiName: 'Sewing End-of-Line DHU', target: '< 2.2%', measurementFrequency: 'Daily' },
      { kpiName: 'First-Hour Production Pass Rate', target: '≥ 95.0%', measurementFrequency: 'Daily' },
      { kpiName: 'Line-Stop Response & Clearance Time', target: '< 15 Minutes', measurementFrequency: 'Weekly' },
    ],
    reportingSubordinates: [
      'Line 1-6 Roving QC Inspectors',
      'Line 7-12 Roving QC Inspectors',
      'End-of-Line 100% Table Auditors',
    ],
    notes: 'Key field leader responsible for daily floor communication of buyer quality specifications.',
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2026-01-20T14:40:00Z',
  },
  {
    id: 'jd-5',
    roleCode: 'JD-FIN-01',
    title: 'Finishing, Packing & AQL Lead Inspector',
    department: 'Finishing & Export Packing',
    level: 'L4 Section Head',
    incumbentName: 'Nasreen Akter',
    companyIdNo: 'EMP-2022-0401',
    supervisorName: 'Tanzim Ahmed',
    supervisorTitle: 'Head of Quality Assurance (QMS Director)',
    supervisorIdNo: 'EMP-2020-0042',
    status: 'ACTIVE',
    employmentType: 'FULL_TIME',
    educationRequirement: 'Bachelor Degree in Science / Business / Apparel',
    experienceYears: 7,
    workstationLocation: 'Finishing & Packaging Hall, Floor 3',
    effectiveDate: '2024-04-01',
    revision: 'Rev 2.8',
    approvedBy: 'Head of Quality Assurance',
    isoClauseMapping: [
      'ISO 9001:2015 Clause 8.5.4 (Preservation of Outputs)',
      'ISO 9001:2015 Clause 8.6 (Release of Products and Services)',
    ],
    decisionAuthority:
      'Final factory sign-off authority to approve carton sealing, issue Pre-Final Internal Audit clearance, or quarantine export shipments failing AQL 1.5.',
    keyResponsibilities: [
      'Perform rigorous pre-final AQL 1.5/2.5 random sampling audits prior to booking buyer third-party inspectors.',
      'Supervise 100% garment metal detector scanning and verify 1.0mm ferrous test card hourly calibration.',
      'Check garment pressing quality, shine marks, moisture content (< 12%), and barcode polybag labeling.',
      'Audit export carton drop testing, carton dimensional integrity, and gross weight verification.',
      'Issue internal Inspection Certificates (IC) certifying consignment readiness for shipping release.',
    ],
    technicalSkills: [
      'ISO 2859-1 / ANSI ASQ Z1.4 AQL Sampling',
      'Metal Detection 9-Zone Tunnel Calibration',
      'Barcode Verification & GTIN Scan Checking',
      'Moisture Meter Testing (Aqua-Boy)',
      'Carton Drop Test & Packaging Standards',
    ],
    certificationsRequired: [
      'Certified Final AQL Garment Auditor (PVH / Inditex Accredited)',
      'Metal Detector Safety Officer',
    ],
    kpiMetrics: [
      { kpiName: 'Pre-Shipment Buyer Audit First-Pass Rate', target: '≥ 99.0%', measurementFrequency: 'Monthly' },
      { kpiName: 'Metal Contamination Escapes', target: 'Zero Tolerance (0)', measurementFrequency: 'Annual' },
      { kpiName: 'Packaging & Barcode Label Accuracy', target: '100%', measurementFrequency: 'Daily' },
    ],
    reportingSubordinates: [
      'AQL Sampling Inspectors',
      'Metal Detector Operators',
      'Carton Audit Checkers',
    ],
    notes: 'Direct liaison for external third-party inspection agencies (SGS, Intertek, Bureau Veritas, QIMA).',
    createdAt: '2023-04-01T08:00:00Z',
    updatedAt: '2026-04-01T16:10:00Z',
  },
  {
    id: 'jd-6',
    roleCode: 'JD-AUD-01',
    title: 'Lead Internal QMS Auditor',
    department: 'Internal Audit & Compliance',
    level: 'L5 Manager',
    incumbentName: 'Md. Rafiqul Islam',
    companyIdNo: 'EMP-2020-0089',
    supervisorName: 'Tanzim Ahmed',
    supervisorTitle: 'Head of Quality Assurance (QMS Director)',
    supervisorIdNo: 'EMP-2020-0042',
    status: 'ACTIVE',
    employmentType: 'FULL_TIME',
    educationRequirement: 'B.Sc. in Industrial Engineering / MBA in Operations Management',
    experienceYears: 10,
    workstationLocation: 'Compliance & Audit Office, Room 204',
    effectiveDate: '2024-01-10',
    revision: 'Rev 3.5',
    approvedBy: 'Managing Director & CEO',
    isoClauseMapping: [
      'ISO 9001:2015 Clause 9.2 (Internal Audit)',
      'ISO 19011:2018 (Guidelines for Auditing Management Systems)',
      'ISO 9001:2015 Clause 10.2 (Corrective Action)',
    ],
    decisionAuthority:
      'Autonomous authority to issue formal Corrective Action Requests (CAR) across any manufacturing department and independently escalate non-compliance to the Managing Director.',
    keyResponsibilities: [
      'Formulate and execute the annual Factory Internal QMS Audit Schedule covering all operational sections.',
      'Ensure complete operational independence from departments under audit per ISO 19011 standards.',
      'Log audit findings, categorize non-conformances (Major, Minor, Observation), and monitor 30-day corrective action closures.',
      'Prepare comprehensive management review inputs for semi-annual executive board meetings.',
      'Train internal audit team members and conduct mock audits prior to buyer accreditation renewals.',
    ],
    technicalSkills: [
      'ISO 19011 Auditing Methodology',
      '8D Root Cause Analysis & 5-Why Matrix',
      'Risk Assessment & FMEA Review',
      'Audit Checklist Design & Scoring',
      'Process Interaction Mapping',
    ],
    certificationsRequired: [
      'IRCA Certified ISO 9001:2015 Lead Auditor',
      'Lead Auditor ISO 14001:2015 (Environmental)',
    ],
    kpiMetrics: [
      { kpiName: 'Annual Audit Schedule Completion Rate', target: '100%', measurementFrequency: 'Annual' },
      { kpiName: 'CAPA On-Time Closure Rate', target: '≥ 95.0%', measurementFrequency: 'Monthly' },
      { kpiName: 'Repeat Audit Non-Conformances', target: '≤ 5%', measurementFrequency: 'Quarterly' },
    ],
    reportingSubordinates: [
      'Internal Audit Officers (3)',
      'CAPA Tracking Coordinator',
    ],
    notes: 'Audit reports are directly shared with the Executive Board and documented in the ERP Audit Log.',
    createdAt: '2023-01-01T08:00:00Z',
    updatedAt: '2026-01-10T12:00:00Z',
  },
  {
    id: 'jd-7',
    roleCode: 'JD-NDL-01',
    title: 'Needle Detection & Calibration Officer',
    department: 'Finishing & Export Packing',
    level: 'L3 Specialist',
    incumbentName: 'Kamal Hossain',
    companyIdNo: 'EMP-2023-0511',
    supervisorName: 'Nasreen Akter',
    supervisorTitle: 'Finishing, Packing & AQL Lead Inspector',
    supervisorIdNo: 'EMP-2022-0401',
    status: 'ACTIVE',
    employmentType: 'FULL_TIME',
    educationRequirement: 'Diploma in Electrical / Mechanical / Garments Technology',
    experienceYears: 4,
    workstationLocation: 'Metal Detection Quarantine Station, 3rd Floor',
    effectiveDate: '2024-05-01',
    revision: 'Rev 2.0',
    approvedBy: 'Head of Quality Assurance',
    isoClauseMapping: [
      'ISO 9001:2015 Clause 7.1.5 (Monitoring and Measuring Resources)',
      'ISO 9001:2015 Clause 8.5.1 (Control of Production)',
    ],
    decisionAuthority:
      'Full authority to halt packing operations and quarantine any batch passing through metal detection if 1.0mm ferrous test card fails 9-point calibration trigger.',
    keyResponsibilities: [
      'Execute calibration checks on conveyor metal detectors using certified 1.0mm Ferrous test cards every 2 hours.',
      'Maintain the broken needle locked register box: collect, examine, and physically reassemble 100% of broken needle fragments.',
      'Supervise handheld magnetic wand scanning on garments triggering the conveyor alarm.',
      'Segregate and record all contaminated garments in the secure red lockup box.',
      'Generate daily metal detector calibration certificates countersigned by the Finishing Manager.',
    ],
    technicalSkills: [
      'Conveyor Tunnel Metal Detector Calibration',
      'Handheld Ferrous Magnetic Wand Inspection',
      'Broken Needle Fragment Microscopic Matching',
      'Quarantine Log Record Keeping',
    ],
    certificationsRequired: [
      'Buyer Certified Metal Detector & Needle Safety Officer',
    ],
    kpiMetrics: [
      { kpiName: 'Calibration Verification Compliance', target: '100% Every 2 Hours', measurementFrequency: 'Daily' },
      { kpiName: 'False Alarm Rate Calibration', target: '< 0.5%', measurementFrequency: 'Weekly' },
      { kpiName: 'Broken Needle Fragment Recovery Rate', target: '100% Complete', measurementFrequency: 'Daily' },
    ],
    reportingSubordinates: [],
    notes: 'Mandatory role for all US and European childrenswear and infant apparel export orders.',
    createdAt: '2023-05-01T08:00:00Z',
    updatedAt: '2026-05-01T15:20:00Z',
  },
  {
    id: 'jd-8',
    roleCode: 'JD-SPL-01',
    title: 'Pre-Production & Sample Quality Technologist',
    department: 'Sample Development & Pre-Production',
    level: 'L4 Section Head',
    incumbentName: 'Shahidul Islam',
    companyIdNo: 'EMP-2022-0388',
    supervisorName: 'Tanzim Ahmed',
    supervisorTitle: 'Head of Quality Assurance (QMS Director)',
    supervisorIdNo: 'EMP-2020-0042',
    status: 'ACTIVE',
    employmentType: 'FULL_TIME',
    educationRequirement: 'B.Sc. in Textile & Apparel Technology',
    experienceYears: 6,
    workstationLocation: 'Central Sample Room & Technical Center',
    effectiveDate: '2024-03-15',
    revision: 'Rev 2.2',
    approvedBy: 'Head of Quality Assurance',
    isoClauseMapping: [
      'ISO 9001:2015 Clause 8.3 (Design and Development of Products and Services)',
      'ISO 9001:2015 Clause 8.2 (Requirements for Products and Services)',
    ],
    decisionAuthority:
      'Sign-off authority on Size Set and Pre-Production (PP) sample quality approval certificates before bulk cutting clearance.',
    keyResponsibilities: [
      'Construct size set samples across all graded sizes to verify measurement balance, fit, and seam construction.',
      'Identify manufacturing vulnerabilities in new buyer tech packs and formulate preventative sewing guides.',
      'Lead technical risk evaluations during Pre-Production Meetings (PPM) with cutting, sewing, and merchandiser leads.',
      'Produce signed "Golden Seal Samples" with tamper-proof tags for sewing line benchmark reference.',
    ],
    technicalSkills: [
      'Sample Room Quality Control',
      'Garment Fit Analysis & Size Grading',
      'Pre-Production Risk Evaluation',
      'Tech Pack Technical Deconstruction',
    ],
    certificationsRequired: [
      'Garment Pattern & Fit Specialist Certificate',
    ],
    kpiMetrics: [
      { kpiName: 'First-Submission Sample Approval Rate', target: '≥ 92.0%', measurementFrequency: 'Monthly' },
      { kpiName: 'Pre-Production Meeting On-Time Execution', target: '100%', measurementFrequency: 'Weekly' },
      { kpiName: 'Golden Sample Delivery Lead Time', target: '≤ 3 Days', measurementFrequency: 'Per Style' },
    ],
    reportingSubordinates: [
      'Sample Fit Technicians',
      'Pattern Verification Drafters',
    ],
    notes: 'Acts as the technical bridge between buyer merchandisers and factory production lines.',
    createdAt: '2023-03-15T08:00:00Z',
    updatedAt: '2026-03-15T11:00:00Z',
  },
];
