import { QualityManualSection } from '@/lib/types/modules';

export const INITIAL_QUALITY_MANUAL_SECTIONS: QualityManualSection[] = [
  {
    id: 'qm-1',
    chapterNumber: 'QM-01',
    title: 'Context of the Organization, Scope & Quality Management Framework',
    clauseReference: 'ISO 9001:2015 Clause 4.1 - 4.4',
    summary:
      'Defines internal/external context, interested parties (buyers, workers, regulatory bodies), and operational scope covering woven, knitwear, and denim apparel manufacturing lines.',
    responsibleDepartment: 'Executive Board & Compliance',
    status: 'ACTIVE',
    version: 'Rev 4.2',
    effectiveDate: '2025-01-15',
    nextReviewDate: '2026-01-14',
    approvedBy: 'Managing Director & CEO',
    author: 'Head of Quality Assurance',
    reviewedBy: 'General Manager Operations',
    scope:
      'Applies to corporate headquarters, Central Fabric Laboratory, Cutting Units 1-4, Sewing Plants A-D, and Central Export Packing Warehouse.',
    isoStandard: 'ISO 9001:2015 / ISO 14001:2015',
    confidentiality: 'GENERAL_FACILITY',
    policyCommitments: [
      'Identify and mitigate operational and supply-chain quality risks systematically across all manufacturing lines.',
      'Ensure 100% compliance with buyer codes of conduct, REACH standards, and zero hazardous discharge guidelines.',
      'Maintain an unbroken chain of traceability from raw greige yarn inward to export carton dispatch.',
      'Conduct bi-annual management reviews to calibrate QMS objectives against factory delivery benchmarks.',
    ],
    complianceRequirements: [
      {
        id: 'comp-101',
        requirement: 'Annual formal review of internal and external issues influencing factory quality',
        verificationMethod: 'SWOT Analysis & Risk Register documentation',
        frequency: 'Annual',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-102',
        requirement: 'Interested party expectations matrix maintained and signed by Department Heads',
        verificationMethod: 'Buyer Audit Log & Stakeholder Review Record',
        frequency: 'Bi-Annual',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-103',
        requirement: 'Process interaction map displayed in all operational production floors',
        verificationMethod: 'Floor Inspection & Visual QMS Board verification',
        frequency: 'Quarterly',
        status: 'COMPLIANT',
      },
    ],
    linkedDocuments: [
      { docNumber: 'DOC-QMS-001', title: 'Quality Management System Policy Manual', docType: 'POLICY' },
      { docNumber: 'PRC-CUT-01', title: 'Fabric Spreading & Natural Relaxation Protocol', docType: 'PROCEDURE' },
      { docNumber: 'SOP-QMS-02', title: 'Internal Quality Audit Standard Operating Procedure', docType: 'SOP' },
    ],
    revisionHistory: [
      {
        revision: 'Rev 4.2',
        changeDate: '2025-01-15',
        changedBy: 'Tanzim Ahmed (QA Director)',
        description: 'Updated interested parties matrix to reflect new EU Corporate Sustainability Due Diligence criteria.',
      },
      {
        revision: 'Rev 4.1',
        changeDate: '2024-03-10',
        changedBy: 'Farhan Rahman (Merchandiser)',
        description: 'Expanded operational scope to incorporate automated circular knitting division.',
      },
    ],
    notes: 'Approved without audit observations during the recent SGS Re-certification Audit.',
    createdAt: '2023-01-01T08:00:00Z',
    updatedAt: '2026-01-15T09:30:00Z',
  },
  {
    id: 'qm-2',
    chapterNumber: 'QM-02',
    title: 'Leadership Commitment, Quality Policy & Organizational Roles',
    clauseReference: 'ISO 9001:2015 Clause 5.1 - 5.3',
    summary:
      'Executive declaration that customer satisfaction, zero-defect culture, line-stop authority, and continuous improvement are supreme operational priorities across all shifts.',
    responsibleDepartment: 'Executive Board',
    status: 'ACTIVE',
    version: 'Rev 4.0',
    effectiveDate: '2025-02-01',
    nextReviewDate: '2026-02-01',
    approvedBy: 'Engr. Tariqul Islam (VP Operations)',
    author: 'QA Director',
    reviewedBy: 'Head of Human Resources',
    scope: 'All executive managers, department heads, line supervisors, and quality controllers.',
    isoStandard: 'ISO 9001:2015 Clause 5',
    confidentiality: 'PUBLIC_POLICY',
    policyCommitments: [
      'Customer focus is paramount: Every garment shipped must strictly adhere to buyer AQL 1.5/2.5 specifications.',
      'Total Quality Empowerment: Operators and roving QC inspectors hold unilateral Stop-the-Line authority upon detecting 3 consecutive sewing defects.',
      'Zero tolerance for unauthorized fabric substitution, non-standard sewing thread, or altered marker layouts.',
      'Annual KPI goals linked directly to first-time-through (FTT) sewing pass rate above 96.5%.',
    ],
    complianceRequirements: [
      {
        id: 'comp-201',
        requirement: 'Quality Policy translated into Bengali and visibly displayed at all entry gates & workstations',
        verificationMethod: 'Physical plant audit & random operator interviews',
        frequency: 'Monthly',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-202',
        requirement: 'Executive management presence at weekly quality review & AQL trend meetings',
        verificationMethod: 'Management Review Minutes signed by VP Operations',
        frequency: 'Weekly',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-203',
        requirement: 'Defined job descriptions and decision authority matrix signed for all QA personnel',
        verificationMethod: 'HR Personnel Records & Organogram role verification',
        frequency: 'Annual',
        status: 'COMPLIANT',
      },
    ],
    linkedDocuments: [
      { docNumber: 'DOC-POL-005', title: 'Corporate Zero-Defect Quality Policy Declaration', docType: 'POLICY' },
      { docNumber: 'ORG-QA-2026', title: 'Garments QA Division Organogram & Reporting Line', docType: 'POLICY' },
      { docNumber: 'SOP-STP-01', title: 'Defect Escalation & Immediate Line-Stop Procedure', docType: 'SOP' },
    ],
    revisionHistory: [
      {
        revision: 'Rev 4.0',
        changeDate: '2025-02-01',
        changedBy: 'Engr. Tariqul Islam',
        description: 'Codified unilateral line-stop authority for roving quality inspectors.',
      },
    ],
    notes: 'Mandatory reading for all newly inducted staff during initial QA onboarding orientation.',
    createdAt: '2023-01-01T08:00:00Z',
    updatedAt: '2026-02-01T11:00:00Z',
  },
  {
    id: 'qm-3',
    chapterNumber: 'QM-03',
    title: 'Planning, Quality Objectives & Risk-Based Management',
    clauseReference: 'ISO 9001:2015 Clause 6.1 - 6.3',
    summary:
      'Protocols for identifying operational risks (fabric shade variation, shrinkage, needle breakage, machine breakdown) and formulating pre-production FMEA mitigation action plans.',
    responsibleDepartment: 'Industrial Engineering & QA',
    status: 'ACTIVE',
    version: 'Rev 3.5',
    effectiveDate: '2025-03-01',
    nextReviewDate: '2026-03-01',
    approvedBy: 'Plant Director',
    author: 'Head of Industrial Engineering',
    reviewedBy: 'Technical Manager',
    scope: 'Pre-production planning, sample development, technical risk assessment, and change management.',
    isoStandard: 'ISO 9001:2015 Clause 6',
    confidentiality: 'INTERNAL_RESTRICTED',
    policyCommitments: [
      'Failure Mode and Effects Analysis (FMEA) must be executed for every new buyer style prior to bulk cutting.',
      'Measurable departmental quality objectives established annually with monthly progress tracking.',
      'Any engineering change in sewing machinery, seam construction, or thread tension requires formal pilot approval.',
    ],
    complianceRequirements: [
      {
        id: 'comp-301',
        requirement: 'Pre-production risk meeting convened with Merchandising, Cutting, Sewing, and Quality Leads',
        verificationMethod: 'Pre-Production Meeting (PPM) minutes signed by all stakeholders',
        frequency: 'Per Order Style',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-302',
        requirement: 'Style risk score assigned with mandatory mock-up seam sample testing before bulk layout',
        verificationMethod: 'Pilot Run 100-piece approval certificate',
        frequency: 'Per Style Run',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-303',
        requirement: 'Monthly tracking of factory DHU (Defects Per Hundred Units) against planned threshold (<2.8%)',
        verificationMethod: 'Daily DHU dashboard & weekly variance reports',
        frequency: 'Monthly',
        status: 'COMPLIANT',
      },
    ],
    linkedDocuments: [
      { docNumber: 'SOP-PPM-01', title: 'Pre-Production Meeting & Risk Analysis Protocol', docType: 'SOP' },
      { docNumber: 'DOC-RISK-2026', title: 'Garment Factory Master Risk Register', docType: 'FORM' },
    ],
    revisionHistory: [
      {
        revision: 'Rev 3.5',
        changeDate: '2025-03-01',
        changedBy: 'Mahmudul Hasan (IE Lead)',
        description: 'Integrated pilot run sample testing parameters for stretch elastane fabrics.',
      },
    ],
    notes: 'Directly linked to ERP Buyer Order pre-production milestone gatekeeper.',
    createdAt: '2023-05-12T08:00:00Z',
    updatedAt: '2026-03-01T14:20:00Z',
  },
  {
    id: 'qm-4',
    chapterNumber: 'QM-04',
    title: 'Support, Calibration, Human Competency & Infrastructure Control',
    clauseReference: 'ISO 9001:2015 Clause 7.1 - 7.5',
    summary:
      'Provision of calibrated laboratory instrumentation, clean 1000 lux illumination at inspection stations, operator skill matrix certification, and controlled document distribution.',
    responsibleDepartment: 'Maintenance, Lab & HR',
    status: 'ACTIVE',
    version: 'Rev 4.1',
    effectiveDate: '2025-01-20',
    nextReviewDate: '2026-01-20',
    approvedBy: 'Managing Director',
    author: 'Central Lab Manager',
    reviewedBy: 'HR Director',
    scope: 'Physical environment, calibration tools, lighting, moisture meters, operator training, and ERP document library.',
    isoStandard: 'ISO 9001:2015 Clause 7',
    confidentiality: 'GENERAL_FACILITY',
    policyCommitments: [
      'All inspection light boxes (D65/TL84/CWF), GSM cutters, pull-testers, and spectral equipment calibrated semi-annually by accredited laboratories.',
      'Minimum 1000 Lux illumination maintained over 100% of final inspection and cutting inspection tables.',
      'Comprehensive operator skill grading matrix updated quarterly with targeted retraining for operators with DHU > 4%.',
      'All quality forms, SOPs, and manuals maintained under strict version control via ERP Document Control module.',
    ],
    complianceRequirements: [
      {
        id: 'comp-401',
        requirement: 'NABL/ISO 17025 accredited calibration certificates on file for all testing equipment',
        verificationMethod: 'Calibration Master Register & equipment sticker audit',
        frequency: 'Semi-Annual',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-402',
        requirement: 'Lux meter photometer verification across all finishing and inspection lines',
        verificationMethod: 'Illumination Log Sheet with 10 random sample points',
        frequency: 'Monthly',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-403',
        requirement: '100% of quality controllers certified under annual 9-box shade sorting & visual defect exams',
        verificationMethod: 'Munsell 100 Hue Test results & training log',
        frequency: 'Annual',
        status: 'COMPLIANT',
      },
    ],
    linkedDocuments: [
      { docNumber: 'DOC-CAL-002', title: 'Measurement Equipment Calibration Procedure', docType: 'PROCEDURE' },
      { docNumber: 'TRN-SKL-01', title: 'Garment Sewing Operator Skill Matrix Protocol', docType: 'SOP' },
      { docNumber: 'DOC-CTRL-2026', title: 'Controlled Document & Version Governance Standard', docType: 'POLICY' },
    ],
    revisionHistory: [
      {
        revision: 'Rev 4.1',
        changeDate: '2025-01-20',
        changedBy: 'Farida Yasmin (Lab Manager)',
        description: 'Added spectrophotometer digital color tolerance delta-E calibration benchmarks.',
      },
    ],
    notes: 'Audited during Inditex and H&M laboratory technical accreditations with zero non-conformances.',
    createdAt: '2023-02-15T08:00:00Z',
    updatedAt: '2026-01-20T16:00:00Z',
  },
  {
    id: 'qm-5',
    chapterNumber: 'QM-05',
    title: 'Operation, Production Realization & Quality Control Gates',
    clauseReference: 'ISO 9001:2015 Clause 8.1 - 8.7',
    summary:
      'Core manufacturing protocols governing raw material inward inspection (4-Point fabric grading), cut piece numbering, fusing temperature peel testing, 100% in-line inspection, and needle control.',
    responsibleDepartment: 'Operations & Quality Assurance',
    status: 'ACTIVE',
    version: 'Rev 4.5',
    effectiveDate: '2025-04-01',
    nextReviewDate: '2026-04-01',
    approvedBy: 'VP Manufacturing & QA',
    author: 'QA Director',
    reviewedBy: 'Cutting & Sewing AGM',
    scope: 'Fabric warehouse, cutting, fusing, sewing, washing, finishing, needle detection, and packaging.',
    isoStandard: 'ISO 9001:2015 Clause 8',
    confidentiality: 'GENERAL_FACILITY',
    policyCommitments: [
      'No fabric roll exceeding 28 penalty points per 100 sq yds (ASTM D5430) released for production cutting without written buyer dispensation.',
      'Mandatory 24-hour natural relaxation for all circular knit fabrics prior to precision marker laying.',
      'Strict 9-point broken needle policy: 100% of broken pieces must be physically reassembled in the locked needle box before issuing a replacement.',
      'Every finished garment carton passes through calibrated 1.0mm 9-zone metal detector before sealing.',
    ],
    complianceRequirements: [
      {
        id: 'comp-501',
        requirement: '10% sample fabric rolls inspected under ASTM D5430 4-Point System with shade band verification',
        verificationMethod: 'Raw Material Inspection Report (GRN linked)',
        frequency: 'Per Inward Lot',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-502',
        requirement: 'Hourly 7-piece roving audit conducted on every active sewing line using traffic light signaling',
        verificationMethod: 'Real-time Line QC tablet logs & physical inspection boards',
        frequency: 'Hourly',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-503',
        requirement: 'Needle detector sensitivity calibrated using 1.0mm Ferrous test card at shift start and every 2 hours',
        verificationMethod: 'Metal Detector Hourly Calibration Log',
        frequency: 'Every 2 Hours',
        status: 'COMPLIANT',
      },
    ],
    linkedDocuments: [
      { docNumber: 'PRC-CUT-01', title: 'Fabric Spreading & Natural Relaxation Protocol', docType: 'PROCEDURE' },
      { docNumber: 'PRC-NDL-01', title: '9-Point Broken Needle & Metal Contamination Control', docType: 'PROCEDURE' },
      { docNumber: 'SOP-AQL-01', title: 'AQL 1.5 Final Random Inspection Standard Operating Procedure', docType: 'SOP' },
      { docNumber: 'SOP-FUS-02', title: 'Interlining Fusing Temperature & Peel Strength Protocol', docType: 'SOP' },
    ],
    revisionHistory: [
      {
        revision: 'Rev 4.5',
        changeDate: '2025-04-01',
        changedBy: 'Tanzim Ahmed (QA Director)',
        description: 'Tightened needle detection verification interval from 4 hours down to every 2 hours.',
      },
    ],
    notes: 'Core operational chapter governing 92% of all daily factory standard operating procedures.',
    createdAt: '2023-01-01T08:00:00Z',
    updatedAt: '2026-04-01T10:15:00Z',
  },
  {
    id: 'qm-6',
    chapterNumber: 'QM-06',
    title: 'Performance Evaluation, Internal Auditing & Customer Satisfaction',
    clauseReference: 'ISO 9001:2015 Clause 9.1 - 9.3',
    summary:
      'Rigorous monitoring mechanisms including daily line DHU statistics, end-of-line AQL audits, monthly internal QMS audits, customer quality feedback tracking, and formal Management Review Meetings.',
    responsibleDepartment: 'Internal Audit & QA',
    status: 'ACTIVE',
    version: 'Rev 3.8',
    effectiveDate: '2025-02-15',
    nextReviewDate: '2026-02-15',
    approvedBy: 'Managing Director',
    author: 'Lead QMS Auditor',
    reviewedBy: 'QA Director',
    scope: 'Internal audit schedule, statistical process control, customer feedback, and executive management reviews.',
    isoStandard: 'ISO 9001:2015 Clause 9',
    confidentiality: 'INTERNAL_RESTRICTED',
    policyCommitments: [
      'Internal QMS audits executed across 100% of plant departments at least twice per calendar year by IRCA certified auditors.',
      'Auditors must be completely independent of the operational department being audited.',
      'Customer complaint root cause analysis (RCA) and 8D CAPA initiated within 24 hours of notification.',
      'Management Review Meetings (MRM) convened semi-annually with documented minutes and time-bound action items.',
    ],
    complianceRequirements: [
      {
        id: 'comp-601',
        requirement: 'Annual Internal Audit Schedule approved by Executive Management and published in ERP',
        verificationMethod: 'Internal Audit Program Register & Auditor Qualification Records',
        frequency: 'Annual',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-602',
        requirement: 'Pre-shipment buyer audit first-time pass rate monitored and maintained > 98.5%',
        verificationMethod: 'Buyer Inspection Log & Certificate of Inspection (COI) records',
        frequency: 'Per Shipment',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-603',
        requirement: 'Formal customer satisfaction rating survey conducted across top 10 international buyers',
        verificationMethod: 'Customer Satisfaction Survey Report with Net Promoter Score',
        frequency: 'Bi-Annual',
        status: 'COMPLIANT',
      },
    ],
    linkedDocuments: [
      { docNumber: 'SOP-AUD-01', title: 'Internal QMS Audit Execution & Auditor Independence Standard', docType: 'SOP' },
      { docNumber: 'DOC-MRM-2026', title: 'Management Review Meeting Agenda & Minutes Template', docType: 'FORM' },
      { docNumber: 'SOP-CAPA-01', title: '8D Corrective Action & Root Cause Analysis Procedure', docType: 'SOP' },
    ],
    revisionHistory: [
      {
        revision: 'Rev 3.8',
        changeDate: '2025-02-15',
        changedBy: 'Md. Rafiqul Islam (Lead Auditor)',
        description: 'Mandated IRCA lead auditor certification credentials for internal audit team leaders.',
      },
    ],
    notes: 'Directly feeds into executive KPI dashboards and ISO 9001 surveillance audit agendas.',
    createdAt: '2023-03-20T08:00:00Z',
    updatedAt: '2026-02-15T12:00:00Z',
  },
  {
    id: 'qm-7',
    chapterNumber: 'QM-07',
    title: 'Continual Improvement, Non-Conformity Management & 8D CAPA',
    clauseReference: 'ISO 9001:2015 Clause 10.1 - 10.3',
    summary:
      'Systematic identification of recurring defects, quarantine of non-conforming lots, 5-Why root cause analysis, irreversible corrective actions, and Kaizen continuous improvement initiatives.',
    responsibleDepartment: 'Quality Assurance & Continuous Improvement',
    status: 'ACTIVE',
    version: 'Rev 4.0',
    effectiveDate: '2025-01-10',
    nextReviewDate: '2026-01-10',
    approvedBy: 'VP Manufacturing & QA',
    author: 'Continuous Improvement Manager',
    reviewedBy: 'QA Director',
    scope: 'Defect logging, red-tag quarantine area, CAPA workflows, supplier non-conformity notices, and Kaizen projects.',
    isoStandard: 'ISO 9001:2015 Clause 10',
    confidentiality: 'GENERAL_FACILITY',
    policyCommitments: [
      'Any lot rejected during in-line or final AQL inspection must be immediately tagged with Red Quarantine Card and segregated in the designated secure QA lockup.',
      'Root cause determination using 5-Why and Ishikawa Fishbone diagrams mandatory for all Critical and Major non-conformances.',
      'CAPA effectiveness verified 30 days after implementation before formal closure by QA Director.',
      'Monthly Kaizen quality improvement suggestions recognized with corporate operator incentive awards.',
    ],
    complianceRequirements: [
      {
        id: 'comp-701',
        requirement: 'Non-conforming product quarantine log maintained with 100% physical segregation',
        verificationMethod: 'Quarantine Area Audit & Red Tag Reconciliation',
        frequency: 'Daily',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-702',
        requirement: '8D CAPA completed and submitted to buyer within 72 hours of major defect notification',
        verificationMethod: 'ERP CAPA Tracking Log & Buyer Acknowledgment',
        frequency: 'Per Incident',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-703',
        requirement: 'Follow-up audit conducted 30 days post-implementation to verify corrective action sustainability',
        verificationMethod: 'CAPA Verification Sign-off Record',
        frequency: 'Per CAPA',
        status: 'COMPLIANT',
      },
    ],
    linkedDocuments: [
      { docNumber: 'SOP-NC-01', title: 'Control of Non-Conforming Garments & Quarantine Protocol', docType: 'SOP' },
      { docNumber: 'SOP-CAPA-01', title: '8D Corrective Action & Root Cause Analysis Procedure', docType: 'SOP' },
      { docNumber: 'DOC-5WHY-01', title: '5-Why & Ishikawa Fishbone Problem Solving Worksheet', docType: 'FORM' },
    ],
    revisionHistory: [
      {
        revision: 'Rev 4.0',
        changeDate: '2025-01-10',
        changedBy: 'Tanzim Ahmed (QA Director)',
        description: 'Standardized 8D problem-solving methodology across all apparel manufacturing units.',
      },
    ],
    notes: 'Reviewed and commended by PVH and Inditex technical audit panels.',
    createdAt: '2023-01-01T08:00:00Z',
    updatedAt: '2026-01-10T17:30:00Z',
  },
  {
    id: 'qm-8',
    chapterNumber: 'QM-08',
    title: 'Chemical Management, Environmental Compliance & Sustainable Washing',
    clauseReference: 'ISO 14001:2015 / ZDHC MRSL v3.1',
    summary:
      'Safe storage and application of textile processing chemicals, Zero Discharge of Hazardous Chemicals (ZDHC) compliance, wastewater treatment monitoring, and garment wash laboratory safety protocols.',
    responsibleDepartment: 'Washing Plant & Environmental Compliance',
    status: 'ACTIVE',
    version: 'Rev 2.4',
    effectiveDate: '2025-02-28',
    nextReviewDate: '2026-02-28',
    approvedBy: 'Environmental Compliance Director',
    author: 'Washing Chemical Engineer',
    reviewedBy: 'Plant Director',
    scope: 'Washing plant, chemical store, Effluent Treatment Plant (ETP), and laundry testing laboratory.',
    isoStandard: 'ZDHC MRSL v3.1 / ISO 14001:2015 / Higg FEM',
    confidentiality: 'GENERAL_FACILITY',
    policyCommitments: [
      '100% of laundry chemicals, enzymes, softeners, and dyes must be ZDHC Level 3 certified and logged in the chemical inventory register.',
      'Safety Data Sheets (SDS) in English and Bengali prominently posted in all chemical mixing and dosing areas.',
      'Secondary containment provided for all bulk chemical containers with spill kits inspected weekly.',
      'Continuous real-time monitoring of ETP treated wastewater discharge parameters (pH, COD, BOD, TDS).',
    ],
    complianceRequirements: [
      {
        id: 'comp-801',
        requirement: 'Monthly upload of chemical procurement inventory to ZDHC Gateway with MRSL conformance score > 98%',
        verificationMethod: 'ZDHC Performance InCheck Report',
        frequency: 'Monthly',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-802',
        requirement: 'Third-party certified laboratory testing of ETP discharge water against ZDHC ClearStream standards',
        verificationMethod: 'Wastewater Test Report (Eurofins/SGS)',
        frequency: 'Quarterly',
        status: 'COMPLIANT',
      },
      {
        id: 'comp-803',
        requirement: 'Operator chemical handling PPE audit including respirators, neoprene gloves, and eye wash stations',
        verificationMethod: 'Safety & PPE Compliance Checklist',
        frequency: 'Weekly',
        status: 'COMPLIANT',
      },
    ],
    linkedDocuments: [
      { docNumber: 'SOP-CHM-01', title: 'Chemical Receipt, Storage, and Dispensing Standard Operating Procedure', docType: 'SOP' },
      { docNumber: 'PRC-ETP-01', title: 'Effluent Treatment Plant Monitoring & Emergency Spillage Protocol', docType: 'PROCEDURE' },
      { docNumber: 'DOC-MSDS-2026', title: 'Master Chemical Safety Data Sheet (SDS) Compendium', docType: 'FORM' },
    ],
    revisionHistory: [
      {
        revision: 'Rev 2.4',
        changeDate: '2025-02-28',
        changedBy: 'Arif Hossain (Chemical Engineer)',
        description: 'Updated MRSL conformance threshold to align with ZDHC v3.1 requirements.',
      },
    ],
    notes: 'Achieved Higg FEM verification score of 94.2% in the latest annual assessment.',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2026-02-28T09:15:00Z',
  },
];
