import {
  CommunicationNotice,
  NoticeCategory,
  NoticeUrgency,
  NoticeStatus,
} from '@/lib/types/modules';

export const NOTICE_CATEGORY_CONFIG: Record<
  NoticeCategory,
  { label: string; bg: string; text: string; border: string; desc: string }
> = {
  QUALITY_FLASH: {
    label: 'Quality Flash Alert',
    bg: 'bg-rose-50',
    text: 'text-rose-700',
    border: 'border-rose-200',
    desc: 'Immediate floor defect containment or process stop',
  },
  BUYER_ADVISORY: {
    label: 'Buyer Advisory',
    bg: 'bg-indigo-50',
    text: 'text-indigo-700',
    border: 'border-indigo-200',
    desc: 'Official technical pack, tolerance, or wash standard update',
  },
  OPERATIONAL_CIRCULAR: {
    label: 'Operational Circular',
    bg: 'bg-blue-50',
    text: 'text-blue-700',
    border: 'border-blue-200',
    desc: 'Internal factory procedures, shift handovers & calibration cycles',
  },
  COMPLIANCE_SAFETY: {
    label: 'Compliance & Safety',
    bg: 'bg-amber-50',
    text: 'text-amber-700',
    border: 'border-amber-200',
    desc: 'WRAP, ISO 9001, needle policy & chemical regulatory mandates',
  },
  COMMENDATION: {
    label: 'Commendation & Award',
    bg: 'bg-emerald-50',
    text: 'text-emerald-700',
    border: 'border-emerald-200',
    desc: 'Floor quality milestones, DHU incentives & audit excellence',
  },
};

export const NOTICE_URGENCY_CONFIG: Record<
  NoticeUrgency,
  { label: string; badgeVariant: 'rose' | 'amber' | 'emerald' | 'blue' }
> = {
  HIGH_PRIORITY: { label: 'High Priority (Urgent)', badgeVariant: 'rose' },
  STANDARD: { label: 'Standard Notice', badgeVariant: 'blue' },
  INFO: { label: 'Informational', badgeVariant: 'emerald' },
};

export const FACTORY_DEPARTMENTS = [
  'All Factory Divisions',
  'Cutting Department',
  'Sewing Lines (All 12 Lines)',
  'Finishing & Packing',
  'In-House QA / QC Lab',
  'Denim Washing & Wet Processing',
  'Embroidery & Print Units',
  'Merchandising & Sourcing',
  'Maintenance & Engineering',
];

export const INITIAL_NOTICES: CommunicationNotice[] = [
  {
    id: 'ntc-001',
    noticeNumber: 'QA-FLSH-2026-001',
    title: 'Strict Color Shading Segregation for Lot LOT-FB-8840 (Heather Grey)',
    urgency: 'HIGH_PRIORITY',
    category: 'QUALITY_FLASH',
    author: 'Tanzim Ahmed',
    authorRole: 'QA Manager',
    targetDepartment: 'Cutting, Sewing & Finishing All Lines',
    targetAudience: ['Cutting Floor Supervisors', 'Line 01-06 QC Leads', 'Ironing Section Heads'],
    publishedDate: '2026-09-22 08:30',
    effectiveUntil: '2026-09-30',
    content:
      'All cutting supervisors must ensure Heather Grey 240 GSM single jersey fabric rolls tagged with Sub-Lot B are strictly cut, numbered, and bundled in separate bin carts from Sub-Lot A. Under no circumstance may rib collars or pocket bags be mixed across different roll dyelots. Continuous ultraviolet inspection is mandated at end of line.',
    actionRequired:
      'Mandatory 100% UV shade band verification for every bundle prior to sewing input. Reject bundles with delta-E greater than 0.8 against master shade card.',
    isRead: false,
    status: 'PUBLISHED',
    buyerRef: 'H&M Hennes & Mauritz',
    orderRef: 'PO-HM-9941',
    styleRef: 'HM-TEE-8829',
    pinned: true,
    totalRecipientsCount: 24,
    acknowledgedCount: 22,
    attachments: [
      { name: 'Shade_Segregation_Guideline_v2.pdf', size: '1.4 MB', type: 'application/pdf' },
      { name: 'DeltaE_Tolerance_Chart.xlsx', size: '240 KB', type: 'application/vnd.ms-excel' },
    ],
    acknowledgments: [
      {
        id: 'ack-101',
        userName: 'Rafiqul Islam',
        userRole: 'Cutting Master',
        department: 'Cutting Department',
        acknowledgedAt: '2026-09-22 09:15',
        actionTakenNotes: 'Separate bin tables assigned for Lot B. UV lamp installed on bundle inspection table 3.',
      },
      {
        id: 'ack-102',
        userName: 'Salma Khatun',
        userRole: 'Sewing Supervisor Line 01',
        department: 'Sewing Line 01',
        acknowledgedAt: '2026-09-22 09:40',
        actionTakenNotes: 'Line 01 operators briefed on collar lot matching stickers.',
      },
      {
        id: 'ack-103',
        userName: 'Monir Hossain',
        userRole: 'Finishing Lead',
        department: 'Finishing & Packing',
        acknowledgedAt: '2026-09-22 10:05',
        actionTakenNotes: '100% shade audit stationed before polybag packing.',
      },
    ],
    comments: [
      {
        id: 'cmt-1',
        authorName: 'Tanzim Ahmed',
        authorRole: 'QA Manager',
        department: 'Quality Assurance',
        timestamp: '2026-09-22 08:35',
        comment: 'Please escalate immediately if any hue mismatch is observed in morning inline audits.',
      },
      {
        id: 'cmt-2',
        authorName: 'Rafiqul Islam',
        authorRole: 'Cutting Master',
        department: 'Cutting',
        timestamp: '2026-09-22 09:16',
        comment: 'All 8 rolls from Lot B have been quarantined with orange fluorescent tags.',
      },
    ],
  },
  {
    id: 'ntc-002',
    noticeNumber: 'QA-ADV-2026-014',
    title: 'Zara Spain Technical Update: Hem Stitch Density & Tension Spec (STY-DN-502)',
    urgency: 'STANDARD',
    category: 'BUYER_ADVISORY',
    author: 'Farhana Akhter',
    authorRole: 'Senior Lab & Tech Pack Specialist',
    targetDepartment: 'Denim Washing & In-Line QC',
    targetAudience: ['Washing Plant Technicians', 'Line 05-08 Supervisors', 'QC Floor Auditors'],
    publishedDate: '2026-09-20 11:20',
    effectiveUntil: '2026-10-15',
    content:
      'Official technical revision received from Inditex / Zara Spain HQ. For Style STY-DN-502 (Slim Fit Stretch Denim), the bottom hem double-chainstitch SPI requirement has been calibrated from 9 SPI to 11 SPI to prevent puckering after enzyme stone wash.',
    actionRequired:
      'Mechanics must immediately recalibrate all bottom-hemming machines on Denim Lines 07 & 08. In-line QC to verify SPI count every 2 hours on mockups.',
    isRead: true,
    status: 'PUBLISHED',
    buyerRef: 'Zara / Inditex',
    orderRef: 'PO-ZR-8820',
    styleRef: 'STY-DN-502',
    pinned: false,
    totalRecipientsCount: 18,
    acknowledgedCount: 16,
    attachments: [
      { name: 'Zara_Hem_SPI_Revision_Notice.pdf', size: '2.1 MB', type: 'application/pdf' },
    ],
    acknowledgments: [
      {
        id: 'ack-201',
        userName: 'Akram Ullah',
        userRole: 'Chief Maintenance Mechanic',
        department: 'Maintenance & Engineering',
        acknowledgedAt: '2026-09-20 12:30',
        actionTakenNotes: 'Feed dogs and stitch gears adjusted on all 6 hemming machines.',
      },
      {
        id: 'ack-202',
        userName: 'Mahinur Rahman',
        userRole: 'Denim Line QC Lead',
        department: 'Sewing Lines',
        acknowledgedAt: '2026-09-20 13:10',
        actionTakenNotes: 'First 50 pcs mockups verified at 11 SPI; pass signed off.',
      },
    ],
    comments: [
      {
        id: 'cmt-3',
        authorName: 'Farhana Akhter',
        authorRole: 'Tech Pack Specialist',
        department: 'QA Lab',
        timestamp: '2026-09-20 11:30',
        comment: 'Washing plant wash sample passed shrinkage check with the new 11 SPI seam.',
      },
    ],
  },
  {
    id: 'ntc-003',
    noticeNumber: 'QA-CIRC-2026-028',
    title: 'Mandatory 9-Point Needle Control & Daily Metal Detector Calibration Log',
    urgency: 'HIGH_PRIORITY',
    category: 'COMPLIANCE_SAFETY',
    author: 'Engr. Tariqul Islam',
    authorRole: 'VP Operations & Compliance Head',
    targetDepartment: 'All Factory Divisions',
    targetAudience: ['Floor Supervisors', 'Maintenance Engineers', 'Finishing Inspectors'],
    publishedDate: '2026-09-18 09:00',
    effectiveUntil: '2026-12-31',
    content:
      'In compliance with WRAP and buyer brand safety protocols, broken needle policies will be subjected to random twice-daily unannounced audits. Any machine found with an incomplete broken needle blister card will be immediately locked out until all 9 fragments are accounted for.',
    actionRequired:
      '1) Metal detector calibration must be validated with 1.0mm Ferrous and 1.2mm Non-Ferrous test wands at 08:00, 12:00, 16:00, and 20:00 without exception. 2) No spare needles permitted on sewing floor workstations.',
    isRead: true,
    status: 'PUBLISHED',
    buyerRef: 'Global Buyer Standards (WRAP / Sedex)',
    orderRef: 'ALL-ACTIVE-PO',
    styleRef: 'FACTORY-WIDE',
    pinned: true,
    totalRecipientsCount: 32,
    acknowledgedCount: 31,
    attachments: [
      { name: 'Needle_Safety_Standard_Operating_Procedure.pdf', size: '3.4 MB', type: 'application/pdf' },
      { name: 'Calibration_Log_Sheet_Template.pdf', size: '420 KB', type: 'application/pdf' },
    ],
    acknowledgments: [
      {
        id: 'ack-301',
        userName: 'Zahid Hasan',
        userRole: 'Metal Detector Operator',
        department: 'Finishing & Packing',
        acknowledgedAt: '2026-09-18 09:45',
        actionTakenNotes: 'Hourly test records updated in digital logbook.',
      },
    ],
    comments: [
      {
        id: 'cmt-4',
        authorName: 'Engr. Tariqul Islam',
        authorRole: 'VP Operations',
        department: 'Operations',
        timestamp: '2026-09-18 09:05',
        comment: 'External WRAP auditor will inspect the broken needle lockbox on Monday.',
      },
    ],
  },
  {
    id: 'ntc-004',
    noticeNumber: 'QA-AWRD-2026-004',
    title: 'Plant Quality Excellence: Sewing Lines 01 & 02 Record 0.98% DHU for August',
    urgency: 'INFO',
    category: 'COMMENDATION',
    author: 'Engr. Tariqul Islam',
    authorRole: 'VP Operations',
    targetDepartment: 'Sewing Lines (All 12 Lines)',
    targetAudience: ['All Sewing Operators', 'Line Mechanics', 'Inline Quality Checkers'],
    publishedDate: '2026-09-15 14:00',
    effectiveUntil: '2026-10-31',
    content:
      'Hearty congratulations to the operators, supervisors, and mechanics of Sewing Lines 01 and 02. Both lines maintained a Defects Per Hundred Units (DHU) below 1.0% across 84,000 polo shirts produced for PVH / Tommy Hilfiger. Monthly quality incentives will be credited in this payroll cycle.',
    actionRequired:
      'Lines 03 to 12 are encouraged to benchmark the work-in-progress bundling and twin-needle hem techniques demonstrated during the line sharing session.',
    isRead: true,
    status: 'PUBLISHED',
    buyerRef: 'PVH Corp / Tommy Hilfiger',
    orderRef: 'PO-PVH-7712',
    styleRef: 'PVH-POLO-2026',
    pinned: false,
    totalRecipientsCount: 40,
    acknowledgedCount: 38,
    attachments: [
      { name: 'August_DHU_Achievement_Report.pdf', size: '1.8 MB', type: 'application/pdf' },
    ],
    acknowledgments: [
      {
        id: 'ack-401',
        userName: 'Nasrin Akhter',
        userRole: 'Line 02 QC Lead',
        department: 'Sewing Lines',
        acknowledgedAt: '2026-09-15 15:20',
        actionTakenNotes: 'Shared congratulations with team; targeting 0.85% DHU for September.',
      },
    ],
    comments: [
      {
        id: 'cmt-5',
        authorName: 'Tanzim Ahmed',
        authorRole: 'QA Manager',
        department: 'Quality Assurance',
        timestamp: '2026-09-15 14:15',
        comment: 'Great work team! Zero end-line rejections on sleeve attaching was exemplary.',
      },
    ],
  },
  {
    id: 'ntc-005',
    noticeNumber: 'QA-CIRC-2026-031',
    title: 'Upcoming Central Steam Boiler Maintenance & Ironing Station Pressure Test',
    urgency: 'STANDARD',
    category: 'OPERATIONAL_CIRCULAR',
    author: 'Kabir Chowdhury',
    authorRole: 'Head of Plant Engineering',
    targetDepartment: 'Finishing & Packing',
    targetAudience: ['Finishing In-charge', 'Ironing Technicians', 'Safety Marshals'],
    publishedDate: '2026-09-12 16:45',
    effectiveUntil: '2026-09-28',
    content:
      'Scheduled preventive maintenance for Steam Boiler Unit #2 will take place on Saturday from 18:00 to 22:00. During this period, steam headers supplying Ironing Stations 1 through 10 will operate on auxiliary generator backup with reduced pressure of 3.8 bar.',
    actionRequired:
      'Finishing supervisors must stagger heavy twill outerwear pressing before 17:30 to avoid press shine or under-cured fusing. Report any condensation dripping immediately.',
    isRead: false,
    status: 'PUBLISHED',
    buyerRef: 'All Buyers',
    orderRef: 'PLANT-MAINT-2026',
    styleRef: 'ALL-STYLES',
    pinned: false,
    totalRecipientsCount: 15,
    acknowledgedCount: 12,
    attachments: [
      { name: 'Boiler_Shutdown_Schedule_Rev3.pdf', size: '890 KB', type: 'application/pdf' },
    ],
    acknowledgments: [],
    comments: [],
  },
];
