import { OrganogramNode } from '@/lib/types/modules';

export const INITIAL_ORGANOGRAM_NODES: OrganogramNode[] = [
  {
    id: 'org-1',
    name: 'Engr. Tariqul Islam',
    title: 'VP of Manufacturing & Quality Assurance',
    department: 'Executive Management',
    email: 'tariqul.islam@garments-erp.com',
    phone: '+880 1711 500101',
    officeLocation: 'Executive Corporate Suite 401',
    headcount: 480,
    grade: 'L8 Executive',
    status: 'ACTIVE',
    responsibilities: [
      'Supreme corporate oversight of multi-unit garment manufacturing, social compliance, and QMS governance',
      'Final executive escalation point for international buyer relationships (Inditex, H&M, PVH, Target)',
      'Direct supervision of Plant Directors, Quality Directors, and Industrial Engineering operations',
      'Approval of annual corporate capital expenditures and strategic automation roadmaps',
    ],
    certifications: [
      'Six Sigma Master Black Belt (ASQ)',
      'IRCA Lead QMS Auditor (ISO 9001:2015)',
      'M.Sc. in Textile Engineering (BUET)',
    ],
    decisionAuthority:
      'Autonomous corporate authority over facility quality release, emergency line shutdowns, and corporate compliance certifications.',
    joinedDate: '2018-04-01',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'org-2',
    name: 'Tanzim Ahmed',
    title: 'Head of Quality Assurance (QMS Director)',
    department: 'Quality Assurance',
    reportsToId: 'org-1',
    email: 'tanzim.ahmed@garments-erp.com',
    phone: '+880 1711 500102',
    officeLocation: 'Central QMS Tower 2, 3rd Floor',
    headcount: 65,
    grade: 'L7 Director',
    status: 'ACTIVE',
    responsibilities: [
      'Maintain factory QMS manual, SOP registers, and zero-defect quality gate architecture',
      'Manage AQL 1.5 / 2.5 final pre-shipment inspections and third-party buyer audits',
      'Oversee CAPA (8D) investigations, defect libraries, and calibration schedules',
      'Coordinate with Merchandising and Production on sample approvals and golden seal sign-offs',
    ],
    certifications: [
      'ISO 9001:2015 Lead Auditor',
      'Lean Six Sigma Black Belt',
      'ZDHC Chemical Quality Manager',
      'WRAP & HIGG FEM Lead Specialist',
    ],
    decisionAuthority:
      'Sole authorized technical authority to sign buyer pre-shipment certificates and reject defective export lots.',
    joinedDate: '2020-02-15',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2026-09-22T14:00:00Z',
  },
  {
    id: 'org-3',
    name: 'Mahmudul Hasan',
    title: 'Head of Industrial Engineering (IE)',
    department: 'Engineering & Productivity',
    reportsToId: 'org-1',
    email: 'm.hasan@garments-erp.com',
    phone: '+880 1711 500103',
    officeLocation: 'Engineering Center, Room 102',
    headcount: 24,
    grade: 'L7 Director',
    status: 'ACTIVE',
    responsibilities: [
      'Design and validate standardized garment process flow charts, line layouts, and SMV studies',
      'Optimize machine automation, motion study benchmarks, and production balancing',
      'Lead digital factory transformation, IoT machine sensors, and real-time efficiency dashboards',
    ],
    certifications: [
      'GSD (General Sewing Data) Certified Master',
      'Lean Manufacturing Gold Practitioner (SME)',
      'B.Sc. Industrial & Production Engineering',
    ],
    decisionAuthority:
      'Standard Minute Value (SMV) authorization and factory line capacity allocation across export buyer orders.',
    joinedDate: '2019-07-01',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2026-09-21T11:00:00Z',
  },
  {
    id: 'org-4',
    name: 'Farhana Akhter',
    title: 'Central QA Testing Lab Manager',
    department: 'Testing & Physical Labs',
    reportsToId: 'org-2',
    email: 'f.akhter@garments-erp.com',
    phone: '+880 1711 500104',
    officeLocation: 'Central Laboratory Building, Lab 01',
    headcount: 8,
    grade: 'L5 Manager',
    status: 'ACTIVE',
    responsibilities: [
      'Direct physical, chemical, and colorfastness testing according to ISO, AATCC, and ASTM standards',
      'Operate spectrophotometer delta E color matching under D65, TL84, and CWF light illuminants',
      'Maintain ISO 17025 lab accreditation and round-robin testing proficiency compliance',
    ],
    certifications: [
      'AATCC Certified Colorist & Evaluator',
      'ISO 17025 Lead Technical Signatory',
      'M.Sc. in Applied Chemistry',
    ],
    decisionAuthority:
      'Authorized signatory for lab pass/fail test reports, shrinkage release, and chemical compliance clearance.',
    joinedDate: '2021-03-10',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2026-09-23T09:30:00Z',
  },
  {
    id: 'org-5',
    name: 'Devon Vance',
    title: 'Warehouse & Incoming QC Manager',
    department: 'Incoming Quality',
    reportsToId: 'org-2',
    email: 'd.vance@garments-erp.com',
    phone: '+880 1711 500105',
    officeLocation: 'Warehouse Receiving Dock Terminal B',
    headcount: 14,
    grade: 'L5 Manager',
    status: 'ACTIVE',
    responsibilities: [
      'Supervise 10% 4-point fabric roll inspection, barcode matching, and trims quarantine verification',
      'Manage raw material supplier ratings, defect escalation, and return-to-vendor (RTV) claims',
      'Ensure ERP traceability barcode registry from inward challan to cutting room release',
    ],
    certifications: [
      'ASTM D5430 4-Point Certified Auditor',
      'APICS Certified Supply Chain Professional (CSCP)',
    ],
    decisionAuthority:
      'Immediate red-tag quarantine authority for non-conforming fabrics, accessories, and yarn lots.',
    joinedDate: '2022-06-01',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2026-09-24T16:00:00Z',
  },
  {
    id: 'org-6',
    name: 'Sarah Jenkins',
    title: 'Denim & Woven Quality Lead',
    department: 'Sewing Operations',
    reportsToId: 'org-2',
    email: 's.jenkins@garments-erp.com',
    phone: '+880 1711 500106',
    officeLocation: 'Sewing Hall B, Inspection Station 04',
    headcount: 18,
    grade: 'L5 Lead',
    status: 'ACTIVE',
    responsibilities: [
      'Manage 18 roving QC inspectors across denim trousers and woven jacket sewing lines',
      'Conduct pilot run audits, 100-piece mock evaluations, and hourly inline check sheets',
      'Validate sewing machine SPI, needle gauge alignment, and seam tension tolerances',
    ],
    certifications: [
      'ANSI/ASQ Z1.4 Sampling Auditor',
      'Pattern Master Fitting Specialist',
      'Six Sigma Green Belt',
    ],
    decisionAuthority:
      'Immediate line-stop authority upon detection of 3 consecutive defect clusters on any sewing line.',
    joinedDate: '2021-11-15',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z',
  },
  {
    id: 'org-7',
    name: 'Rafiqul Islam',
    title: 'Knits & Finishing Quality Lead',
    department: 'Finishing Operations',
    reportsToId: 'org-2',
    email: 'r.islam@garments-erp.com',
    phone: '+880 1711 500107',
    officeLocation: 'Finishing Terminal 3, Pre-Final Station',
    headcount: 25,
    grade: 'L5 Lead',
    status: 'ACTIVE',
    responsibilities: [
      'Oversee button pull testing (90N/10s), 100% metal detector conveyor scans, and carton SKU audits',
      'Ensure GPQ pre-final audit clearance and export packaging compliance',
      'Direct needle exchange logbook security and 9-point sphere calibration hourly',
    ],
    certifications: [
      'Metal Detection Procedure Certified Specialist',
      'Garment Packaging & Barcode Master Auditor',
    ],
    decisionAuthority:
      'Authorization of final carton sealing and container release for export forwarding.',
    joinedDate: '2020-09-01',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'org-8',
    name: 'Anisur Rahman',
    title: 'Senior Calibration & Metrology Specialist',
    department: 'Testing & Physical Labs',
    reportsToId: 'org-4',
    email: 'a.rahman@garments-erp.com',
    phone: '+880 1711 500108',
    officeLocation: 'Metrology Clean Room 104',
    headcount: 3,
    grade: 'L4 Specialist',
    status: 'ACTIVE',
    responsibilities: [
      'Calibrate dial calipers, digital balances, pull testers, and thermocouple sensors',
      'Maintain traceability to National Metrology Laboratory (NML) standards',
      'Tag yellow/red calibration status labels across factory equipment',
    ],
    certifications: [
      'ISO 17025 Metrology & Uncertainty Evaluator',
      'Electrical & Mechanical Instrument Specialist',
    ],
    decisionAuthority:
      'Immediate decommission and lock-out tag-out (LOTO) of any gauge drifting outside tolerance.',
    joinedDate: '2022-01-10',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2026-09-22T09:00:00Z',
  },
];
