import { FactoryEventItem } from '@/lib/types/modules';

export const INITIAL_FACTORY_EVENTS: FactoryEventItem[] = [
  {
    id: 'evt-001',
    eventCode: 'EVT-2026-14',
    title: 'H&M Regional Quality Director Semi-Annual Technical Visit',
    type: 'BUYER_VISIT',
    eventDate: '2026-10-08',
    endDate: '2026-10-09',
    timeSlot: '09:00 AM - 05:00 PM',
    location: 'Executive Boardroom, Sample Room & Sewing Lines 01-04',
    leadOrganizer: 'Farhan Rahman (Merchandising & QA Directorate)',
    buyerName: 'H&M Hennes & Mauritz',
    department: 'Executive Quality & Merchandising',
    priority: 'CRITICAL',
    status: 'UPCOMING',
    readinessPercentage: 85,
    attendeesCount: 12,
    agendaSummary: 'Review A/W 2026 bulk denim run, assess line defect Pareto charts, inspect Fabric Lab spectrophotometer calibration, and confirm gold-supplier quality rating.',
    description: 'High-level bi-annual audit and relationship meeting with H&M Regional Technical Quality Director to verify QMS compliance and discuss capacity expansion.',
    delegationMembers: [
      { id: 'att-1', name: 'Marcus Lindqvist', organization: 'BUYER', role: 'Regional Quality Director (H&M Sweden)', confirmed: true },
      { id: 'att-2', name: 'Sarah Jenkins', organization: 'BUYER', role: 'Country Technical QA Specialist', confirmed: true },
      { id: 'att-3', name: 'Tanzim Ahmed', organization: 'FACTORY', department: 'Quality Assurance', role: 'Head of Quality (Host)', confirmed: true },
      { id: 'att-4', name: 'Engr. M. A. Jalil', organization: 'FACTORY', department: 'Executive Directorate', role: 'Managing Director', confirmed: true },
      { id: 'att-5', name: 'Farhana Akhter', organization: 'FACTORY', department: 'Testing Lab', role: 'QA Documentation & Lab Lead', confirmed: true },
    ],
    itinerary: [
      { id: 'itin-1', timeSlot: '09:00 AM - 10:00 AM', activity: 'Executive Welcome & Factory QMS Overview Presentation', location: 'Executive Boardroom', facilitator: 'Tanzim Ahmed', completed: false },
      { id: 'itin-2', timeSlot: '10:00 AM - 12:30 PM', activity: 'Floor Walkthrough: Cutting Room & Sewing Lines 01-04 Pilot Run', location: 'Sewing Floor 1', facilitator: 'Shamima Nasrin', completed: false },
      { id: 'itin-3', timeSlot: '01:30 PM - 03:00 PM', activity: 'In-House Physical & Chemical Testing Lab Audit', location: 'Central QA Lab', facilitator: 'Farhana Akhter', completed: false },
      { id: 'itin-4', timeSlot: '03:30 PM - 05:00 PM', activity: 'Closing Meeting & Summary of Recommendations', location: 'Executive Boardroom', facilitator: 'Engr. M. A. Jalil', completed: false },
    ],
    preparationChecklist: [
      { id: 'chk-1', task: 'Prepare A/W 2026 bulk production DHU trend charts and golden sample display', responsiblePerson: 'Tanzim Ahmed', dueDate: '2026-10-05', completed: true, completedDate: '2026-09-24' },
      { id: 'chk-2', task: 'Calibrate VeriVide light box bulbs and document NIST traceability certificates', responsiblePerson: 'Farhana Akhter', dueDate: '2026-10-06', completed: true, completedDate: '2026-09-23' },
      { id: 'chk-3', task: 'Conduct 5S floor housekeeping audit on Lines 01 through 04', responsiblePerson: 'Shamima Nasrin', dueDate: '2026-10-07', completed: false },
      { id: 'chk-4', task: 'Prepare visitor safety gear (PPE badges, safety footwear, ear protection)', responsiblePerson: 'Admin Dept', dueDate: '2026-10-07', completed: false },
    ],
    keyFindings: [
      'Factory achieved 98.8% First-Pass audit rating in previous visit.',
      'Denim inseam chainstitch tension optimization commended.',
    ],
  },
  {
    id: 'evt-002',
    eventCode: 'EVT-2026-15',
    eventDate: '2026-10-01',
    endDate: '2026-10-31',
    timeSlot: 'Full Month Campaign',
    title: 'Annual Factory Quality Awareness Month Kickoff 2026',
    type: 'QUALITY_MONTH',
    location: 'Main Factory Auditorium & All Production Lines',
    leadOrganizer: 'HR & Quality Committee Directorate',
    department: 'Human Resources & Quality Governance',
    priority: 'HIGH',
    status: 'UPCOMING',
    readinessPercentage: 90,
    attendeesCount: 450,
    agendaSummary: 'Plant-wide campaign promoting Zero-Defect culture, operator needle safety pledges, best-operator awards, and 5S competition across all 18 sewing lines.',
    description: 'Annual flagship event engaging 2,200 garment workers in defect prevention competitions, skill matrix recognitions, and lean manufacturing awareness.',
    delegationMembers: [
      { id: 'att-201', name: 'Tanzim Ahmed', organization: 'FACTORY', department: 'Quality Assurance', role: 'Quality Committee Chair', confirmed: true },
      { id: 'att-202', name: 'Md. Al-Amin', organization: 'FACTORY', department: 'Training & Auditing', role: 'Event Master of Ceremonies', confirmed: true },
    ],
    itinerary: [
      { id: 'itin-201', timeSlot: '08:30 AM - 10:00 AM', activity: 'Grand Opening Rally & Quality Oath Ceremony', location: 'Main Factory Auditorium', facilitator: 'Tanzim Ahmed', completed: false },
      { id: 'itin-202', timeSlot: '10:30 AM - 12:00 PM', activity: 'Inter-Line 5S & Clean Workstation Competition Launch', location: 'Production Floors 1-3', facilitator: 'Md. Al-Amin', completed: false },
    ],
    preparationChecklist: [
      { id: 'chk-201', task: 'Print banner displays and zero-defect posters for all 18 line headboards', responsiblePerson: 'HR Team', dueDate: '2026-09-28', completed: true, completedDate: '2026-09-22' },
      { id: 'chk-202', task: 'Prepare awards trophies and cash bonuses for Top Quality Operators', responsiblePerson: 'Accounts Dept', dueDate: '2026-09-29', completed: true, completedDate: '2026-09-24' },
      { id: 'chk-203', task: 'Distribute Quality Awareness Month pins and T-shirts to all line leaders', responsiblePerson: 'Admin Dept', dueDate: '2026-09-30', completed: false },
    ],
  },
  {
    id: 'evt-003',
    eventCode: 'EVT-2026-16',
    eventDate: '2026-09-28',
    endDate: '2026-09-28',
    timeSlot: '10:00 AM - 01:30 PM',
    title: 'Pre-Production Pilot Run: Style STY-PL-889 (Tommy Hilfiger Polo)',
    type: 'PRE_PRODUCTION_MEETING',
    location: 'Sample Room & Sewing Line 05 Workstations',
    leadOrganizer: 'Technical Design & IE Dept',
    buyerName: 'Tommy Hilfiger / PVH Corp',
    department: 'Technical Engineering & Production',
    priority: 'HIGH',
    status: 'UPCOMING',
    readinessPercentage: 95,
    attendeesCount: 9,
    agendaSummary: 'Validate 100 pcs pilot run for pique cotton polo shirt, test collar flatlock rib attachment, confirm embroidery placement tolerances, and approve bulk cutting release.',
    description: 'Pre-production gate meeting required by PVH quality manual before commencing 45,000 pcs bulk order.',
    delegationMembers: [
      { id: 'att-301', name: 'Robert Chen', organization: 'BUYER', role: 'PVH Senior Technical Quality Lead', confirmed: true },
      { id: 'att-302', name: 'Kabir Hossain', organization: 'FACTORY', department: 'Cutting', role: 'Chief Cutting Master', confirmed: true },
      { id: 'att-303', name: 'Nasrin Sultana', organization: 'FACTORY', department: 'Sewing', role: 'Line 05 Supervisor', confirmed: true },
    ],
    itinerary: [
      { id: 'itin-301', timeSlot: '10:00 AM - 11:00 AM', activity: 'Pilot Garment Measurement Specification Verification', location: 'Sample Room', facilitator: 'Robert Chen', completed: false },
      { id: 'itin-302', timeSlot: '11:00 AM - 12:30 PM', activity: 'Sewing Line 05 Machine Speed & Feed Dog Balance Review', location: 'Line 05', facilitator: 'Babul Akter', completed: false },
      { id: 'itin-303', timeSlot: '12:30 PM - 01:30 PM', activity: 'Sign-off on PP Approval Certificate and Golden Sample Sealed Tag', location: 'Technical Conference Room', facilitator: 'Tanzim Ahmed', completed: false },
    ],
    preparationChecklist: [
      { id: 'chk-301', task: 'Stitch 100 pcs pilot garments under actual line conditions', responsiblePerson: 'Line 05 Team', dueDate: '2026-09-26', completed: true, completedDate: '2026-09-24' },
      { id: 'chk-302', task: 'Prepare full size-set measurement audit sheet (XS to XXL)', responsiblePerson: 'Sample QC', dueDate: '2026-09-27', completed: true, completedDate: '2026-09-25' },
    ],
  },
  {
    id: 'evt-004',
    eventCode: 'EVT-2026-17',
    eventDate: '2026-09-19',
    endDate: '2026-09-20',
    timeSlot: '09:00 AM - 05:30 PM',
    title: 'ISO 9001:2015 & WRAP Surveillance Audit Inspection',
    type: 'AUDIT_INSPECTION',
    location: 'Executive Conference Room & All Factory Sections',
    leadOrganizer: 'Quality Assurance & Compliance Directorate',
    department: 'Quality Governance & Compliance',
    priority: 'CRITICAL',
    status: 'CONCLUDED',
    readinessPercentage: 100,
    attendeesCount: 8,
    agendaSummary: 'Annual comprehensive surveillance audit by SGS Bangladesh evaluating Document Control, Calibration Registry, CAPA management, and social compliance.',
    description: 'Official accredited 3rd party surveillance audit ensuring zero critical non-conformances and renewing ISO 9001:2015 certification.',
    delegationMembers: [
      { id: 'att-401', name: 'Engr. Tareq Rahman', organization: 'AUDITOR', role: 'Lead QMS Auditor (SGS / IRCA)', confirmed: true },
      { id: 'att-402', name: 'Tanzim Ahmed', organization: 'FACTORY', department: 'Quality Assurance', role: 'Management Representative (MR)', confirmed: true },
    ],
    itinerary: [
      { id: 'itin-401', timeSlot: '09:00 AM - 10:00 AM', activity: 'Formal Opening Meeting with Senior Management', location: 'Executive Boardroom', facilitator: 'Engr. Tareq Rahman', completed: true },
      { id: 'itin-402', timeSlot: '10:00 AM - 04:00 PM', activity: 'Clause-by-Clause Departmental Audit (Clauses 4 through 10)', location: 'Entire Factory', facilitator: 'Tanzim Ahmed', completed: true },
      { id: 'itin-403', timeSlot: '04:30 PM - 05:30 PM', activity: 'Closing Meeting & Audit Verdict Announcement', location: 'Executive Boardroom', facilitator: 'Engr. Tareq Rahman', completed: true },
    ],
    preparationChecklist: [
      { id: 'chk-401', task: 'Reconcile all 12 SOP registers and Document Control change logs', responsiblePerson: 'Farhana Akhter', dueDate: '2026-09-17', completed: true, completedDate: '2026-09-16' },
      { id: 'chk-402', task: 'Verify calibration certificates for all 42 digital weigh scales and pull testers', responsiblePerson: 'Rashedul Islam', dueDate: '2026-09-18', completed: true, completedDate: '2026-09-17' },
    ],
    outcomesSummary: 'Auditor awarded Grade A Pass. Zero Major Non-Conformances; two minor observations closed on-site.',
    keyFindings: [
      'Document control digital repository commended as best-practice.',
      'Needle policy sticky tape reconstitution confirmed 100% compliant.',
    ],
  },
  {
    id: 'evt-005',
    eventCode: 'EVT-2026-18',
    eventDate: '2026-09-12',
    endDate: '2026-09-13',
    timeSlot: '06:00 AM - 08:00 PM',
    title: 'Semi-Annual Machine Calibration & Preventive Maintenance Shutdown',
    type: 'MAINTENANCE_SHUTDOWN',
    location: 'Sewing Lines 01-18, Boiler House & Compressor Room',
    leadOrganizer: 'Maintenance, Engineering & Utility Dept',
    department: 'Plant Maintenance & Engineering',
    priority: 'HIGH',
    status: 'CONCLUDED',
    readinessPercentage: 100,
    attendeesCount: 24,
    agendaSummary: 'Planned factory shutdown to conduct deep overhauling of sewing machine motors, calibrate digital thermostats on fusing machines, and service steam boilers.',
    description: 'Scheduled engineering maintenance window to guarantee machine zero-breakdown reliability during peak export shipping quarters.',
    delegationMembers: [
      { id: 'att-501', name: 'Babul Akter', organization: 'FACTORY', department: 'Maintenance', role: 'Chief Mechanical Engineer', confirmed: true },
      { id: 'att-502', name: 'Rashedul Islam', organization: 'FACTORY', department: 'Testing Lab', role: 'Calibration In-Charge', confirmed: true },
    ],
    preparationChecklist: [
      { id: 'chk-501', task: 'Procure spare heating elements for Hashima fusing presses', responsiblePerson: 'Procurement', dueDate: '2026-09-10', completed: true, completedDate: '2026-09-08' },
      { id: 'chk-502', task: 'Service air compressor filters and drain condensation tanks', responsiblePerson: 'Utility Team', dueDate: '2026-09-12', completed: true, completedDate: '2026-09-12' },
    ],
    outcomesSummary: 'Successfully serviced 340 sewing machines, 4 fusing presses, and 2 boilers with zero accidents.',
  },
];

export const EVENT_TYPE_CONFIG: Record<
  string,
  { label: string; badgeClass: string; tone: 'blue' | 'emerald' | 'amber' | 'indigo' | 'purple' | 'rose' }
> = {
  BUYER_VISIT: {
    label: 'Buyer QA Delegation Visit',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
    tone: 'blue',
  },
  PRE_PRODUCTION_MEETING: {
    label: 'PP Meeting & Pilot Run',
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-200',
    tone: 'purple',
  },
  QUALITY_MONTH: {
    label: 'Quality Month & Campaign',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    tone: 'emerald',
  },
  AUDIT_INSPECTION: {
    label: 'Audit & Certification',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200',
    tone: 'rose',
  },
  MAINTENANCE_SHUTDOWN: {
    label: 'Maintenance & Calibration',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
    tone: 'amber',
  },
  TRAINING_SEMINAR: {
    label: 'Technical QMS Workshop',
    badgeClass: 'bg-cyan-50 text-cyan-700 border-cyan-200',
    tone: 'blue',
  },
  MANAGEMENT_REVIEW: {
    label: 'ISO Management Review',
    badgeClass: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    tone: 'indigo',
  },
};
